import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { run, type Manifest } from "./build.ts";

export async function compileExtension(
  root: string,
  manifest: Manifest,
  output: string,
): Promise<void> {
  const zig = process.env.ZIG ?? "zig";
  const check = Bun.spawn([zig, "version"], { stdout: "pipe", stderr: "inherit" });
  const version = (await new Response(check.stdout).text()).trim();
  if ((await check.exited) !== 0 || !/^0\.16\./.test(version))
    throw new Error(
      `This template requires Zig 0.16.x; found ${version || "an unknown version"}. Set ZIG to its executable path.`,
    );
  const native = join(root, "native");
  writeFileSync(
    join(native, "build_info.zig"),
    `// Generated by scripts/build.ts; edit quickgui.extension.json instead.\npub const name = ${JSON.stringify(manifest.name)};\npub const version = ${JSON.stringify(manifest.version)};\n`,
  );
  await run(
    [
      zig,
      "build-lib",
      "extension.zig",
      "-dynamic",
      "-O",
      "ReleaseSafe",
      "-lc",
      "-I",
      ".",
      "--name",
      manifest.library,
      `-femit-bin=${output}`,
    ],
    native,
  );
}
