// Generated by @quickgui/cli from modules/git/main.zig. Do not edit: `quickgui dev`,
// `quickgui build`, and `quickgui modules` rewrite this file whenever the Zig source changes.
/* eslint-disable */
import { bindNativeModule, type NativeModuleBinding } from "@quickgui/native/modules";

const binding: NativeModuleBinding = {"abi":1,"functions":[{"name":"parseDiff","params":["allocator","string","boolean"],"result":"json"},{"name":"parseGitHeaderPaths","params":["string"],"result":"json"},{"name":"openDiff","params":["allocator","string","boolean","number"],"result":"json"},{"name":"closeDiff","params":["number"],"result":"boolean"},{"name":"openDiffCount","params":[],"result":"number"},{"name":"diffRows","params":["allocator","number","number","number"],"result":"json"},{"name":"diffFile","params":["number","number"],"result":"json"},{"name":"diffSelectedLines","params":["allocator","number","json"],"result":"json"},{"name":"renderDiff","params":["allocator","number"],"result":"string"}]};

function loadAddon(): unknown {
  try {
    // A literal relative path lets Bun embed the addon in the compiled application.
    return require("../../.quickgui/modules/git/darwin-arm64/git.node");
  } catch (error) {
    throw new Error("The native module \"git\" is not built for this host. Run `quickgui modules` (or `quickgui dev`).", { cause: error });
  }
}

const native = bindNativeModule("git", loadAddon(), binding);

/** Zig `main.DiffFile`. */
export interface DiffFile {
  kind: DiffFileKind;
  oldPath: string | null;
  newPath: string | null;
  path: string;
  binary: boolean;
  oldMode?: string | null;
  newMode?: string | null;
  similarity?: number | null;
  hunks: DiffHunk[];
  truncated: boolean;
}

/** Zig `main.HeaderPaths`. */
export interface HeaderPaths {
  oldPath: string;
  newPath: string;
}

/** Zig `main.DiffSummary`. */
export interface DiffSummary {
  id: number;
  files: DiffFileSummary[];
  rowCount: number;
  added: number;
  removed: number;
}

/** Zig `main.DiffRow`. */
export interface DiffRow {
  kind: DiffRowKind;
  fileIndex: number;
  hunkIndex: number;
  lineIndex: number;
  lineKind: DiffLineKind;
  text: string;
  oldLineNumber: number | null;
  newLineNumber: number | null;
  noNewline: boolean;
}

/** Zig `main.DiffLineGroup`. */
export interface DiffLineGroup {
  fileIndex: number;
  hunkIndex: number;
  lines: number[];
}

/** Zig `main.DiffFileKind`. */
export type DiffFileKind = "modified" | "added" | "deleted" | "renamed" | "copied";

/** Zig `main.DiffHunk`. */
export interface DiffHunk {
  oldStart: number;
  oldLines: number;
  newStart: number;
  newLines: number;
  heading: string;
  lines: DiffLine[];
}

/** Zig `main.DiffFileSummary`. */
export interface DiffFileSummary {
  kind: DiffFileKind;
  oldPath: string | null;
  newPath: string | null;
  path: string;
  binary: boolean;
  oldMode?: string | null;
  newMode?: string | null;
  similarity?: number | null;
  hunkCount: number;
  lineCount: number;
  added: number;
  removed: number;
  truncated: boolean;
}

/** Zig `main.DiffRowKind`. */
export type DiffRowKind = "file" | "hunk" | "line" | "notice";

/** Zig `main.DiffLineKind`. */
export type DiffLineKind = "context" | "added" | "removed";

/** Zig `main.DiffLine`. */
export interface DiffLine {
  kind: DiffLineKind;
  text: string;
  oldLineNumber: number | null;
  newLineNumber: number | null;
  noNewline: boolean;
}

/**
 * Parse the complete output of `git diff` into files. `truncated` marks the last file when the
 * output hit the app's byte bound.
 *
 * Zig: `pub fn parseDiff(allocator: Allocator, output: []const u8, truncated: bool) ![]DiffFile`
 */
export function parseDiff(output: string | Uint8Array, truncated: boolean): DiffFile[] {
  return native.call(0, [output, truncated]) as DiffFile[];
}

/**
 * Like `parseDiff`, but runs on the native thread pool and resolves when it finishes.
 *
 * Zig: `pub fn parseDiff(allocator: Allocator, output: []const u8, truncated: bool) ![]DiffFile`
 */
export function parseDiffAsync(output: string | Uint8Array, truncated: boolean): Promise<DiffFile[]> {
  return native.callAsync(0, [output, truncated]) as Promise<DiffFile[]>;
}

/**
 * Split the `a/<old> b/<new>` pair of a `diff --git` line.
 *
 * Paths may contain spaces, so the split point is the ` b/` whose two halves agree when the file
 * kept its name; otherwise the first ` b/` after `a/` is used and later header lines correct it.
 *
 * Zig: `pub fn parseGitHeaderPaths(pair: []const u8) HeaderPaths`
 */
export function parseGitHeaderPaths(pair: string | Uint8Array): HeaderPaths {
  return native.call(1, [pair]) as HeaderPaths;
}

/**
 * Like `parseGitHeaderPaths`, but runs on the native thread pool and resolves when it finishes.
 *
 * Zig: `pub fn parseGitHeaderPaths(pair: []const u8) HeaderPaths`
 */
export function parseGitHeaderPathsAsync(pair: string | Uint8Array): Promise<HeaderPaths> {
  return native.callAsync(1, [pair]) as Promise<HeaderPaths>;
}

/**
 * Parse `output` and keep the result until `closeDiff`. Safe to call through the thread pool.
 *
 * Zig: `pub fn openDiff(allocator: Allocator, output: []const u8, truncated: bool, maxRows: u32) !DiffSummary`
 */
export function openDiff(output: string | Uint8Array, truncated: boolean, maxRows: number): DiffSummary {
  return native.call(2, [output, truncated, maxRows]) as DiffSummary;
}

/**
 * Like `openDiff`, but runs on the native thread pool and resolves when it finishes.
 *
 * Zig: `pub fn openDiff(allocator: Allocator, output: []const u8, truncated: bool, maxRows: u32) !DiffSummary`
 */
export function openDiffAsync(output: string | Uint8Array, truncated: boolean, maxRows: number): Promise<DiffSummary> {
  return native.callAsync(2, [output, truncated, maxRows]) as Promise<DiffSummary>;
}

/**
 * Release a diff. Returns false when the handle is unknown (already closed).
 *
 * Zig: `pub fn closeDiff(id: u32) bool`
 */
export function closeDiff(id: number): boolean {
  return native.call(3, [id]) as boolean;
}

/**
 * Like `closeDiff`, but runs on the native thread pool and resolves when it finishes.
 *
 * Zig: `pub fn closeDiff(id: u32) bool`
 */
export function closeDiffAsync(id: number): Promise<boolean> {
  return native.callAsync(3, [id]) as Promise<boolean>;
}

/**
 * Number of diffs currently held, for tests.
 *
 * Zig: `pub fn openDiffCount() u32`
 */
export function openDiffCount(): number {
  return native.call(4, []) as number;
}

/**
 * Like `openDiffCount`, but runs on the native thread pool and resolves when it finishes.
 *
 * Zig: `pub fn openDiffCount() u32`
 */
export function openDiffCountAsync(): Promise<number> {
  return native.callAsync(4, []) as Promise<number>;
}

/**
 * The table rows in `[start, end)`, clipped to the diff.
 *
 * Zig: `pub fn diffRows(allocator: Allocator, id: u32, start: u32, end: u32) ![]DiffRow`
 */
export function diffRows(id: number, start: number, end: number): DiffRow[] {
  return native.call(5, [id, start, end]) as DiffRow[];
}

/**
 * Like `diffRows`, but runs on the native thread pool and resolves when it finishes.
 *
 * Zig: `pub fn diffRows(allocator: Allocator, id: u32, start: u32, end: u32) ![]DiffRow`
 */
export function diffRowsAsync(id: number, start: number, end: number): Promise<DiffRow[]> {
  return native.callAsync(5, [id, start, end]) as Promise<DiffRow[]>;
}

/**
 * One file with all its hunks, for building a patch.
 *
 * Zig: `pub fn diffFile(id: u32, fileIndex: u32) !DiffFile`
 */
export function diffFile(id: number, fileIndex: number): DiffFile {
  return native.call(6, [id, fileIndex]) as DiffFile;
}

/**
 * Like `diffFile`, but runs on the native thread pool and resolves when it finishes.
 *
 * Zig: `pub fn diffFile(id: u32, fileIndex: u32) !DiffFile`
 */
export function diffFileAsync(id: number, fileIndex: number): Promise<DiffFile> {
  return native.callAsync(6, [id, fileIndex]) as Promise<DiffFile>;
}

/**
 * The changed lines inside the table's selected row ranges (inclusive), grouped by hunk in the
 * order they were first seen.
 *
 * Zig: `pub fn diffSelectedLines(allocator: Allocator, id: u32, ranges: []const [2]u32) ![]DiffLineGroup`
 */
export function diffSelectedLines(id: number, ranges: number[][]): DiffLineGroup[] {
  return native.call(7, [id, ranges]) as DiffLineGroup[];
}

/**
 * Like `diffSelectedLines`, but runs on the native thread pool and resolves when it finishes.
 *
 * Zig: `pub fn diffSelectedLines(allocator: Allocator, id: u32, ranges: []const [2]u32) ![]DiffLineGroup`
 */
export function diffSelectedLinesAsync(id: number, ranges: number[][]): Promise<DiffLineGroup[]> {
  return native.callAsync(7, [id, ranges]) as Promise<DiffLineGroup[]>;
}

/**
 * The diff as text for a prompt: one header per file, hunk headers, and marked lines.
 *
 * Zig: `pub fn renderDiff(allocator: Allocator, id: u32) ![]const u8`
 */
export function renderDiff(id: number): string {
  return native.call(8, [id]) as string;
}

/**
 * Like `renderDiff`, but runs on the native thread pool and resolves when it finishes.
 *
 * Zig: `pub fn renderDiff(allocator: Allocator, id: u32) ![]const u8`
 */
export function renderDiffAsync(id: number): Promise<string> {
  return native.callAsync(8, [id]) as Promise<string>;
}
