// Generated by @quickgui/cli from modules/git/main.zig. Do not edit: `quickgui dev`,
// `quickgui build`, and `quickgui modules` rewrite this file whenever the Zig source changes.
/* eslint-disable */
import {
  NativeArguments,
  allocateNativeModuleRequest,
  awaitNativeModuleResult,
  decodeNativeBoolean,
  decodeNativeJson,
  decodeNativeNumber,
  decodeNativeString,
} from "@quickgui/native/modules";

// The module's C entry points. `@quickgui/cli` binds them through the scriptc FFI manifest when
// it compiles the application; they are not callable under Bun or Node.
declare function quickgui_module_git_call(index: number, args: Uint8Array, reply: (result: Uint8Array) => void): void;
declare function quickgui_module_git_call_async(request: number, index: number, args: Uint8Array): void;

function call(index: number, args: Uint8Array): Uint8Array {
  let result: Uint8Array = new Uint8Array(0);
  quickgui_module_git_call(index, args, (bytes: Uint8Array): void => {
    result = bytes;
  });
  return result;
}

function callAsync(index: number, args: Uint8Array): Promise<Uint8Array> {
  const request = allocateNativeModuleRequest();
  const result = awaitNativeModuleResult(request);
  quickgui_module_git_call_async(request, index, args);
  return result;
}

/** Zig `main.DiffFile`. */
export interface DiffFile {
  kind: DiffFileKind;
  oldPath: string | null;
  newPath: string | null;
  path: string;
  binary: boolean;
  oldMode?: string | null;
  newMode?: string | null;
  similarity?: number | null;
  hunks: DiffHunk[];
  truncated: boolean;
}

/** Zig `main.HeaderPaths`. */
export interface HeaderPaths {
  oldPath: string;
  newPath: string;
}

/** Zig `main.DiffSummary`. */
export interface DiffSummary {
  id: number;
  files: DiffFileSummary[];
  rowCount: number;
  added: number;
  removed: number;
}

/** Zig `main.DiffRow`. */
export interface DiffRow {
  kind: DiffRowKind;
  fileIndex: number;
  hunkIndex: number;
  lineIndex: number;
  lineKind: DiffLineKind;
  text: string;
  oldLineNumber: number | null;
  newLineNumber: number | null;
  noNewline: boolean;
}

/** Zig `main.DiffLineGroup`. */
export interface DiffLineGroup {
  fileIndex: number;
  hunkIndex: number;
  lines: number[];
}

/** Zig `main.DiffFileKind`. */
export type DiffFileKind = "modified" | "added" | "deleted" | "renamed" | "copied";

/** Zig `main.DiffHunk`. */
export interface DiffHunk {
  oldStart: number;
  oldLines: number;
  newStart: number;
  newLines: number;
  heading: string;
  lines: DiffLine[];
}

/** Zig `main.DiffFileSummary`. */
export interface DiffFileSummary {
  kind: DiffFileKind;
  oldPath: string | null;
  newPath: string | null;
  path: string;
  binary: boolean;
  oldMode?: string | null;
  newMode?: string | null;
  similarity?: number | null;
  hunkCount: number;
  lineCount: number;
  added: number;
  removed: number;
  truncated: boolean;
}

/** Zig `main.DiffRowKind`. */
export type DiffRowKind = "file" | "hunk" | "line" | "notice";

/** Zig `main.DiffLineKind`. */
export type DiffLineKind = "context" | "added" | "removed";

/** Zig `main.DiffLine`. */
export interface DiffLine {
  kind: DiffLineKind;
  text: string;
  oldLineNumber: number | null;
  newLineNumber: number | null;
  noNewline: boolean;
}

/**
 * Parse the complete output of `git diff` into files. `truncated` marks the last file when the
 * output hit the app's byte bound.
 *
 * Zig: `pub fn parseDiff(allocator: Allocator, output: []const u8, truncated: bool) ![]DiffFile`
 */
export function parseDiff(output: string, truncated: boolean): DiffFile[] {
  const args = new NativeArguments(2);
  args.string(output);
  args.boolean(truncated);
  return JSON.parse(decodeNativeJson("git", "parseDiff", call(0, args.finish()))) as DiffFile[];
}

/**
 * Like `parseDiff`, but runs on its own thread and resolves when it finishes.
 *
 * Zig: `pub fn parseDiff(allocator: Allocator, output: []const u8, truncated: bool) ![]DiffFile`
 */
export async function parseDiffAsync(output: string, truncated: boolean): Promise<DiffFile[]> {
  const args = new NativeArguments(2);
  args.string(output);
  args.boolean(truncated);
  return JSON.parse(decodeNativeJson("git", "parseDiff", await callAsync(0, args.finish()))) as DiffFile[];
}

/**
 * Split the `a/<old> b/<new>` pair of a `diff --git` line.
 *
 * Paths may contain spaces, so the split point is the ` b/` whose two halves agree when the file
 * kept its name; otherwise the first ` b/` after `a/` is used and later header lines correct it.
 *
 * Zig: `pub fn parseGitHeaderPaths(pair: []const u8) HeaderPaths`
 */
export function parseGitHeaderPaths(pair: string): HeaderPaths {
  const args = new NativeArguments(1);
  args.string(pair);
  return JSON.parse(decodeNativeJson("git", "parseGitHeaderPaths", call(1, args.finish()))) as HeaderPaths;
}

/**
 * Like `parseGitHeaderPaths`, but runs on its own thread and resolves when it finishes.
 *
 * Zig: `pub fn parseGitHeaderPaths(pair: []const u8) HeaderPaths`
 */
export async function parseGitHeaderPathsAsync(pair: string): Promise<HeaderPaths> {
  const args = new NativeArguments(1);
  args.string(pair);
  return JSON.parse(decodeNativeJson("git", "parseGitHeaderPaths", await callAsync(1, args.finish()))) as HeaderPaths;
}

/**
 * Parse `output` and keep the result until `closeDiff`. Safe to call through the thread pool.
 *
 * Zig: `pub fn openDiff(allocator: Allocator, output: []const u8, truncated: bool, maxRows: u32) !DiffSummary`
 */
export function openDiff(output: string, truncated: boolean, maxRows: number): DiffSummary {
  const args = new NativeArguments(3);
  args.string(output);
  args.boolean(truncated);
  args.number(maxRows);
  return JSON.parse(decodeNativeJson("git", "openDiff", call(2, args.finish()))) as DiffSummary;
}

/**
 * Like `openDiff`, but runs on its own thread and resolves when it finishes.
 *
 * Zig: `pub fn openDiff(allocator: Allocator, output: []const u8, truncated: bool, maxRows: u32) !DiffSummary`
 */
export async function openDiffAsync(output: string, truncated: boolean, maxRows: number): Promise<DiffSummary> {
  const args = new NativeArguments(3);
  args.string(output);
  args.boolean(truncated);
  args.number(maxRows);
  return JSON.parse(decodeNativeJson("git", "openDiff", await callAsync(2, args.finish()))) as DiffSummary;
}

/**
 * Release a diff. Returns false when the handle is unknown (already closed).
 *
 * Zig: `pub fn closeDiff(id: u32) bool`
 */
export function closeDiff(id: number): boolean {
  const args = new NativeArguments(1);
  args.number(id);
  return decodeNativeBoolean("git", "closeDiff", call(3, args.finish()));
}

/**
 * Like `closeDiff`, but runs on its own thread and resolves when it finishes.
 *
 * Zig: `pub fn closeDiff(id: u32) bool`
 */
export async function closeDiffAsync(id: number): Promise<boolean> {
  const args = new NativeArguments(1);
  args.number(id);
  return decodeNativeBoolean("git", "closeDiff", await callAsync(3, args.finish()));
}

/**
 * Number of diffs currently held, for tests.
 *
 * Zig: `pub fn openDiffCount() u32`
 */
export function openDiffCount(): number {
  const args = new NativeArguments(0);
  return decodeNativeNumber("git", "openDiffCount", call(4, args.finish()));
}

/**
 * Like `openDiffCount`, but runs on its own thread and resolves when it finishes.
 *
 * Zig: `pub fn openDiffCount() u32`
 */
export async function openDiffCountAsync(): Promise<number> {
  const args = new NativeArguments(0);
  return decodeNativeNumber("git", "openDiffCount", await callAsync(4, args.finish()));
}

/**
 * The table rows in `[start, end)`, clipped to the diff.
 *
 * Zig: `pub fn diffRows(allocator: Allocator, id: u32, start: u32, end: u32) ![]DiffRow`
 */
export function diffRows(id: number, start: number, end: number): DiffRow[] {
  const args = new NativeArguments(3);
  args.number(id);
  args.number(start);
  args.number(end);
  return JSON.parse(decodeNativeJson("git", "diffRows", call(5, args.finish()))) as DiffRow[];
}

/**
 * Like `diffRows`, but runs on its own thread and resolves when it finishes.
 *
 * Zig: `pub fn diffRows(allocator: Allocator, id: u32, start: u32, end: u32) ![]DiffRow`
 */
export async function diffRowsAsync(id: number, start: number, end: number): Promise<DiffRow[]> {
  const args = new NativeArguments(3);
  args.number(id);
  args.number(start);
  args.number(end);
  return JSON.parse(decodeNativeJson("git", "diffRows", await callAsync(5, args.finish()))) as DiffRow[];
}

/**
 * One file with all its hunks, for building a patch.
 *
 * Zig: `pub fn diffFile(id: u32, fileIndex: u32) !DiffFile`
 */
export function diffFile(id: number, fileIndex: number): DiffFile {
  const args = new NativeArguments(2);
  args.number(id);
  args.number(fileIndex);
  return JSON.parse(decodeNativeJson("git", "diffFile", call(6, args.finish()))) as DiffFile;
}

/**
 * Like `diffFile`, but runs on its own thread and resolves when it finishes.
 *
 * Zig: `pub fn diffFile(id: u32, fileIndex: u32) !DiffFile`
 */
export async function diffFileAsync(id: number, fileIndex: number): Promise<DiffFile> {
  const args = new NativeArguments(2);
  args.number(id);
  args.number(fileIndex);
  return JSON.parse(decodeNativeJson("git", "diffFile", await callAsync(6, args.finish()))) as DiffFile;
}

/**
 * The changed lines inside the table's selected row ranges (inclusive), grouped by hunk in the
 * order they were first seen.
 *
 * Zig: `pub fn diffSelectedLines(allocator: Allocator, id: u32, ranges: []const [2]u32) ![]DiffLineGroup`
 */
export function diffSelectedLines(id: number, ranges: number[][]): DiffLineGroup[] {
  const args = new NativeArguments(2);
  args.number(id);
  args.json(JSON.stringify(ranges));
  return JSON.parse(decodeNativeJson("git", "diffSelectedLines", call(7, args.finish()))) as DiffLineGroup[];
}

/**
 * Like `diffSelectedLines`, but runs on its own thread and resolves when it finishes.
 *
 * Zig: `pub fn diffSelectedLines(allocator: Allocator, id: u32, ranges: []const [2]u32) ![]DiffLineGroup`
 */
export async function diffSelectedLinesAsync(id: number, ranges: number[][]): Promise<DiffLineGroup[]> {
  const args = new NativeArguments(2);
  args.number(id);
  args.json(JSON.stringify(ranges));
  return JSON.parse(decodeNativeJson("git", "diffSelectedLines", await callAsync(7, args.finish()))) as DiffLineGroup[];
}

/**
 * The diff as text for a prompt: one header per file, hunk headers, and marked lines.
 *
 * Zig: `pub fn renderDiff(allocator: Allocator, id: u32) ![]const u8`
 */
export function renderDiff(id: number): string {
  const args = new NativeArguments(1);
  args.number(id);
  return decodeNativeString("git", "renderDiff", call(8, args.finish()));
}

/**
 * Like `renderDiff`, but runs on its own thread and resolves when it finishes.
 *
 * Zig: `pub fn renderDiff(allocator: Allocator, id: u32) ![]const u8`
 */
export async function renderDiffAsync(id: number): Promise<string> {
  const args = new NativeArguments(1);
  args.number(id);
  return decodeNativeString("git", "renderDiff", await callAsync(8, args.finish()));
}
