/**
 * Generate `generated.ts` from the property table: the `Style`, `StateStyleProps`, and
 * `NativeProps` interfaces plus the run-time `applyStyle` and `applyProps` functions.
 *
 * Run with `bun run generate` inside `packages/ui`.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  KIND_BACKGROUND,
  KIND_GRID_PLACEMENT,
  KIND_JSON,
  KIND_STATE,
  KIND_GROUP_STATE,
  eventTable,
  propertyTable,
  setterForKind,
  stateNames,
  typeForEntry,
  type PropertyEntry,
} from "../style-table.ts";

const lines: string[] = [];
const out = (line: string): void => {
  lines.push(line);
};

out("// Generated by scripts/generate.ts from style-table.ts. Do not edit by hand.");
out("");
out('import type { NativeNode, QuickGuiEvent } from "@quickgui/native";');
out("");
out("import {");
const setters = new Set<string>();
for (const entry of propertyTable) setters.add(setterForKind(entry.kind));
setters.add("setListener");
setters.add("insertChildren");
for (const setter of [...setters].sort()) out(`  ${setter},`);
out('} from "./runtime.ts";');
out("import type {");
for (const name of [
  "ComponentAppearance",
  "ComponentItem",
  "DragSource",
  "DropKind",
  "Extent",
  "GradientDeclaration",
  "GroupStateStyle",
  "Keymap",
  "OptionSource",
  "StateStyle",
  "StringMap",
  "TableColumn",
  "TableEditing",
  "TerminalPalette",
  "TextShadowDeclaration",
  "ToastDeclaration",
  "TransformMatrix",
  "TransitionDeclaration",
  "TreeNode",
  "TreeNodeChildren",
]) {
  out(`  ${name},`);
}
out('} from "./types.ts";');
out('import type { Children } from "./runtime.ts";');
out('import { createRenderEffect, type Accessor } from "./reactive.ts";');
out("");

const styleEntries = propertyTable.filter((entry) => entry.style);
const propEntries = propertyTable.filter((entry) => !entry.style);
const seenStyle = new Set<string>();

out("/** Every style the host understands, including the nested interaction states. */");
out("export interface Style {");
for (const entry of styleEntries) {
  if (seenStyle.has(entry.name)) continue;
  seenStyle.add(entry.name);
  out(`  ${entry.name}?: ${typeForEntry(entry)};`);
}
out("}");
out("");
out("/** Props every host element accepts: the styles that are not interaction states, element props, and events. */");
out("export interface NativeProps {");
out("  children?: Children;");
out("  style?: Style | Style[];");
out("  ref?: (node: NativeNode) => void;");
for (const entry of styleEntries) {
  if (stateNames.includes(entry.name)) continue;
  out(`  ${entry.name}?: ${typeForEntry(entry)};`);
}
const seenProp = new Set<string>();
for (const entry of propEntries) {
  if (seenProp.has(entry.name)) continue;
  seenProp.add(entry.name);
  out(`  ${entry.name}?: ${typeForEntry(entry)};`);
}
const seenEvent = new Set<string>();
for (const event of eventTable) {
  if (seenEvent.has(event.name)) continue;
  seenEvent.add(event.name);
  out(`  ${event.name}?: (event: QuickGuiEvent) => void;`);
}
out("}");
out("");

function setterCall(entry: PropertyEntry, value: string): string {
  const setter = setterForKind(entry.kind);
  if (entry.kind === KIND_BACKGROUND) return `${setter}(node, ${entry.code}, ${entry.secondary ?? 0}, ${value})`;
  if (entry.kind === KIND_GRID_PLACEMENT) return `${setter}(node, ${entry.secondary === 1 ? "true" : "false"}, ${value})`;
  if (entry.kind === KIND_STATE || entry.kind === KIND_GROUP_STATE) return `${setter}(node, ${entry.code}, ${JSON.stringify(entry.name)}, ${value})`;
  if (entry.kind === KIND_JSON) return `${setter}(node, ${entry.code}, ${entry.secondary ?? 65536}, ${value})`;
  return `${setter}(node, ${entry.code}, ${value})`;
}

out("/** Apply a whole style record, sending only the properties that changed since `prev`. */");
out("export function applyStyle(node: NativeNode, next: Style, prev: Style | undefined): void {");
out("  if (prev === undefined) {");
seenStyle.clear();
for (const entry of styleEntries) {
  if (seenStyle.has(entry.name)) continue;
  seenStyle.add(entry.name);
  out(`    if (next.${entry.name} !== undefined) ${setterCall(entry, `next.${entry.name}`)};`);
}
out("    return;");
out("  }");
seenStyle.clear();
for (const entry of styleEntries) {
  if (seenStyle.has(entry.name)) continue;
  seenStyle.add(entry.name);
  out(`  if (next.${entry.name} !== prev.${entry.name}) ${setterCall(entry, `next.${entry.name}`)};`);
}
out("}");
out("");
out("// Property codes of the element props, for components that set them outside JSX.");
seenProp.clear();
for (const entry of propEntries) {
  if (seenProp.has(entry.name)) continue;
  seenProp.add(entry.name);
  const constant = entry.name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
  out(`export const CODE_${constant} = ${entry.code};`);
}
out("");
out("/** Copy every declared property of `source` over `target`; later styles in a list win. */");
out("export function mergeStyle(target: Style, source: Style): void {");
seenStyle.clear();
for (const entry of styleEntries) {
  if (seenStyle.has(entry.name)) continue;
  seenStyle.add(entry.name);
  out(`  if (source.${entry.name} !== undefined) target.${entry.name} = source.${entry.name};`);
}
out("}");
out("");
out("/** Apply a style list merged left to right; returns the merged record for the next diff. */");
out("export function applyStyleList(node: NativeNode, next: Style[], prev: Style | undefined): Style {");
out("  const merged: Style = {};");
out("  for (const style of next) mergeStyle(merged, style);");
out("  applyStyle(node, merged, prev);");
out("  return merged;");
out("}");
out("");
out("/** Keep a host element's style in sync with a reactive style record. */");
out("export function bindStyle(node: NativeNode, style: Accessor<Style>): void {");
out("  let previous: Style | undefined = undefined;");
out("  createRenderEffect(() => {");
out("    const next = style();");
out("    applyStyle(node, next, previous);");
out("    previous = next;");
out("  });");
out("}");
out("");
out("/** Keep a host element's style in sync with a reactive style list. */");
out("export function bindStyleList(node: NativeNode, styles: Accessor<Style[]>): void {");
out("  let previous: Style | undefined = undefined;");
out("  createRenderEffect(() => {");
out("    previous = applyStyleList(node, styles(), previous);");
out("  });");
out("}");
out("");
out("/** Apply a props record to a host element once, for components called without JSX. */");
out("export function applyProps(node: NativeNode, props: NativeProps): void {");
out("  const style = props.style;");
out("  if (style !== undefined) {");
out("    if (Array.isArray(style)) applyStyleList(node, style, undefined);");
out("    else applyStyle(node, style, undefined);");
out("  }");
seenStyle.clear();
for (const entry of styleEntries) {
  if (stateNames.includes(entry.name) || seenStyle.has(entry.name)) continue;
  seenStyle.add(entry.name);
  out(`  if (props.${entry.name} !== undefined) ${setterCall(entry, `props.${entry.name}`)};`);
}
seenProp.clear();
for (const entry of propEntries) {
  if (seenProp.has(entry.name)) continue;
  seenProp.add(entry.name);
  out(`  if (props.${entry.name} !== undefined) ${setterCall(entry, `props.${entry.name}`)};`);
}
seenEvent.clear();
for (const event of eventTable) {
  if (seenEvent.has(event.name)) continue;
  seenEvent.add(event.name);
  out(`  if (props.${event.name} !== undefined) setListener(node, ${event.type}, props.${event.name});`);
}
out("  if (props.children !== undefined) insertChildren(node, props.children);");
out("  if (props.ref !== undefined) props.ref(node);");
out("}");

writeFileSync(resolve(import.meta.dir, "..", "generated.ts"), lines.join("\n") + "\n");
console.log(`generated.ts: ${lines.length} lines`);
