package uiformat

import (
	"bytes"
	"go/format"
	"go/scanner"
	"go/token"
	"reflect"
	"strings"
	"testing"
)

func TestWrapsCallbacksWithoutChangingTokens(t *testing.T) {
	source := []byte(`package example
import gui "github.com/egoist/quickgui/go/ui"
func root() {
gui.Show(func() bool { return selected() }, func() {
gui.Button(gui.OnClick(func() { increment() }), gui.BackgroundColor("#ccc"), "Increment")
}, func() { fallback() })
}`)
	result := checkFormat(t, source)
	for _, want := range []string{
		"gui.Show(\n",
		"func() bool { return selected() },\n",
		"gui.Button(\n",
		"gui.OnClick(func() { increment() }),\n",
		"},\n\t\tfunc() { fallback() },\n\t)",
	} {
		if !strings.Contains(string(result), want) {
			t.Errorf("missing %q in:\n%s", want, result)
		}
	}
}

func TestPreservesCommentsRawStringsAndVariadics(t *testing.T) {
	source := []byte("package example\n" +
		"import ui \"github.com/egoist/quickgui/go/ui\"\n" +
		"func root() {\n" +
		"ui.View(/* leading, comma */ ui.Padding(20), // spacing\n" +
		"/* next argument */ ui.BackgroundColor(\"a long value which should wrap the containing UI declaration\"), `raw\n  text, stays exact`, args... /* final, comment */)\n" +
		"}")
	result := checkFormat(t, source)
	if !bytes.Contains(result, []byte("args..., /* final, comment */\n")) {
		t.Fatalf("variadic comma or comment was lost:\n%s", result)
	}
}

func TestWrapsPropertiesNestedCallsAndGenericCalls(t *testing.T) {
	source := []byte(`package example
import (
 gui "github.com/egoist/quickgui/go/ui"
 native "github.com/egoist/quickgui/go/native"
)
func root() {
gui.View(gui.Props{Style: gui.Style{Display: "flex", Width: "100%", Height: "100%", BackgroundColor: "#ccc"}, OnClick: func(event *native.Event) { handle(event) }}, func() { child() })
gui.For[int](values, func(item int, index func() int) *native.Node { return row(item, index) }, nil, nil)
}`)
	result := checkFormat(t, source)
	if !bytes.Contains(result, []byte("gui.Props{\n")) || !bytes.Contains(result, []byte("gui.Style{\n")) || !bytes.Contains(result, []byte("gui.For[int](\n")) {
		t.Fatalf("declarations were not wrapped:\n%s", result)
	}
}

func TestLeavesShortCallsAndOtherPackagesToGofmt(t *testing.T) {
	source := []byte(`package example
import (
 "github.com/egoist/quickgui/go/ui"
 other "example.com/ui"
)
func root() {
ui.Text(ui.FontSize(14), "Hello")
other.View(other.Padding(20), other.BackgroundColor("a long value that is not part of a QuickGUI UI declaration"), "Hello")
}`)
	want, err := format.Source(source)
	if err != nil {
		t.Fatal(err)
	}
	if got := checkFormat(t, source); !bytes.Equal(got, want) {
		t.Fatalf("unexpected wrapping:\n%s", got)
	}
}

func TestGeneratedFilesAndSyntaxErrors(t *testing.T) {
	generated := []byte("// Code generated by fixture. DO NOT EDIT.\npackage example\nfunc f( ){}\n")
	got, err := Source(generated, DefaultWidth)
	if err != nil || !bytes.Equal(got, generated) {
		t.Fatalf("generated source changed: %s, %v", got, err)
	}
	if _, err := Source([]byte("package incomplete\nfunc"), DefaultWidth); err == nil {
		t.Fatal("invalid Go must be rejected")
	}
	if _, err := Source([]byte("package example"), 0); err == nil {
		t.Fatal("invalid width must be rejected")
	}
}

func checkFormat(t *testing.T, source []byte) []byte {
	t.Helper()
	result, err := Source(source, DefaultWidth)
	if err != nil {
		t.Fatal(err)
	}
	again, err := Source(result, DefaultWidth)
	if err != nil || !bytes.Equal(result, again) {
		t.Fatalf("formatting is not idempotent: %v\n%s\n%s", err, result, again)
	}
	standard, err := format.Source(result)
	if err != nil || !bytes.Equal(result, standard) {
		t.Fatalf("gofmt changed the custom layout: %v\n%s", err, result)
	}
	baseline, err := format.Source(source)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(tokens(baseline), tokens(result)) {
		t.Fatalf("formatting changed Go tokens or comments:\n%s", result)
	}
	return result
}

func tokens(source []byte) []string {
	fs := token.NewFileSet()
	var scan scanner.Scanner
	scan.Init(fs.AddFile("", -1, len(source)), source, nil, scanner.ScanComments)
	var result []string
	for {
		_, kind, literal := scan.Scan()
		if kind == token.EOF {
			return result
		}
		if kind != token.COMMA && kind != token.SEMICOLON {
			result = append(result, kind.String()+":"+literal)
		}
	}
}
