import { copyFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { run, type Manifest } from "./build.ts";

export async function compileExtension(
  root: string,
  manifest: Manifest,
  output: string,
): Promise<void> {
  const native = join(root, "native");
  writeFileSync(
    join(native, "src/build_info.rs"),
    `// Generated by scripts/build.ts; edit quickgui.extension.json instead.\npub const NAME: &str = ${JSON.stringify(manifest.name)};\npub const VERSION: &str = ${JSON.stringify(manifest.version)};\n`,
  );

  // Set the host triple explicitly so a user's cross-compilation defaults cannot
  // accidentally put a foreign binary in the current host's artifact directory.
  const rustc = Bun.spawn([process.env.RUSTC ?? "rustc", "-vV"], {
    stdout: "pipe",
    stderr: "inherit",
  });
  const info = await new Response(rustc.stdout).text();
  if ((await rustc.exited) !== 0) throw new Error("Could not determine the Rust host target");
  const triple = /^host: (.+)$/m.exec(info)?.[1];
  if (!triple) throw new Error("rustc did not report a host target");
  const target = join(native, "target");
  await run(
    [process.env.CARGO ?? "cargo", "build", "--release", "--lib", "--target", triple],
    native,
    { ...process.env, CARGO_TARGET_DIR: target },
  );
  // Cargo's library name is set in native/Cargo.toml; the manifest controls the
  // published filename, so changing the manifest does not break artifact lookup.
  const filename = basename(output).replace(manifest.library, "{{LIBRARY}}");
  copyFileSync(join(target, triple, "release", filename), output);
}
