// Command componentsgen generates the typed compound-component instance API.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type method struct{ name, props, factory string }
type field struct{ name, typ string }

func main() {
	check := flag.Bool("check", false, "check generated output")
	flag.Parse()
	fset := token.NewFileSet()
	paths, err := filepath.Glob("*.go")
	must(err)
	structs := map[string]*ast.StructType{}
	apis := map[string][]method{}
	render := func(node ast.Node) string { var b bytes.Buffer; must(format.Node(&b, fset, node)); return b.String() }
	for _, path := range paths {
		if strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, "_generated.go") {
			continue
		}
		file, err := parser.ParseFile(fset, path, nil, 0)
		must(err)
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch s := spec.(type) {
					case *ast.TypeSpec:
						if typ, ok := s.Type.(*ast.StructType); ok {
							structs[s.Name.Name] = typ
						}
					}
				}
			case *ast.FuncDecl:
				if d.Recv == nil || len(d.Type.Params.List) == 0 {
					continue
				}
				recv, ok := d.Recv.List[0].Type.(*ast.Ident)
				if !ok || !strings.HasSuffix(recv.Name, "API") {
					continue
				}
				prop, ok := d.Type.Params.List[0].Type.(*ast.Ident)
				if !ok {
					continue
				}
				apis[recv.Name] = append(apis[recv.Name], method{d.Name.Name, prop.Name, recv.Name})
			}
		}
	}
	var fields func(string) []field
	fields = func(name string) []field {
		var result []field
		s := structs[name]
		if s == nil {
			return result
		}
		for _, f := range s.Fields.List {
			if len(f.Names) == 0 {
				if id, ok := f.Type.(*ast.Ident); ok {
					result = append(result, fields(id.Name)...)
				}
			} else {
				for _, n := range f.Names {
					result = append(result, field{n.Name, render(f.Type)})
				}
			}
		}
		return result
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go run ../internal/cmd/componentsgen; DO NOT EDIT.\n\npackage ui\n\nimport \"github.com/egoist/quickgui/go/native\"")
	keys := make([]string, 0, len(apis))
	for key := range apis {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	transparent := map[string]bool{"Popover": true, "SystemPopover": true, "Dialog": true, "AlertDialog": true, "Tooltip": true, "Toast": true, "Menu": true, "PopoverMenu": true, "ContextMenu": true}
	// Required identity/position arguments belong on a part, just as in Rust.
	identity := map[string]string{
		"Tabs.Tab": "Value", "Tabs.Panel": "Value", "Accordion.Item": "Value", "ToggleGroup.Item": "Value",
		"Splitter.Pane": "Index", "Splitter.Handle": "Index", "DateField.Segment": "Segment", "TimeField.Segment": "Segment",
		"Calendar.Week": "Index", "Calendar.Day": "Day", "OtpField.Input": "Index", "OtpField.Separator": "Index",
	}
	for _, api := range keys {
		base := strings.TrimSuffix(api, "API")
		name := strings.ToUpper(base[:1]) + base[1:]
		if strings.HasPrefix(name, "SwiftUI") {
			continue
		}
		if name == "" {
			panic(api)
		}
		methods := apis[api]
		if name == "ContextMenu" {
			for _, part := range apis["menuAPI"] {
				if part.name != "Root" && part.name != "Trigger" {
					methods = append(methods, part)
				}
			}
		}
		rootName := "Root"
		if name == "Toast" {
			rootName = "Provider"
		}
		rootProps := ""
		for _, m := range methods {
			if (name == "Popover" || name == "SystemPopover") && m.name == "Content" {
				continue
			}
			if m.name == rootName {
				rootProps = m.props
			}
		}
		if rootProps == "" {
			continue
		}
		typ := name + "Component"
		fmt.Fprintf(&out, "\n// %s is one %s instance. Configure it before mounting its root.\n// Parts return fluent elements and share only this instance's state.\ntype %s struct { instance componentInstance; props %s }\n", typ, name, typ, rootProps)
		fmt.Fprintf(&out, "\n// New%s declares a %s instance. Optional props provide initial settings.\nfunc New%s(props ...%s) *%s { return &%s{instance:componentInstance{name:%q},props:componentProps(%q,props)} }\n", name, name, name, rootProps, typ, typ, name, "New"+name)
		partNames := map[string]bool{}
		for _, m := range methods {
			partNames[m.name] = true
		}
		for _, f := range fields(rootProps) {
			if f.name == "Children" || f.name == "Style" || f.name == "Ref" || commonPartField(f.name) {
				continue
			}
			setter := f.name
			if partNames[setter] {
				setter = "Set" + setter
			}
			param, assign := f.typ, "value"
			if strings.HasPrefix(f.typ, "func() *") {
				param = "any"
				assign = "componentOptionalAccessor[" + strings.TrimPrefix(f.typ, "func() *") + "](value)"
				if f.typ == "func() *float64" {
					assign = "componentNumberAccessor(value)"
				}
			} else if strings.HasPrefix(f.typ, "func() ") {
				param = "any"
				assign = "componentAccessor[" + strings.TrimPrefix(f.typ, "func() ") + "](value)"
				if f.typ == "func() float64" {
					assign = "componentNumberValueAccessor(value)"
				}
				if f.typ == "func() CheckedState" {
					assign = "componentCheckedAccessor(value)"
				}
			} else if f.typ == "*bool" || f.typ == "*float64" || f.typ == "*int" {
				param = f.typ[1:]
				assign = "&value"
			}
			fmt.Fprintf(&out, "\nfunc (component *%s) %s(value %s) *%s { component.instance.configure(); component.props.%s=%s;return component }\n", typ, setter, param, typ, f.name, assign)
		}
		fmt.Fprintf(&out, "\nfunc (component *%s) %s() *Element { return component.instance.rootElement(%t,func(children Component) *native.Node { props:=component.props;props.Children=children;return (%s{}).%s(props) },component.props.Children) }\n", typ, rootName, transparent[name], api, rootName)
		for _, m := range methods {
			if (name == "Popover" || name == "SystemPopover") && m.name == "Content" {
				continue
			}
			if m.name == rootName || (name == "Tooltip" && m.name == "Provider") {
				continue
			}
			fieldName := identity[name+"."+m.name]
			arg := ""
			assign := ""
			for _, f := range fields(m.props) {
				if f.name != fieldName {
					continue
				}
				t := strings.TrimPrefix(f.typ, "*")
				arg = "value " + t + ", "
				assign = "props." + fieldName + "=value;"
				if strings.HasPrefix(f.typ, "*") {
					assign = "props." + fieldName + "=&value;"
				}
			}
			fmt.Fprintf(&out, "\nfunc (component *%s) %s(%soptions ...%s) *Element { props:=componentProps(%q,options);%s return component.instance.partElement(func(children Component)*native.Node{props.Children=children;return (%s{}).%s(props)},props.Children) }\n", typ, m.name, arg, m.props, name+"."+m.name, assign, m.factory, m.name)
			if arg != "" {
				fmt.Fprintf(&out, "\n// %sWith supplies explicit properties for this part.\nfunc (component *%s) %sWith(props %s) *Element { return component.instance.partElement(func(children Component)*native.Node{props.Children=children;return (%s{}).%s(props)},props.Children) }\n", m.name, typ, m.name, m.props, m.factory, m.name)
			}
		}
	}
	// A tooltip provider groups instances, so its root is independent of any one tooltip.
	fmt.Fprint(&out, `// NewTooltipProvider groups tooltip instances under shared timing settings.
func NewTooltipProvider(props ...TooltipProviderProps) *TooltipProviderComponent { return &TooltipProviderComponent{instance:componentInstance{name:"TooltipProvider"},props:componentProps("NewTooltipProvider",props)} }
type TooltipProviderComponent struct { instance componentInstance; props TooltipProviderProps }
func (provider *TooltipProviderComponent) Delay(value any) *TooltipProviderComponent { provider.instance.configure(); provider.props.Delay=value;return provider }
func (provider *TooltipProviderComponent) CloseDelay(value any) *TooltipProviderComponent { provider.instance.configure(); provider.props.CloseDelay=value;return provider }
func (provider *TooltipProviderComponent) Timeout(value any) *TooltipProviderComponent { provider.instance.configure(); provider.props.Timeout=value;return provider }
func (provider *TooltipProviderComponent) Root() *Element { return provider.instance.rootElement(false,func(children Component)*native.Node { props:=provider.props;props.Children=children;return (tooltipAPI{}).Provider(props) },provider.props.Children) }
`)
	data, err := format.Source(out.Bytes())
	if err != nil {
		os.WriteFile("/tmp/quickgui-components-unformatted.go", out.Bytes(), 0644)
	}
	must(err)
	const path = "component_instances_generated.go"
	if *check {
		old, err := os.ReadFile(path)
		must(err)
		if !bytes.Equal(old, data) {
			panic("run go -C go/ui run ../internal/cmd/componentsgen")
		}
		return
	}
	must(os.WriteFile(path, data, 0644))
	fmt.Printf("generated %d compound component instances\n", len(keys))
}
func commonPartField(name string) bool {
	switch name {
	case "Role", "FocusOnPointer", "Group", "AriaLabel", "TabIndex", "OnClick", "OnDoubleClick", "OnContextMenu", "OnPointer", "OnMouseEnter", "OnMouseLeave", "OnMouseDown", "OnMouseUp", "OnKeyDown", "OnKeyUp", "OnFocus", "OnBlur":
		return true
	}
	return false
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
