// Editorial explanations shared by both language references. Names and types are
// always extracted from declarations; these notes describe their behavior.
export const propertyNotes: Record<string, string> = {
  align_item_with_trigger: "Aligns the selected option with the trigger when the picker opens.",
  align_offset: "Offset along the anchor’s cross axis, in logical pixels.",
  allow_wheel_scrub:
    "Allows wheel input to adjust the number field while its scrub interaction is active.",
  anchor: "Element used as the placement anchor for this surface.",
  anchor_target: "Identity of the element used to position the surface.",
  anchor_point: "Explicit point used to position the surface when no element anchor is used.",
  anchor_gap: "Space between the anchor and its surface, in logical pixels.",
  anchor_placement: "Preferred side and alignment relative to the anchor.",
  aria_modal: "Exposes the modal state of the surface to accessibility.",
  auto_focus: "Requests initial keyboard focus when the element mounts.",
  auto_highlight: "Automatically highlights a matching option when suggestions change.",
  auto_submit: "Submits the one-time code after every required cell has a value.",
  children_checked:
    "Reads the checked states used to derive a parent checkbox’s on, off, or mixed state.",
  close_on_click: "Closes the surface after activation of the item.",
  close_parent_on_esc: "Also dismisses the parent surface when Escape closes this surface.",
  collision_padding:
    "Space reserved between the positioned surface and the available viewport edges.",
  column: "Identifies the table column associated with this part.",
  day: "Calendar date represented by this day cell.",
  default_expanded: "Initially expanded tree nodes for an uncontrolled tree.",
  default_values: "Initial collection of values when no controlled values accessor is supplied.",
  dirty: "Whether the field value has changed from its initial value.",
  disclosure: "Controls the disclosure indicator associated with a tree row.",
  dismiss_on_backdrop: "Allows a backdrop press to dismiss the surface.",
  dismiss_on_pointer_outside: "Allows a pointer press outside the surface to dismiss it.",
  disable_pointer_dismissal: "Prevents outside pointer presses from dismissing the surface.",
  draggable: "Enables the element as a drag source.",
  drop_kinds: "Kinds of drop payload this target accepts.",
  editing: "Controlled editing state of the table cell.",
  element: "Retained native element used by this component part.",
  enter_duration:
    "Duration of the entering transition. Completion is scheduled by the native core.",
  filled: "Whether the associated control contains a value.",
  fit: "How an image or vector fits its available bounds.",
  focus_trap: "Keeps keyboard focus within the active modal surface.",
  format: "Formatting configuration or callback for the displayed value.",
  gap: "Space between adjacent children, in logical pixels.",
  header_height: "Height reserved for the table’s header row, in logical pixels.",
  heading_level: "Accessibility heading level used for accordion headers.",
  highlight_item_on_hover: "Moves the highlighted option when the pointer enters an item.",
  hit_slop: "Expands the pointer hit area without changing the visual bounds.",
  hit_slop_top: "Extra pointer hit area above the visual bounds.",
  hit_slop_right: "Extra pointer hit area to the right of the visual bounds.",
  hit_slop_bottom: "Extra pointer hit area below the visual bounds.",
  hit_slop_left: "Extra pointer hit area to the left of the visual bounds.",
  hour12: "Uses a twelve-hour clock with an AM/PM segment.",
  index: "Zero-based index associated with this repeated part.",
  item_index: "Zero-based index associated with this repeated part.",
  keymap: "Keyboard bindings used by the editor.",
  large_step: "Larger increment used by accelerated keyboard adjustment.",
  small_step: "Smaller increment used by fine keyboard adjustment.",
  limit: "Maximum number of notifications visible at once.",
  loading_label: "Text displayed while a tree node’s children are loading.",
  mask: "Whether the input conceals its entered value.",
  password: "Conceals the entered text while preserving the editor’s value.",
  maximum_value_label: "Accessible label for the maximum end of the range.",
  minimum_value_label: "Accessible label for the minimum end of the range.",
  min_steps_between_values:
    "Minimum separation between neighboring slider thumbs, measured in steps.",
  name: "Name used to identify the control in a form.",
  node_id: "Stable identity of the tree node represented by this part.",
  open_on_hover: "Opens the surface when its trigger is hovered.",
  open_on_input_click: "Opens suggestions when the text input is clicked.",
  overlay: "Places this content in the overlay paint plane.",
  parent: "Marks a checkbox as a parent whose state is derived from its children.",
  passive: "Controls whether the surface is presented without activating its owner.",
  pitch: "Logical pixels of scrub motion required for one step.",
  precision: "Number of fractional digits used for number formatting.",
  render: "Callback that constructs the content for this part.",
  restore_previous_focus: "Restores the previously focused element when the surface closes.",
  scrub_direction: "Axis used to translate scrub motion into value changes.",
  scrub_sensitivity: "Amount of pointer motion required to change the numeric value.",
  segment: "Date or time segment represented by this editable part.",
  segment_order: "Order in which the date segments are displayed.",
  selected: "Exposes the selected state of this item.",
  selected_value: "Value identifying the selected item.",
  active_value: "Value identifying the active item in a coordinated control.",
  set_children: "Callback used to construct and replace the part’s children.",
  side_offset: "Distance from the anchor on the chosen side, in logical pixels.",
  snap_on_step: "Snaps the numeric value to a step boundary during adjustment.",
  sort: "Current table sort configuration.",
  sort_column: "Column used to sort the table.",
  sort_direction: "Ascending or descending direction of the current table sort.",
  sticky: "Keeps the positioned surface attached to its anchor within available bounds.",
  target: "Destination associated with this navigation or link part.",
  test_id: "Stable identifier for native automation and tests.",
  thumb_alignment:
    "Whether the slider thumb stays inside the track or aligns its center to the edge.",
  tooltip_delay: "Delay before the tooltip opens.",
  tooltip_gap: "Space between the tooltip and its trigger.",
  tooltip_placement: "Preferred side and alignment of the tooltip.",
  tooltip_text: "Text displayed by the element’s tooltip.",
  tooltip_viewport_margin: "Minimum space between the tooltip and the window edges.",
  touched: "Whether the user has interacted with the field.",
  track_cursor_axis: "Axis along which the floating surface follows the pointer.",
  type: "Input editing mode for this control.",
  validation_debounce_time: "Delay before deferred validation runs after an edit.",
  validation_type: "Validation strategy applied to the field.",
  viewport_margin: "Minimum space reserved around the surface within the viewport.",
  visible: "Whether the component is presented.",
  activate_on_focus:
    "Selects a tab when keyboard focus moves to it; disable for manual activation.",
  civil_value: "Calendar date or wall-clock time, without an implicit timezone conversion.",
  civil_minimum: "Earliest accepted calendar date or wall-clock time.",
  civil_maximum: "Latest accepted calendar date or wall-clock time.",
  menu: "Model describing menu items, groups, and submenus.",
  menu_count: "Number of top-level menus coordinated by this menubar.",
  padding: "Space between the element’s bounds and its content, in logical pixels.",
  provider: "Shared context coordinating related component instances.",
  slot: "Constructs a named part within this root’s context. Use a Slot variant, then configure the returned element.",
  stack_expanded: "Expands the notification stack so the individual toasts are visible.",
  variant: "Component variant controlling the surface’s semantic behavior.",
};
