// Code generated by bun scripts/generate-style-helpers.ts; DO NOT EDIT.

import type { JSX } from "./index.ts";

/** Fixed Rust style presets, declared as boolean JSX attributes or style fields. */
export interface StyleHelpers {
  /** Matches Rust's absolute. */
  absolute?: boolean | null | undefined;
  /** Matches Rust's app_region_drag. */
  "app-region-drag"?: boolean | null | undefined;
  /** Matches Rust's app_region_no_drag. */
  "app-region-no-drag"?: boolean | null | undefined;
  /** Matches Rust's aspect_square. */
  "aspect-square"?: boolean | null | undefined;
  /** Matches Rust's block. */
  block?: boolean | null | undefined;
  /** Matches Rust's border_dashed. */
  "border-dashed"?: boolean | null | undefined;
  /** Matches Rust's border_dotted. */
  "border-dotted"?: boolean | null | undefined;
  /** Matches Rust's border_solid. */
  "border-solid"?: boolean | null | undefined;
  /** Matches Rust's col_end_auto. */
  "col-end-auto"?: boolean | null | undefined;
  /** Matches Rust's col_span_full. */
  "col-span-full"?: boolean | null | undefined;
  /** Matches Rust's col_start_auto. */
  "col-start-auto"?: boolean | null | undefined;
  /** Matches Rust's content_around. */
  "content-around"?: boolean | null | undefined;
  /** Matches Rust's content_between. */
  "content-between"?: boolean | null | undefined;
  /** Matches Rust's content_center. */
  "content-center"?: boolean | null | undefined;
  /** Matches Rust's content_end. */
  "content-end"?: boolean | null | undefined;
  /** Matches Rust's content_evenly. */
  "content-evenly"?: boolean | null | undefined;
  /** Matches Rust's content_normal. */
  "content-normal"?: boolean | null | undefined;
  /** Matches Rust's content_start. */
  "content-start"?: boolean | null | undefined;
  /** Matches Rust's content_stretch. */
  "content-stretch"?: boolean | null | undefined;
  /** Matches Rust's cursor_alias. */
  "cursor-alias"?: boolean | null | undefined;
  /** Matches Rust's cursor_col_resize. */
  "cursor-col-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_context_menu. */
  "cursor-context-menu"?: boolean | null | undefined;
  /** Matches Rust's cursor_copy. */
  "cursor-copy"?: boolean | null | undefined;
  /** Matches Rust's cursor_crosshair. */
  "cursor-crosshair"?: boolean | null | undefined;
  /** Matches Rust's cursor_default. */
  "cursor-default"?: boolean | null | undefined;
  /** Matches Rust's cursor_e_resize. */
  "cursor-e-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_ew_resize. */
  "cursor-ew-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_grab. */
  "cursor-grab"?: boolean | null | undefined;
  /** Matches Rust's cursor_grabbing. */
  "cursor-grabbing"?: boolean | null | undefined;
  /** Matches Rust's cursor_move. */
  "cursor-move"?: boolean | null | undefined;
  /** Matches Rust's cursor_n_resize. */
  "cursor-n-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_nesw_resize. */
  "cursor-nesw-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_no_drop. */
  "cursor-no-drop"?: boolean | null | undefined;
  /** Matches Rust's cursor_not_allowed. */
  "cursor-not-allowed"?: boolean | null | undefined;
  /** Matches Rust's cursor_ns_resize. */
  "cursor-ns-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_nwse_resize. */
  "cursor-nwse-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_pointer. */
  "cursor-pointer"?: boolean | null | undefined;
  /** Matches Rust's cursor_row_resize. */
  "cursor-row-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_s_resize. */
  "cursor-s-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_text. */
  "cursor-text"?: boolean | null | undefined;
  /** Matches Rust's cursor_vertical_text. */
  "cursor-vertical-text"?: boolean | null | undefined;
  /** Matches Rust's cursor_w_resize. */
  "cursor-w-resize"?: boolean | null | undefined;
  /** Matches Rust's flex. */
  flex?: boolean | null | undefined;
  /** Matches Rust's flex_1. */
  "flex-1"?: boolean | null | undefined;
  /** Matches Rust's flex_auto. */
  "flex-auto"?: boolean | null | undefined;
  /** Matches Rust's flex_basis_auto. */
  "flex-basis-auto"?: boolean | null | undefined;
  /** Matches Rust's flex_col. */
  "flex-col"?: boolean | null | undefined;
  /** Matches Rust's flex_col_reverse. */
  "flex-col-reverse"?: boolean | null | undefined;
  /** Matches Rust's flex_grow_0. */
  "flex-grow-0"?: boolean | null | undefined;
  /** Matches Rust's flex_grow_1. */
  "flex-grow-1"?: boolean | null | undefined;
  /** Matches Rust's flex_initial. */
  "flex-initial"?: boolean | null | undefined;
  /** Matches Rust's flex_none. */
  "flex-none"?: boolean | null | undefined;
  /** Matches Rust's flex_nowrap. */
  "flex-nowrap"?: boolean | null | undefined;
  /** Matches Rust's flex_row. */
  "flex-row"?: boolean | null | undefined;
  /** Matches Rust's flex_row_reverse. */
  "flex-row-reverse"?: boolean | null | undefined;
  /** Matches Rust's flex_shrink_0. */
  "flex-shrink-0"?: boolean | null | undefined;
  /** Matches Rust's flex_shrink_1. */
  "flex-shrink-1"?: boolean | null | undefined;
  /** Matches Rust's flex_wrap. */
  "flex-wrap"?: boolean | null | undefined;
  /** Matches Rust's flex_wrap_reverse. */
  "flex-wrap-reverse"?: boolean | null | undefined;
  /** Matches Rust's font_bold. */
  "font-bold"?: boolean | null | undefined;
  /** Matches Rust's font_medium. */
  "font-medium"?: boolean | null | undefined;
  /** Matches Rust's font_normal. */
  "font-normal"?: boolean | null | undefined;
  /** Matches Rust's font_semibold. */
  "font-semibold"?: boolean | null | undefined;
  /** Matches Rust's gap_1. */
  "gap-1"?: boolean | null | undefined;
  /** Matches Rust's gap_2. */
  "gap-2"?: boolean | null | undefined;
  /** Matches Rust's gap_3. */
  "gap-3"?: boolean | null | undefined;
  /** Matches Rust's gap_4. */
  "gap-4"?: boolean | null | undefined;
  /** Matches Rust's gap_5. */
  "gap-5"?: boolean | null | undefined;
  /** Matches Rust's gap_6. */
  "gap-6"?: boolean | null | undefined;
  /** Matches Rust's gap_x_0. */
  "gap-x-0"?: boolean | null | undefined;
  /** Matches Rust's gap_x_1. */
  "gap-x-1"?: boolean | null | undefined;
  /** Matches Rust's gap_x_2. */
  "gap-x-2"?: boolean | null | undefined;
  /** Matches Rust's gap_x_3. */
  "gap-x-3"?: boolean | null | undefined;
  /** Matches Rust's gap_x_4. */
  "gap-x-4"?: boolean | null | undefined;
  /** Matches Rust's gap_x_5. */
  "gap-x-5"?: boolean | null | undefined;
  /** Matches Rust's gap_x_6. */
  "gap-x-6"?: boolean | null | undefined;
  /** Matches Rust's gap_y_0. */
  "gap-y-0"?: boolean | null | undefined;
  /** Matches Rust's gap_y_1. */
  "gap-y-1"?: boolean | null | undefined;
  /** Matches Rust's gap_y_2. */
  "gap-y-2"?: boolean | null | undefined;
  /** Matches Rust's gap_y_3. */
  "gap-y-3"?: boolean | null | undefined;
  /** Matches Rust's gap_y_4. */
  "gap-y-4"?: boolean | null | undefined;
  /** Matches Rust's gap_y_5. */
  "gap-y-5"?: boolean | null | undefined;
  /** Matches Rust's gap_y_6. */
  "gap-y-6"?: boolean | null | undefined;
  /** Matches Rust's grid. */
  grid?: boolean | null | undefined;
  /** Matches Rust's grid_flow_col. */
  "grid-flow-col"?: boolean | null | undefined;
  /** Matches Rust's grid_flow_col_dense. */
  "grid-flow-col-dense"?: boolean | null | undefined;
  /** Matches Rust's grid_flow_row. */
  "grid-flow-row"?: boolean | null | undefined;
  /** Matches Rust's grid_flow_row_dense. */
  "grid-flow-row-dense"?: boolean | null | undefined;
  /** Matches Rust's h_10. */
  "h-10"?: boolean | null | undefined;
  /** Matches Rust's h_12. */
  "h-12"?: boolean | null | undefined;
  /** Matches Rust's h_8. */
  "h-8"?: boolean | null | undefined;
  /** Matches Rust's h_full. */
  "h-full"?: boolean | null | undefined;
  /** Matches Rust's hidden. */
  hidden?: boolean | null | undefined;
  /** Matches Rust's inset_0. */
  "inset-0"?: boolean | null | undefined;
  /** Matches Rust's invisible. */
  invisible?: boolean | null | undefined;
  /** Matches Rust's items_baseline. */
  "items-baseline"?: boolean | null | undefined;
  /** Matches Rust's items_center. */
  "items-center"?: boolean | null | undefined;
  /** Matches Rust's items_end. */
  "items-end"?: boolean | null | undefined;
  /** Matches Rust's items_start. */
  "items-start"?: boolean | null | undefined;
  /** Matches Rust's items_stretch. */
  "items-stretch"?: boolean | null | undefined;
  /** Matches Rust's justify_around. */
  "justify-around"?: boolean | null | undefined;
  /** Matches Rust's justify_between. */
  "justify-between"?: boolean | null | undefined;
  /** Matches Rust's justify_center. */
  "justify-center"?: boolean | null | undefined;
  /** Matches Rust's justify_end. */
  "justify-end"?: boolean | null | undefined;
  /** Matches Rust's justify_evenly. */
  "justify-evenly"?: boolean | null | undefined;
  /** Matches Rust's justify_start. */
  "justify-start"?: boolean | null | undefined;
  /** Matches Rust's ltr. */
  ltr?: boolean | null | undefined;
  /** Matches Rust's m_0. */
  "m-0"?: boolean | null | undefined;
  /** Matches Rust's m_1. */
  "m-1"?: boolean | null | undefined;
  /** Matches Rust's m_10. */
  "m-10"?: boolean | null | undefined;
  /** Matches Rust's m_12. */
  "m-12"?: boolean | null | undefined;
  /** Matches Rust's m_16. */
  "m-16"?: boolean | null | undefined;
  /** Matches Rust's m_2. */
  "m-2"?: boolean | null | undefined;
  /** Matches Rust's m_20. */
  "m-20"?: boolean | null | undefined;
  /** Matches Rust's m_24. */
  "m-24"?: boolean | null | undefined;
  /** Matches Rust's m_3. */
  "m-3"?: boolean | null | undefined;
  /** Matches Rust's m_32. */
  "m-32"?: boolean | null | undefined;
  /** Matches Rust's m_4. */
  "m-4"?: boolean | null | undefined;
  /** Matches Rust's m_5. */
  "m-5"?: boolean | null | undefined;
  /** Matches Rust's m_6. */
  "m-6"?: boolean | null | undefined;
  /** Matches Rust's m_8. */
  "m-8"?: boolean | null | undefined;
  /** Matches Rust's m_auto. */
  "m-auto"?: boolean | null | undefined;
  /** Matches Rust's mb_0. */
  "mb-0"?: boolean | null | undefined;
  /** Matches Rust's mb_1. */
  "mb-1"?: boolean | null | undefined;
  /** Matches Rust's mb_10. */
  "mb-10"?: boolean | null | undefined;
  /** Matches Rust's mb_12. */
  "mb-12"?: boolean | null | undefined;
  /** Matches Rust's mb_16. */
  "mb-16"?: boolean | null | undefined;
  /** Matches Rust's mb_2. */
  "mb-2"?: boolean | null | undefined;
  /** Matches Rust's mb_20. */
  "mb-20"?: boolean | null | undefined;
  /** Matches Rust's mb_24. */
  "mb-24"?: boolean | null | undefined;
  /** Matches Rust's mb_3. */
  "mb-3"?: boolean | null | undefined;
  /** Matches Rust's mb_32. */
  "mb-32"?: boolean | null | undefined;
  /** Matches Rust's mb_4. */
  "mb-4"?: boolean | null | undefined;
  /** Matches Rust's mb_5. */
  "mb-5"?: boolean | null | undefined;
  /** Matches Rust's mb_6. */
  "mb-6"?: boolean | null | undefined;
  /** Matches Rust's mb_8. */
  "mb-8"?: boolean | null | undefined;
  /** Matches Rust's mb_auto. */
  "mb-auto"?: boolean | null | undefined;
  /** Matches Rust's ml_0. */
  "ml-0"?: boolean | null | undefined;
  /** Matches Rust's ml_1. */
  "ml-1"?: boolean | null | undefined;
  /** Matches Rust's ml_10. */
  "ml-10"?: boolean | null | undefined;
  /** Matches Rust's ml_12. */
  "ml-12"?: boolean | null | undefined;
  /** Matches Rust's ml_16. */
  "ml-16"?: boolean | null | undefined;
  /** Matches Rust's ml_2. */
  "ml-2"?: boolean | null | undefined;
  /** Matches Rust's ml_20. */
  "ml-20"?: boolean | null | undefined;
  /** Matches Rust's ml_24. */
  "ml-24"?: boolean | null | undefined;
  /** Matches Rust's ml_3. */
  "ml-3"?: boolean | null | undefined;
  /** Matches Rust's ml_32. */
  "ml-32"?: boolean | null | undefined;
  /** Matches Rust's ml_4. */
  "ml-4"?: boolean | null | undefined;
  /** Matches Rust's ml_5. */
  "ml-5"?: boolean | null | undefined;
  /** Matches Rust's ml_6. */
  "ml-6"?: boolean | null | undefined;
  /** Matches Rust's ml_8. */
  "ml-8"?: boolean | null | undefined;
  /** Matches Rust's ml_auto. */
  "ml-auto"?: boolean | null | undefined;
  /** Matches Rust's mr_0. */
  "mr-0"?: boolean | null | undefined;
  /** Matches Rust's mr_1. */
  "mr-1"?: boolean | null | undefined;
  /** Matches Rust's mr_10. */
  "mr-10"?: boolean | null | undefined;
  /** Matches Rust's mr_12. */
  "mr-12"?: boolean | null | undefined;
  /** Matches Rust's mr_16. */
  "mr-16"?: boolean | null | undefined;
  /** Matches Rust's mr_2. */
  "mr-2"?: boolean | null | undefined;
  /** Matches Rust's mr_20. */
  "mr-20"?: boolean | null | undefined;
  /** Matches Rust's mr_24. */
  "mr-24"?: boolean | null | undefined;
  /** Matches Rust's mr_3. */
  "mr-3"?: boolean | null | undefined;
  /** Matches Rust's mr_32. */
  "mr-32"?: boolean | null | undefined;
  /** Matches Rust's mr_4. */
  "mr-4"?: boolean | null | undefined;
  /** Matches Rust's mr_5. */
  "mr-5"?: boolean | null | undefined;
  /** Matches Rust's mr_6. */
  "mr-6"?: boolean | null | undefined;
  /** Matches Rust's mr_8. */
  "mr-8"?: boolean | null | undefined;
  /** Matches Rust's mr_auto. */
  "mr-auto"?: boolean | null | undefined;
  /** Matches Rust's mt_0. */
  "mt-0"?: boolean | null | undefined;
  /** Matches Rust's mt_1. */
  "mt-1"?: boolean | null | undefined;
  /** Matches Rust's mt_10. */
  "mt-10"?: boolean | null | undefined;
  /** Matches Rust's mt_12. */
  "mt-12"?: boolean | null | undefined;
  /** Matches Rust's mt_16. */
  "mt-16"?: boolean | null | undefined;
  /** Matches Rust's mt_2. */
  "mt-2"?: boolean | null | undefined;
  /** Matches Rust's mt_20. */
  "mt-20"?: boolean | null | undefined;
  /** Matches Rust's mt_24. */
  "mt-24"?: boolean | null | undefined;
  /** Matches Rust's mt_3. */
  "mt-3"?: boolean | null | undefined;
  /** Matches Rust's mt_32. */
  "mt-32"?: boolean | null | undefined;
  /** Matches Rust's mt_4. */
  "mt-4"?: boolean | null | undefined;
  /** Matches Rust's mt_5. */
  "mt-5"?: boolean | null | undefined;
  /** Matches Rust's mt_6. */
  "mt-6"?: boolean | null | undefined;
  /** Matches Rust's mt_8. */
  "mt-8"?: boolean | null | undefined;
  /** Matches Rust's mt_auto. */
  "mt-auto"?: boolean | null | undefined;
  /** Matches Rust's mx_0. */
  "mx-0"?: boolean | null | undefined;
  /** Matches Rust's mx_1. */
  "mx-1"?: boolean | null | undefined;
  /** Matches Rust's mx_10. */
  "mx-10"?: boolean | null | undefined;
  /** Matches Rust's mx_12. */
  "mx-12"?: boolean | null | undefined;
  /** Matches Rust's mx_16. */
  "mx-16"?: boolean | null | undefined;
  /** Matches Rust's mx_2. */
  "mx-2"?: boolean | null | undefined;
  /** Matches Rust's mx_20. */
  "mx-20"?: boolean | null | undefined;
  /** Matches Rust's mx_24. */
  "mx-24"?: boolean | null | undefined;
  /** Matches Rust's mx_3. */
  "mx-3"?: boolean | null | undefined;
  /** Matches Rust's mx_32. */
  "mx-32"?: boolean | null | undefined;
  /** Matches Rust's mx_4. */
  "mx-4"?: boolean | null | undefined;
  /** Matches Rust's mx_5. */
  "mx-5"?: boolean | null | undefined;
  /** Matches Rust's mx_6. */
  "mx-6"?: boolean | null | undefined;
  /** Matches Rust's mx_8. */
  "mx-8"?: boolean | null | undefined;
  /** Matches Rust's mx_auto. */
  "mx-auto"?: boolean | null | undefined;
  /** Matches Rust's my_0. */
  "my-0"?: boolean | null | undefined;
  /** Matches Rust's my_1. */
  "my-1"?: boolean | null | undefined;
  /** Matches Rust's my_10. */
  "my-10"?: boolean | null | undefined;
  /** Matches Rust's my_12. */
  "my-12"?: boolean | null | undefined;
  /** Matches Rust's my_16. */
  "my-16"?: boolean | null | undefined;
  /** Matches Rust's my_2. */
  "my-2"?: boolean | null | undefined;
  /** Matches Rust's my_20. */
  "my-20"?: boolean | null | undefined;
  /** Matches Rust's my_24. */
  "my-24"?: boolean | null | undefined;
  /** Matches Rust's my_3. */
  "my-3"?: boolean | null | undefined;
  /** Matches Rust's my_32. */
  "my-32"?: boolean | null | undefined;
  /** Matches Rust's my_4. */
  "my-4"?: boolean | null | undefined;
  /** Matches Rust's my_5. */
  "my-5"?: boolean | null | undefined;
  /** Matches Rust's my_6. */
  "my-6"?: boolean | null | undefined;
  /** Matches Rust's my_8. */
  "my-8"?: boolean | null | undefined;
  /** Matches Rust's my_auto. */
  "my-auto"?: boolean | null | undefined;
  /** Matches Rust's overflow_hidden. */
  "overflow-hidden"?: boolean | null | undefined;
  /** Matches Rust's overflow_scroll. */
  "overflow-scroll"?: boolean | null | undefined;
  /** Matches Rust's overflow_x_scroll. */
  "overflow-x-scroll"?: boolean | null | undefined;
  /** Matches Rust's overflow_y_scroll. */
  "overflow-y-scroll"?: boolean | null | undefined;
  /** Matches Rust's p_1. */
  "p-1"?: boolean | null | undefined;
  /** Matches Rust's p_2. */
  "p-2"?: boolean | null | undefined;
  /** Matches Rust's p_3. */
  "p-3"?: boolean | null | undefined;
  /** Matches Rust's p_4. */
  "p-4"?: boolean | null | undefined;
  /** Matches Rust's p_5. */
  "p-5"?: boolean | null | undefined;
  /** Matches Rust's p_6. */
  "p-6"?: boolean | null | undefined;
  /** Matches Rust's px_2. */
  "px-2"?: boolean | null | undefined;
  /** Matches Rust's px_3. */
  "px-3"?: boolean | null | undefined;
  /** Matches Rust's px_4. */
  "px-4"?: boolean | null | undefined;
  /** Matches Rust's py_1. */
  "py-1"?: boolean | null | undefined;
  /** Matches Rust's py_2. */
  "py-2"?: boolean | null | undefined;
  /** Matches Rust's relative. */
  relative?: boolean | null | undefined;
  /** Matches Rust's rounded_2xl. */
  "rounded-2xl"?: boolean | null | undefined;
  /** Matches Rust's rounded_full. */
  "rounded-full"?: boolean | null | undefined;
  /** Matches Rust's rounded_lg. */
  "rounded-lg"?: boolean | null | undefined;
  /** Matches Rust's rounded_md. */
  "rounded-md"?: boolean | null | undefined;
  /** Matches Rust's rounded_sm. */
  "rounded-sm"?: boolean | null | undefined;
  /** Matches Rust's rounded_xl. */
  "rounded-xl"?: boolean | null | undefined;
  /** Matches Rust's row_end_auto. */
  "row-end-auto"?: boolean | null | undefined;
  /** Matches Rust's row_span_full. */
  "row-span-full"?: boolean | null | undefined;
  /** Matches Rust's row_start_auto. */
  "row-start-auto"?: boolean | null | undefined;
  /** Matches Rust's rtl. */
  rtl?: boolean | null | undefined;
  /** Matches Rust's selectable. */
  selectable?: boolean | null | undefined;
  /** Matches Rust's self_baseline. */
  "self-baseline"?: boolean | null | undefined;
  /** Matches Rust's self_center. */
  "self-center"?: boolean | null | undefined;
  /** Matches Rust's self_end. */
  "self-end"?: boolean | null | undefined;
  /** Matches Rust's self_flex_end. */
  "self-flex-end"?: boolean | null | undefined;
  /** Matches Rust's self_flex_start. */
  "self-flex-start"?: boolean | null | undefined;
  /** Matches Rust's self_start. */
  "self-start"?: boolean | null | undefined;
  /** Matches Rust's self_stretch. */
  "self-stretch"?: boolean | null | undefined;
  /** Matches Rust's size_full. */
  "size-full"?: boolean | null | undefined;
  /** Matches Rust's snap_stop_always. */
  "snap-stop-always"?: boolean | null | undefined;
  /** Matches Rust's sticky. */
  "position-sticky"?: boolean | null | undefined;
  /** Matches Rust's text_2xl. */
  "text-2xl"?: boolean | null | undefined;
  /** Matches Rust's text_3xl. */
  "text-3xl"?: boolean | null | undefined;
  /** Matches Rust's text_base. */
  "text-base"?: boolean | null | undefined;
  /** Matches Rust's text_center. */
  "text-center"?: boolean | null | undefined;
  /** Matches Rust's text_ellipsis. */
  "text-ellipsis"?: boolean | null | undefined;
  /** Matches Rust's text_ellipsis_middle. */
  "text-ellipsis-middle"?: boolean | null | undefined;
  /** Matches Rust's text_ellipsis_start. */
  "text-ellipsis-start"?: boolean | null | undefined;
  /** Matches Rust's text_end. */
  "text-end"?: boolean | null | undefined;
  /** Matches Rust's text_justify. */
  "text-justify"?: boolean | null | undefined;
  /** Matches Rust's text_left. */
  "text-left"?: boolean | null | undefined;
  /** Matches Rust's text_lg. */
  "text-lg"?: boolean | null | undefined;
  /** Matches Rust's text_right. */
  "text-right"?: boolean | null | undefined;
  /** Matches Rust's text_sm. */
  "text-sm"?: boolean | null | undefined;
  /** Matches Rust's text_start. */
  "text-start"?: boolean | null | undefined;
  /** Matches Rust's text_xl. */
  "text-xl"?: boolean | null | undefined;
  /** Matches Rust's text_xs. */
  "text-xs"?: boolean | null | undefined;
  /** Matches Rust's truncate. */
  truncate?: boolean | null | undefined;
  /** Matches Rust's user_select_none. */
  "user-select-none"?: boolean | null | undefined;
  /** Matches Rust's user_select_text. */
  "user-select-text"?: boolean | null | undefined;
  /** Matches Rust's visible. */
  visible?: boolean | null | undefined;
  /** Matches Rust's w_full. */
  "w-full"?: boolean | null | undefined;
  /** Matches Rust's whitespace_normal. */
  "whitespace-normal"?: boolean | null | undefined;
  /** Matches Rust's whitespace_nowrap. */
  "whitespace-nowrap"?: boolean | null | undefined;
}

export type HelperDeclaration = Record<string, unknown>;
export interface StyleHelperDefinition {
  fields: readonly string[];
  resolve: () => HelperDeclaration;
}

export const styleHelpers: Record<string, StyleHelperDefinition> = {
  absolute: { fields: ["position"], resolve: () => ({ position: "absolute" }) },
  "app-region-drag": { fields: ["appRegion"], resolve: () => ({ appRegion: "drag" }) },
  "app-region-no-drag": { fields: ["appRegion"], resolve: () => ({ appRegion: "no-drag" }) },
  "aspect-square": { fields: ["aspectRatio"], resolve: () => ({ aspectRatio: 1 }) },
  block: { fields: ["display"], resolve: () => ({ display: "block" }) },
  "border-dashed": { fields: ["borderStyle"], resolve: () => ({ borderStyle: "dashed" }) },
  "border-dotted": { fields: ["borderStyle"], resolve: () => ({ borderStyle: "dotted" }) },
  "border-solid": { fields: ["borderStyle"], resolve: () => ({ borderStyle: "solid" }) },
  "col-end-auto": { fields: ["gridColumnEnd"], resolve: () => ({ gridColumnEnd: 0 }) },
  "col-span-full": {
    fields: ["gridColumnSpan", "gridColumnStart", "gridColumnEnd"],
    resolve: () => ({ gridColumnSpan: null, gridColumnStart: 1, gridColumnEnd: -1 }),
  },
  "col-start-auto": { fields: ["gridColumnStart"], resolve: () => ({ gridColumnStart: 0 }) },
  "content-around": { fields: ["alignContent"], resolve: () => ({ alignContent: "space-around" }) },
  "content-between": {
    fields: ["alignContent"],
    resolve: () => ({ alignContent: "space-between" }),
  },
  "content-center": { fields: ["alignContent"], resolve: () => ({ alignContent: "center" }) },
  "content-end": { fields: ["alignContent"], resolve: () => ({ alignContent: "flex-end" }) },
  "content-evenly": { fields: ["alignContent"], resolve: () => ({ alignContent: "space-evenly" }) },
  "content-normal": { fields: ["alignContent"], resolve: () => ({ alignContent: "normal" }) },
  "content-start": { fields: ["alignContent"], resolve: () => ({ alignContent: "flex-start" }) },
  "content-stretch": { fields: ["alignContent"], resolve: () => ({ alignContent: "stretch" }) },
  "cursor-alias": { fields: ["cursor"], resolve: () => ({ cursor: "alias" }) },
  "cursor-col-resize": { fields: ["cursor"], resolve: () => ({ cursor: "col-resize" }) },
  "cursor-context-menu": { fields: ["cursor"], resolve: () => ({ cursor: "context-menu" }) },
  "cursor-copy": { fields: ["cursor"], resolve: () => ({ cursor: "copy" }) },
  "cursor-crosshair": { fields: ["cursor"], resolve: () => ({ cursor: "crosshair" }) },
  "cursor-default": { fields: ["cursor"], resolve: () => ({ cursor: "default" }) },
  "cursor-e-resize": { fields: ["cursor"], resolve: () => ({ cursor: "e-resize" }) },
  "cursor-ew-resize": { fields: ["cursor"], resolve: () => ({ cursor: "ew-resize" }) },
  "cursor-grab": { fields: ["cursor"], resolve: () => ({ cursor: "grab" }) },
  "cursor-grabbing": { fields: ["cursor"], resolve: () => ({ cursor: "grabbing" }) },
  "cursor-move": { fields: ["cursor"], resolve: () => ({ cursor: "grabbing" }) },
  "cursor-n-resize": { fields: ["cursor"], resolve: () => ({ cursor: "n-resize" }) },
  "cursor-nesw-resize": { fields: ["cursor"], resolve: () => ({ cursor: "nesw-resize" }) },
  "cursor-no-drop": { fields: ["cursor"], resolve: () => ({ cursor: "not-allowed" }) },
  "cursor-not-allowed": { fields: ["cursor"], resolve: () => ({ cursor: "not-allowed" }) },
  "cursor-ns-resize": { fields: ["cursor"], resolve: () => ({ cursor: "ns-resize" }) },
  "cursor-nwse-resize": { fields: ["cursor"], resolve: () => ({ cursor: "nwse-resize" }) },
  "cursor-pointer": { fields: ["cursor"], resolve: () => ({ cursor: "pointer" }) },
  "cursor-row-resize": { fields: ["cursor"], resolve: () => ({ cursor: "row-resize" }) },
  "cursor-s-resize": { fields: ["cursor"], resolve: () => ({ cursor: "s-resize" }) },
  "cursor-text": { fields: ["cursor"], resolve: () => ({ cursor: "text" }) },
  "cursor-vertical-text": { fields: ["cursor"], resolve: () => ({ cursor: "vertical-text" }) },
  "cursor-w-resize": { fields: ["cursor"], resolve: () => ({ cursor: "w-resize" }) },
  flex: { fields: ["display"], resolve: () => ({ display: "flex" }) },
  "flex-1": {
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: () => ({ flexGrow: 1, flexShrink: 1, flexBasis: 0 }),
  },
  "flex-auto": {
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: () => ({ flexGrow: 1, flexShrink: 1, flexBasis: "auto" }),
  },
  "flex-basis-auto": { fields: ["flexBasis"], resolve: () => ({ flexBasis: "auto" }) },
  "flex-col": {
    fields: ["display", "flexDirection"],
    resolve: () => ({ display: "flex", flexDirection: "column" }),
  },
  "flex-col-reverse": {
    fields: ["display", "flexDirection"],
    resolve: () => ({ display: "flex", flexDirection: "column-reverse" }),
  },
  "flex-grow-0": { fields: ["flexGrow"], resolve: () => ({ flexGrow: 0 }) },
  "flex-grow-1": { fields: ["flexGrow"], resolve: () => ({ flexGrow: 1 }) },
  "flex-initial": {
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: () => ({ flexGrow: 0, flexShrink: 1, flexBasis: "auto" }),
  },
  "flex-none": {
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: () => ({ flexGrow: 0, flexShrink: 0, flexBasis: "auto" }),
  },
  "flex-nowrap": { fields: ["flexWrap"], resolve: () => ({ flexWrap: "nowrap" }) },
  "flex-row": {
    fields: ["display", "flexDirection"],
    resolve: () => ({ display: "flex", flexDirection: "row" }),
  },
  "flex-row-reverse": {
    fields: ["display", "flexDirection"],
    resolve: () => ({ display: "flex", flexDirection: "row-reverse" }),
  },
  "flex-shrink-0": { fields: ["flexShrink"], resolve: () => ({ flexShrink: 0 }) },
  "flex-shrink-1": { fields: ["flexShrink"], resolve: () => ({ flexShrink: 1 }) },
  "flex-wrap": { fields: ["flexWrap"], resolve: () => ({ flexWrap: "wrap" }) },
  "flex-wrap-reverse": { fields: ["flexWrap"], resolve: () => ({ flexWrap: "wrap-reverse" }) },
  "font-bold": { fields: ["fontWeight"], resolve: () => ({ fontWeight: 700 }) },
  "font-medium": { fields: ["fontWeight"], resolve: () => ({ fontWeight: 500 }) },
  "font-normal": { fields: ["fontWeight"], resolve: () => ({ fontWeight: 400 }) },
  "font-semibold": { fields: ["fontWeight"], resolve: () => ({ fontWeight: 600 }) },
  "gap-1": { fields: ["gap"], resolve: () => ({ gap: 4 }) },
  "gap-2": { fields: ["gap"], resolve: () => ({ gap: 8 }) },
  "gap-3": { fields: ["gap"], resolve: () => ({ gap: 12 }) },
  "gap-4": { fields: ["gap"], resolve: () => ({ gap: 16 }) },
  "gap-5": { fields: ["gap"], resolve: () => ({ gap: 20 }) },
  "gap-6": { fields: ["gap"], resolve: () => ({ gap: 24 }) },
  "gap-x-0": { fields: ["columnGap"], resolve: () => ({ columnGap: 0 }) },
  "gap-x-1": { fields: ["columnGap"], resolve: () => ({ columnGap: 4 }) },
  "gap-x-2": { fields: ["columnGap"], resolve: () => ({ columnGap: 8 }) },
  "gap-x-3": { fields: ["columnGap"], resolve: () => ({ columnGap: 12 }) },
  "gap-x-4": { fields: ["columnGap"], resolve: () => ({ columnGap: 16 }) },
  "gap-x-5": { fields: ["columnGap"], resolve: () => ({ columnGap: 20 }) },
  "gap-x-6": { fields: ["columnGap"], resolve: () => ({ columnGap: 24 }) },
  "gap-y-0": { fields: ["rowGap"], resolve: () => ({ rowGap: 0 }) },
  "gap-y-1": { fields: ["rowGap"], resolve: () => ({ rowGap: 4 }) },
  "gap-y-2": { fields: ["rowGap"], resolve: () => ({ rowGap: 8 }) },
  "gap-y-3": { fields: ["rowGap"], resolve: () => ({ rowGap: 12 }) },
  "gap-y-4": { fields: ["rowGap"], resolve: () => ({ rowGap: 16 }) },
  "gap-y-5": { fields: ["rowGap"], resolve: () => ({ rowGap: 20 }) },
  "gap-y-6": { fields: ["rowGap"], resolve: () => ({ rowGap: 24 }) },
  grid: { fields: ["display"], resolve: () => ({ display: "grid" }) },
  "grid-flow-col": { fields: ["gridAutoFlow"], resolve: () => ({ gridAutoFlow: "column" }) },
  "grid-flow-col-dense": {
    fields: ["gridAutoFlow"],
    resolve: () => ({ gridAutoFlow: "column dense" }),
  },
  "grid-flow-row": { fields: ["gridAutoFlow"], resolve: () => ({ gridAutoFlow: "row" }) },
  "grid-flow-row-dense": {
    fields: ["gridAutoFlow"],
    resolve: () => ({ gridAutoFlow: "row dense" }),
  },
  "h-10": { fields: ["height"], resolve: () => ({ height: 40 }) },
  "h-12": { fields: ["height"], resolve: () => ({ height: 48 }) },
  "h-8": { fields: ["height"], resolve: () => ({ height: 32 }) },
  "h-full": { fields: ["height"], resolve: () => ({ height: "100%" }) },
  hidden: { fields: ["display"], resolve: () => ({ display: "none" }) },
  "inset-0": {
    fields: ["top", "right", "bottom", "left"],
    resolve: () => ({ top: 0, right: 0, bottom: 0, left: 0 }),
  },
  invisible: { fields: ["visibility"], resolve: () => ({ visibility: "hidden" }) },
  "items-baseline": { fields: ["alignItems"], resolve: () => ({ alignItems: "baseline" }) },
  "items-center": { fields: ["alignItems"], resolve: () => ({ alignItems: "center" }) },
  "items-end": { fields: ["alignItems"], resolve: () => ({ alignItems: "flex-end" }) },
  "items-start": { fields: ["alignItems"], resolve: () => ({ alignItems: "flex-start" }) },
  "items-stretch": { fields: ["alignItems"], resolve: () => ({ alignItems: "stretch" }) },
  "justify-around": {
    fields: ["justifyContent"],
    resolve: () => ({ justifyContent: "space-around" }),
  },
  "justify-between": {
    fields: ["justifyContent"],
    resolve: () => ({ justifyContent: "space-between" }),
  },
  "justify-center": { fields: ["justifyContent"], resolve: () => ({ justifyContent: "center" }) },
  "justify-end": { fields: ["justifyContent"], resolve: () => ({ justifyContent: "end" }) },
  "justify-evenly": {
    fields: ["justifyContent"],
    resolve: () => ({ justifyContent: "space-evenly" }),
  },
  "justify-start": { fields: ["justifyContent"], resolve: () => ({ justifyContent: "start" }) },
  ltr: { fields: ["direction"], resolve: () => ({ direction: "ltr" }) },
  "m-0": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 0, marginRight: 0, marginBottom: 0, marginLeft: 0 }),
  },
  "m-1": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 4, marginRight: 4, marginBottom: 4, marginLeft: 4 }),
  },
  "m-10": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 40, marginRight: 40, marginBottom: 40, marginLeft: 40 }),
  },
  "m-12": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 48, marginRight: 48, marginBottom: 48, marginLeft: 48 }),
  },
  "m-16": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 64, marginRight: 64, marginBottom: 64, marginLeft: 64 }),
  },
  "m-2": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 8, marginRight: 8, marginBottom: 8, marginLeft: 8 }),
  },
  "m-20": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 80, marginRight: 80, marginBottom: 80, marginLeft: 80 }),
  },
  "m-24": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 96, marginRight: 96, marginBottom: 96, marginLeft: 96 }),
  },
  "m-3": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 12, marginRight: 12, marginBottom: 12, marginLeft: 12 }),
  },
  "m-32": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 128, marginRight: 128, marginBottom: 128, marginLeft: 128 }),
  },
  "m-4": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 16, marginRight: 16, marginBottom: 16, marginLeft: 16 }),
  },
  "m-5": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 20, marginRight: 20, marginBottom: 20, marginLeft: 20 }),
  },
  "m-6": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 24, marginRight: 24, marginBottom: 24, marginLeft: 24 }),
  },
  "m-8": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 32, marginRight: 32, marginBottom: 32, marginLeft: 32 }),
  },
  "m-auto": {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({
      marginTop: "auto",
      marginRight: "auto",
      marginBottom: "auto",
      marginLeft: "auto",
    }),
  },
  "mb-0": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 0 }) },
  "mb-1": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 4 }) },
  "mb-10": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 40 }) },
  "mb-12": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 48 }) },
  "mb-16": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 64 }) },
  "mb-2": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 8 }) },
  "mb-20": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 80 }) },
  "mb-24": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 96 }) },
  "mb-3": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 12 }) },
  "mb-32": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 128 }) },
  "mb-4": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 16 }) },
  "mb-5": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 20 }) },
  "mb-6": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 24 }) },
  "mb-8": { fields: ["marginBottom"], resolve: () => ({ marginBottom: 32 }) },
  "mb-auto": { fields: ["marginBottom"], resolve: () => ({ marginBottom: "auto" }) },
  "ml-0": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 0 }) },
  "ml-1": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 4 }) },
  "ml-10": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 40 }) },
  "ml-12": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 48 }) },
  "ml-16": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 64 }) },
  "ml-2": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 8 }) },
  "ml-20": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 80 }) },
  "ml-24": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 96 }) },
  "ml-3": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 12 }) },
  "ml-32": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 128 }) },
  "ml-4": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 16 }) },
  "ml-5": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 20 }) },
  "ml-6": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 24 }) },
  "ml-8": { fields: ["marginLeft"], resolve: () => ({ marginLeft: 32 }) },
  "ml-auto": { fields: ["marginLeft"], resolve: () => ({ marginLeft: "auto" }) },
  "mr-0": { fields: ["marginRight"], resolve: () => ({ marginRight: 0 }) },
  "mr-1": { fields: ["marginRight"], resolve: () => ({ marginRight: 4 }) },
  "mr-10": { fields: ["marginRight"], resolve: () => ({ marginRight: 40 }) },
  "mr-12": { fields: ["marginRight"], resolve: () => ({ marginRight: 48 }) },
  "mr-16": { fields: ["marginRight"], resolve: () => ({ marginRight: 64 }) },
  "mr-2": { fields: ["marginRight"], resolve: () => ({ marginRight: 8 }) },
  "mr-20": { fields: ["marginRight"], resolve: () => ({ marginRight: 80 }) },
  "mr-24": { fields: ["marginRight"], resolve: () => ({ marginRight: 96 }) },
  "mr-3": { fields: ["marginRight"], resolve: () => ({ marginRight: 12 }) },
  "mr-32": { fields: ["marginRight"], resolve: () => ({ marginRight: 128 }) },
  "mr-4": { fields: ["marginRight"], resolve: () => ({ marginRight: 16 }) },
  "mr-5": { fields: ["marginRight"], resolve: () => ({ marginRight: 20 }) },
  "mr-6": { fields: ["marginRight"], resolve: () => ({ marginRight: 24 }) },
  "mr-8": { fields: ["marginRight"], resolve: () => ({ marginRight: 32 }) },
  "mr-auto": { fields: ["marginRight"], resolve: () => ({ marginRight: "auto" }) },
  "mt-0": { fields: ["marginTop"], resolve: () => ({ marginTop: 0 }) },
  "mt-1": { fields: ["marginTop"], resolve: () => ({ marginTop: 4 }) },
  "mt-10": { fields: ["marginTop"], resolve: () => ({ marginTop: 40 }) },
  "mt-12": { fields: ["marginTop"], resolve: () => ({ marginTop: 48 }) },
  "mt-16": { fields: ["marginTop"], resolve: () => ({ marginTop: 64 }) },
  "mt-2": { fields: ["marginTop"], resolve: () => ({ marginTop: 8 }) },
  "mt-20": { fields: ["marginTop"], resolve: () => ({ marginTop: 80 }) },
  "mt-24": { fields: ["marginTop"], resolve: () => ({ marginTop: 96 }) },
  "mt-3": { fields: ["marginTop"], resolve: () => ({ marginTop: 12 }) },
  "mt-32": { fields: ["marginTop"], resolve: () => ({ marginTop: 128 }) },
  "mt-4": { fields: ["marginTop"], resolve: () => ({ marginTop: 16 }) },
  "mt-5": { fields: ["marginTop"], resolve: () => ({ marginTop: 20 }) },
  "mt-6": { fields: ["marginTop"], resolve: () => ({ marginTop: 24 }) },
  "mt-8": { fields: ["marginTop"], resolve: () => ({ marginTop: 32 }) },
  "mt-auto": { fields: ["marginTop"], resolve: () => ({ marginTop: "auto" }) },
  "mx-0": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 0, marginRight: 0 }),
  },
  "mx-1": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 4, marginRight: 4 }),
  },
  "mx-10": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 40, marginRight: 40 }),
  },
  "mx-12": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 48, marginRight: 48 }),
  },
  "mx-16": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 64, marginRight: 64 }),
  },
  "mx-2": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 8, marginRight: 8 }),
  },
  "mx-20": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 80, marginRight: 80 }),
  },
  "mx-24": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 96, marginRight: 96 }),
  },
  "mx-3": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 12, marginRight: 12 }),
  },
  "mx-32": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 128, marginRight: 128 }),
  },
  "mx-4": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 16, marginRight: 16 }),
  },
  "mx-5": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 20, marginRight: 20 }),
  },
  "mx-6": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 24, marginRight: 24 }),
  },
  "mx-8": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 32, marginRight: 32 }),
  },
  "mx-auto": {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: "auto", marginRight: "auto" }),
  },
  "my-0": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 0, marginBottom: 0 }),
  },
  "my-1": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 4, marginBottom: 4 }),
  },
  "my-10": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 40, marginBottom: 40 }),
  },
  "my-12": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 48, marginBottom: 48 }),
  },
  "my-16": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 64, marginBottom: 64 }),
  },
  "my-2": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 8, marginBottom: 8 }),
  },
  "my-20": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 80, marginBottom: 80 }),
  },
  "my-24": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 96, marginBottom: 96 }),
  },
  "my-3": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 12, marginBottom: 12 }),
  },
  "my-32": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 128, marginBottom: 128 }),
  },
  "my-4": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 16, marginBottom: 16 }),
  },
  "my-5": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 20, marginBottom: 20 }),
  },
  "my-6": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 24, marginBottom: 24 }),
  },
  "my-8": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 32, marginBottom: 32 }),
  },
  "my-auto": {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: "auto", marginBottom: "auto" }),
  },
  "overflow-hidden": {
    fields: ["overflowX", "overflowY"],
    resolve: () => ({ overflowX: "hidden", overflowY: "hidden" }),
  },
  "overflow-scroll": {
    fields: ["overflowX", "overflowY"],
    resolve: () => ({ overflowX: "scroll", overflowY: "scroll" }),
  },
  "overflow-x-scroll": {
    fields: ["overflowX", "overflowY"],
    resolve: () => ({ overflowX: "scroll", overflowY: "hidden" }),
  },
  "overflow-y-scroll": {
    fields: ["overflowX", "overflowY"],
    resolve: () => ({ overflowX: "hidden", overflowY: "scroll" }),
  },
  "p-1": {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 4, paddingRight: 4, paddingBottom: 4, paddingLeft: 4 }),
  },
  "p-2": {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 8, paddingRight: 8, paddingBottom: 8, paddingLeft: 8 }),
  },
  "p-3": {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 12, paddingRight: 12, paddingBottom: 12, paddingLeft: 12 }),
  },
  "p-4": {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 16, paddingRight: 16, paddingBottom: 16, paddingLeft: 16 }),
  },
  "p-5": {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 20, paddingRight: 20, paddingBottom: 20, paddingLeft: 20 }),
  },
  "p-6": {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 24, paddingRight: 24, paddingBottom: 24, paddingLeft: 24 }),
  },
  "px-2": {
    fields: ["paddingLeft", "paddingRight"],
    resolve: () => ({ paddingLeft: 8, paddingRight: 8 }),
  },
  "px-3": {
    fields: ["paddingLeft", "paddingRight"],
    resolve: () => ({ paddingLeft: 12, paddingRight: 12 }),
  },
  "px-4": {
    fields: ["paddingLeft", "paddingRight"],
    resolve: () => ({ paddingLeft: 16, paddingRight: 16 }),
  },
  "py-1": {
    fields: ["paddingTop", "paddingBottom"],
    resolve: () => ({ paddingTop: 4, paddingBottom: 4 }),
  },
  "py-2": {
    fields: ["paddingTop", "paddingBottom"],
    resolve: () => ({ paddingTop: 8, paddingBottom: 8 }),
  },
  relative: { fields: ["position"], resolve: () => ({ position: "relative" }) },
  "rounded-2xl": {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 16,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-full": {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 4096,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-lg": {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 8,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-md": {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 6,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-sm": {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 4,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-xl": {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 12,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "row-end-auto": { fields: ["gridRowEnd"], resolve: () => ({ gridRowEnd: 0 }) },
  "row-span-full": {
    fields: ["gridRowSpan", "gridRowStart", "gridRowEnd"],
    resolve: () => ({ gridRowSpan: null, gridRowStart: 1, gridRowEnd: -1 }),
  },
  "row-start-auto": { fields: ["gridRowStart"], resolve: () => ({ gridRowStart: 0 }) },
  rtl: { fields: ["direction"], resolve: () => ({ direction: "rtl" }) },
  selectable: { fields: ["userSelect"], resolve: () => ({ userSelect: "text" }) },
  "self-baseline": { fields: ["alignSelf"], resolve: () => ({ alignSelf: "baseline" }) },
  "self-center": { fields: ["alignSelf"], resolve: () => ({ alignSelf: "center" }) },
  "self-end": { fields: ["alignSelf"], resolve: () => ({ alignSelf: "end" }) },
  "self-flex-end": { fields: ["alignSelf"], resolve: () => ({ alignSelf: "flex-end" }) },
  "self-flex-start": { fields: ["alignSelf"], resolve: () => ({ alignSelf: "flex-start" }) },
  "self-start": { fields: ["alignSelf"], resolve: () => ({ alignSelf: "start" }) },
  "self-stretch": { fields: ["alignSelf"], resolve: () => ({ alignSelf: "stretch" }) },
  "size-full": { fields: ["width", "height"], resolve: () => ({ width: "100%", height: "100%" }) },
  "snap-stop-always": { fields: ["scrollSnapStop"], resolve: () => ({ scrollSnapStop: "always" }) },
  "position-sticky": { fields: ["position"], resolve: () => ({ position: "sticky" }) },
  "text-2xl": {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 24, lineHeight: 32 }),
  },
  "text-3xl": {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 30, lineHeight: 36 }),
  },
  "text-base": {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 16, lineHeight: 24 }),
  },
  "text-center": { fields: ["textAlign"], resolve: () => ({ textAlign: "center" }) },
  "text-ellipsis": { fields: ["textOverflow"], resolve: () => ({ textOverflow: "ellipsis" }) },
  "text-ellipsis-middle": {
    fields: ["textOverflow"],
    resolve: () => ({ textOverflow: "ellipsis-middle" }),
  },
  "text-ellipsis-start": {
    fields: ["textOverflow"],
    resolve: () => ({ textOverflow: "ellipsis-start" }),
  },
  "text-end": { fields: ["textAlign"], resolve: () => ({ textAlign: "end" }) },
  "text-justify": { fields: ["textAlign"], resolve: () => ({ textAlign: "justify" }) },
  "text-left": { fields: ["textAlign"], resolve: () => ({ textAlign: "left" }) },
  "text-lg": {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 18, lineHeight: 26 }),
  },
  "text-right": { fields: ["textAlign"], resolve: () => ({ textAlign: "right" }) },
  "text-sm": {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 14, lineHeight: 20 }),
  },
  "text-start": { fields: ["textAlign"], resolve: () => ({ textAlign: "start" }) },
  "text-xl": {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 20, lineHeight: 28 }),
  },
  "text-xs": {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 12, lineHeight: 16 }),
  },
  truncate: {
    fields: ["overflowX", "overflowY", "whiteSpace", "textOverflow"],
    resolve: () => ({
      overflowX: "hidden",
      overflowY: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    }),
  },
  "user-select-none": { fields: ["userSelect"], resolve: () => ({ userSelect: "none" }) },
  "user-select-text": { fields: ["userSelect"], resolve: () => ({ userSelect: "text" }) },
  visible: { fields: ["visibility"], resolve: () => ({ visibility: "visible" }) },
  "w-full": { fields: ["width"], resolve: () => ({ width: "100%" }) },
  "whitespace-normal": { fields: ["whiteSpace"], resolve: () => ({ whiteSpace: "normal" }) },
  "whitespace-nowrap": { fields: ["whiteSpace"], resolve: () => ({ whiteSpace: "nowrap" }) },
};

export const helperProperties = new Set(
  Object.values(styleHelpers).flatMap((helper) => helper.fields),
);

/** Native style values exposed as kebab-case JSX attributes. */
export interface StyleAttributes {
  "text-color"?: JSX.Style["textColor"];
  "flex-direction"?: JSX.Style["flexDirection"];
  "flex-grow"?: JSX.Style["flexGrow"];
  "flex-shrink"?: JSX.Style["flexShrink"];
  "flex-basis"?: JSX.Style["flexBasis"];
  "align-items"?: JSX.Style["alignItems"];
  "align-self"?: JSX.Style["alignSelf"];
  "justify-content"?: JSX.Style["justifyContent"];
  "align-content"?: JSX.Style["alignContent"];
  "column-gap"?: JSX.Style["columnGap"];
  "row-gap"?: JSX.Style["rowGap"];
  "min-width"?: JSX.Style["minWidth"];
  "min-height"?: JSX.Style["minHeight"];
  "max-width"?: JSX.Style["maxWidth"];
  "max-height"?: JSX.Style["maxHeight"];
  "padding-top"?: JSX.Style["paddingTop"];
  "padding-right"?: JSX.Style["paddingRight"];
  "padding-bottom"?: JSX.Style["paddingBottom"];
  "padding-left"?: JSX.Style["paddingLeft"];
  "margin-top"?: JSX.Style["marginTop"];
  "margin-right"?: JSX.Style["marginRight"];
  "margin-bottom"?: JSX.Style["marginBottom"];
  "margin-left"?: JSX.Style["marginLeft"];
  "hover-color"?: JSX.Style["hoverColor"];
  "active-color"?: JSX.Style["activeColor"];
  "border-width"?: JSX.Style["borderWidth"];
  "border-top-width"?: JSX.Style["borderTopWidth"];
  "border-right-width"?: JSX.Style["borderRightWidth"];
  "border-bottom-width"?: JSX.Style["borderBottomWidth"];
  "border-left-width"?: JSX.Style["borderLeftWidth"];
  "border-color"?: JSX.Style["borderColor"];
  "border-radius"?: JSX.Style["borderRadius"];
  "box-shadow"?: JSX.Style["boxShadow"];
  "font-size"?: JSX.Style["fontSize"];
  "font-family"?: JSX.Style["fontFamily"];
  "font-weight"?: JSX.Style["fontWeight"];
  "line-height"?: JSX.Style["lineHeight"];
  "text-align"?: JSX.Style["textAlign"];
  "white-space"?: JSX.Style["whiteSpace"];
  "text-overflow"?: JSX.Style["textOverflow"];
  "line-clamp"?: JSX.Style["lineClamp"];
  "overflow-x"?: JSX.Style["overflowX"];
  "overflow-y"?: JSX.Style["overflowY"];
  "app-region"?: JSX.Style["appRegion"];
  "user-select"?: JSX.Style["userSelect"];
  "aspect-ratio"?: JSX.Style["aspectRatio"];
  "grid-template-columns"?: JSX.Style["gridTemplateColumns"];
  "grid-template-rows"?: JSX.Style["gridTemplateRows"];
  "grid-auto-flow"?: JSX.Style["gridAutoFlow"];
  "grid-column"?: JSX.Style["gridColumn"];
  "grid-row"?: JSX.Style["gridRow"];
  "grid-column-start"?: JSX.Style["gridColumnStart"];
  "grid-column-end"?: JSX.Style["gridColumnEnd"];
  "grid-column-span"?: JSX.Style["gridColumnSpan"];
  "grid-row-start"?: JSX.Style["gridRowStart"];
  "grid-row-end"?: JSX.Style["gridRowEnd"];
  "grid-row-span"?: JSX.Style["gridRowSpan"];
  "transition-property"?: JSX.Style["transitionProperty"];
  "transition-duration"?: JSX.Style["transitionDuration"];
  "transition-timing-function"?: JSX.Style["transitionTimingFunction"];
  "transition-easing"?: JSX.Style["transitionEasing"];
  "transition-max-fps"?: JSX.Style["transitionMaxFps"];
  "object-fit"?: JSX.Style["objectFit"];
  "markdown-code-background"?: JSX.Style["markdownCodeBackground"];
  "markdown-border-color"?: JSX.Style["markdownBorderColor"];
  "markdown-muted-color"?: JSX.Style["markdownMutedColor"];
  "markdown-link-color"?: JSX.Style["markdownLinkColor"];
  "markdown-code-text-color"?: JSX.Style["markdownCodeTextColor"];
  "markdown-block-gap"?: JSX.Style["markdownBlockGap"];
  "markdown-code-font-size"?: JSX.Style["markdownCodeFontSize"];
  "scroll-to-end-revision"?: JSX.Style["scrollToEndRevision"];
  "letter-spacing"?: JSX.Style["letterSpacing"];
  "word-spacing"?: JSX.Style["wordSpacing"];
  "text-transform"?: JSX.Style["textTransform"];
  "text-shadow"?: JSX.Style["textShadow"];
  "text-decoration"?: JSX.Style["textDecoration"];
  "text-decoration-line"?: JSX.Style["textDecorationLine"];
  "text-decoration-color"?: JSX.Style["textDecorationColor"];
  "text-decoration-style"?: JSX.Style["textDecorationStyle"];
  "text-decoration-thickness"?: JSX.Style["textDecorationThickness"];
  "word-break"?: JSX.Style["wordBreak"];
  "overflow-wrap"?: JSX.Style["overflowWrap"];
  "text-direction"?: JSX.Style["textDirection"];
  "padding-start"?: JSX.Style["paddingStart"];
  "padding-end"?: JSX.Style["paddingEnd"];
  "margin-start"?: JSX.Style["marginStart"];
  "margin-end"?: JSX.Style["marginEnd"];
  "border-start-width"?: JSX.Style["borderStartWidth"];
  "border-end-width"?: JSX.Style["borderEndWidth"];
  "bg-gradient"?: JSX.Style["bgGradient"];
  "border-top-left-radius"?: JSX.Style["borderTopLeftRadius"];
  "border-top-right-radius"?: JSX.Style["borderTopRightRadius"];
  "border-bottom-right-radius"?: JSX.Style["borderBottomRightRadius"];
  "border-bottom-left-radius"?: JSX.Style["borderBottomLeftRadius"];
  "border-style"?: JSX.Style["borderStyle"];
  "outline-width"?: JSX.Style["outlineWidth"];
  "outline-color"?: JSX.Style["outlineColor"];
  "outline-offset"?: JSX.Style["outlineOffset"];
  "outline-style"?: JSX.Style["outlineStyle"];
  "bg-image"?: JSX.Style["bgImage"];
  "bg-size"?: JSX.Style["bgSize"];
  "bg-repeat"?: JSX.Style["bgRepeat"];
  "bg-position"?: JSX.Style["bgPosition"];
  "backdrop-filter"?: JSX.Style["backdropFilter"];
  "transform-origin"?: JSX.Style["transformOrigin"];
  "mix-blend-mode"?: JSX.Style["mixBlendMode"];
  "hover-bg"?: JSX.Style["hoverBg"];
  "hover-outline"?: JSX.Style["hoverOutline"];
  "hover-transform"?: JSX.Style["hoverTransform"];
  "active-bg"?: JSX.Style["activeBg"];
  "active-outline"?: JSX.Style["activeOutline"];
  "active-transform"?: JSX.Style["activeTransform"];
  "focus-bg"?: JSX.Style["focusBg"];
  "focus-color"?: JSX.Style["focusColor"];
  "focus-outline"?: JSX.Style["focusOutline"];
  "focus-transform"?: JSX.Style["focusTransform"];
  "scroll-snap-type"?: JSX.Style["scrollSnapType"];
  "scroll-snap-align"?: JSX.Style["scrollSnapAlign"];
  "scroll-snap-stop"?: JSX.Style["scrollSnapStop"];
}

export const styleAttributeNames: Record<string, string> = {
  "text-color": "textColor",
  "flex-direction": "flexDirection",
  "flex-grow": "flexGrow",
  "flex-shrink": "flexShrink",
  "flex-basis": "flexBasis",
  "align-items": "alignItems",
  "align-self": "alignSelf",
  "justify-content": "justifyContent",
  "align-content": "alignContent",
  "column-gap": "columnGap",
  "row-gap": "rowGap",
  "min-width": "minWidth",
  "min-height": "minHeight",
  "max-width": "maxWidth",
  "max-height": "maxHeight",
  "padding-top": "paddingTop",
  "padding-right": "paddingRight",
  "padding-bottom": "paddingBottom",
  "padding-left": "paddingLeft",
  "margin-top": "marginTop",
  "margin-right": "marginRight",
  "margin-bottom": "marginBottom",
  "margin-left": "marginLeft",
  "hover-color": "hoverColor",
  "active-color": "activeColor",
  "border-width": "borderWidth",
  "border-top-width": "borderTopWidth",
  "border-right-width": "borderRightWidth",
  "border-bottom-width": "borderBottomWidth",
  "border-left-width": "borderLeftWidth",
  "border-color": "borderColor",
  "border-radius": "borderRadius",
  "box-shadow": "boxShadow",
  "font-size": "fontSize",
  "font-family": "fontFamily",
  "font-weight": "fontWeight",
  "line-height": "lineHeight",
  "text-align": "textAlign",
  "white-space": "whiteSpace",
  "text-overflow": "textOverflow",
  "line-clamp": "lineClamp",
  "overflow-x": "overflowX",
  "overflow-y": "overflowY",
  "app-region": "appRegion",
  "user-select": "userSelect",
  "aspect-ratio": "aspectRatio",
  "grid-template-columns": "gridTemplateColumns",
  "grid-template-rows": "gridTemplateRows",
  "grid-auto-flow": "gridAutoFlow",
  "grid-column": "gridColumn",
  "grid-row": "gridRow",
  "grid-column-start": "gridColumnStart",
  "grid-column-end": "gridColumnEnd",
  "grid-column-span": "gridColumnSpan",
  "grid-row-start": "gridRowStart",
  "grid-row-end": "gridRowEnd",
  "grid-row-span": "gridRowSpan",
  "transition-property": "transitionProperty",
  "transition-duration": "transitionDuration",
  "transition-timing-function": "transitionTimingFunction",
  "transition-easing": "transitionEasing",
  "transition-max-fps": "transitionMaxFps",
  "object-fit": "objectFit",
  "markdown-code-background": "markdownCodeBackground",
  "markdown-border-color": "markdownBorderColor",
  "markdown-muted-color": "markdownMutedColor",
  "markdown-link-color": "markdownLinkColor",
  "markdown-code-text-color": "markdownCodeTextColor",
  "markdown-block-gap": "markdownBlockGap",
  "markdown-code-font-size": "markdownCodeFontSize",
  "scroll-to-end-revision": "scrollToEndRevision",
  "letter-spacing": "letterSpacing",
  "word-spacing": "wordSpacing",
  "text-transform": "textTransform",
  "text-shadow": "textShadow",
  "text-decoration": "textDecoration",
  "text-decoration-line": "textDecorationLine",
  "text-decoration-color": "textDecorationColor",
  "text-decoration-style": "textDecorationStyle",
  "text-decoration-thickness": "textDecorationThickness",
  "word-break": "wordBreak",
  "overflow-wrap": "overflowWrap",
  "text-direction": "textDirection",
  "padding-start": "paddingStart",
  "padding-end": "paddingEnd",
  "margin-start": "marginStart",
  "margin-end": "marginEnd",
  "border-start-width": "borderStartWidth",
  "border-end-width": "borderEndWidth",
  "bg-gradient": "bgGradient",
  "border-top-left-radius": "borderTopLeftRadius",
  "border-top-right-radius": "borderTopRightRadius",
  "border-bottom-right-radius": "borderBottomRightRadius",
  "border-bottom-left-radius": "borderBottomLeftRadius",
  "border-style": "borderStyle",
  "outline-width": "outlineWidth",
  "outline-color": "outlineColor",
  "outline-offset": "outlineOffset",
  "outline-style": "outlineStyle",
  "bg-image": "bgImage",
  "bg-size": "bgSize",
  "bg-repeat": "bgRepeat",
  "bg-position": "bgPosition",
  "backdrop-filter": "backdropFilter",
  "transform-origin": "transformOrigin",
  "mix-blend-mode": "mixBlendMode",
  "hover-bg": "hoverBg",
  "hover-outline": "hoverOutline",
  "hover-transform": "hoverTransform",
  "active-bg": "activeBg",
  "active-outline": "activeOutline",
  "active-transform": "activeTransform",
  "focus-bg": "focusBg",
  "focus-color": "focusColor",
  "focus-outline": "focusOutline",
  "focus-transform": "focusTransform",
  "scroll-snap-type": "scrollSnapType",
  "scroll-snap-align": "scrollSnapAlign",
  "scroll-snap-stop": "scrollSnapStop",
};
