// Code generated by bun scripts/generate-style-helpers.ts; DO NOT EDIT.

export const roundedPresets = { "2xl": 16, full: 4096, lg: 8, md: 6, sm: 4, xl: 12 } as const;
export type RoundedPreset = keyof typeof roundedPresets;

/** Rust Element conveniences in kebab-case, usable as JSX props or inside a style object. */
export interface StyleHelpers {
  /** Matches Rust's absolute. */
  absolute?: boolean | null | undefined;
  /** Matches Rust's app_region_drag. */
  "app-region-drag"?: boolean | null | undefined;
  /** Matches Rust's app_region_no_drag. */
  "app-region-no-drag"?: boolean | null | undefined;
  /** Matches Rust's aspect_square. */
  "aspect-square"?: boolean | null | undefined;
  /** Matches Rust's block. */
  block?: boolean | null | undefined;
  /** Matches Rust's border_dashed. */
  "border-dashed"?: boolean | null | undefined;
  /** Matches Rust's border_dotted. */
  "border-dotted"?: boolean | null | undefined;
  /** Matches Rust's border_e. */
  "border-e"?: number | string | false | null | undefined;
  /** Matches Rust's border_s. */
  "border-s"?: number | string | false | null | undefined;
  /** Matches Rust's border_solid. */
  "border-solid"?: boolean | null | undefined;
  /** Matches Rust's col_end. */
  "col-end"?: number | string | false | null | undefined;
  /** Matches Rust's col_end_auto. */
  "col-end-auto"?: boolean | null | undefined;
  /** Matches Rust's col_span. */
  "col-span"?: number | string | false | null | undefined;
  /** Matches Rust's col_span_full. */
  "col-span-full"?: boolean | null | undefined;
  /** Matches Rust's col_start. */
  "col-start"?: number | string | false | null | undefined;
  /** Matches Rust's col_start_auto. */
  "col-start-auto"?: boolean | null | undefined;
  /** Matches Rust's content_around. */
  "content-around"?: boolean | null | undefined;
  /** Matches Rust's content_between. */
  "content-between"?: boolean | null | undefined;
  /** Matches Rust's content_center. */
  "content-center"?: boolean | null | undefined;
  /** Matches Rust's content_end. */
  "content-end"?: boolean | null | undefined;
  /** Matches Rust's content_evenly. */
  "content-evenly"?: boolean | null | undefined;
  /** Matches Rust's content_normal. */
  "content-normal"?: boolean | null | undefined;
  /** Matches Rust's content_start. */
  "content-start"?: boolean | null | undefined;
  /** Matches Rust's content_stretch. */
  "content-stretch"?: boolean | null | undefined;
  /** Matches Rust's cursor_alias. */
  "cursor-alias"?: boolean | null | undefined;
  /** Matches Rust's cursor_col_resize. */
  "cursor-col-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_context_menu. */
  "cursor-context-menu"?: boolean | null | undefined;
  /** Matches Rust's cursor_copy. */
  "cursor-copy"?: boolean | null | undefined;
  /** Matches Rust's cursor_crosshair. */
  "cursor-crosshair"?: boolean | null | undefined;
  /** Matches Rust's cursor_default. */
  "cursor-default"?: boolean | null | undefined;
  /** Matches Rust's cursor_e_resize. */
  "cursor-e-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_ew_resize. */
  "cursor-ew-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_grab. */
  "cursor-grab"?: boolean | null | undefined;
  /** Matches Rust's cursor_grabbing. */
  "cursor-grabbing"?: boolean | null | undefined;
  /** Matches Rust's cursor_move. */
  "cursor-move"?: boolean | null | undefined;
  /** Matches Rust's cursor_n_resize. */
  "cursor-n-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_nesw_resize. */
  "cursor-nesw-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_no_drop. */
  "cursor-no-drop"?: boolean | null | undefined;
  /** Matches Rust's cursor_not_allowed. */
  "cursor-not-allowed"?: boolean | null | undefined;
  /** Matches Rust's cursor_ns_resize. */
  "cursor-ns-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_nwse_resize. */
  "cursor-nwse-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_pointer. */
  "cursor-pointer"?: boolean | null | undefined;
  /** Matches Rust's cursor_row_resize. */
  "cursor-row-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_s_resize. */
  "cursor-s-resize"?: boolean | null | undefined;
  /** Matches Rust's cursor_text. */
  "cursor-text"?: boolean | null | undefined;
  /** Matches Rust's cursor_vertical_text. */
  "cursor-vertical-text"?: boolean | null | undefined;
  /** Matches Rust's cursor_w_resize. */
  "cursor-w-resize"?: boolean | null | undefined;
  /** Matches Rust's flex. */
  flex?: boolean | number | string | null | undefined;
  /** Matches Rust's flex_1. */
  "flex-1"?: boolean | null | undefined;
  /** Matches Rust's flex_auto. */
  "flex-auto"?: boolean | null | undefined;
  /** Matches Rust's flex_basis_auto. */
  "flex-basis-auto"?: boolean | null | undefined;
  /** Matches Rust's flex_col. */
  "flex-col"?: boolean | null | undefined;
  /** Matches Rust's flex_col_reverse. */
  "flex-col-reverse"?: boolean | null | undefined;
  /** Matches Rust's flex_grow_0. */
  "flex-grow-0"?: boolean | null | undefined;
  /** Matches Rust's flex_grow_1. */
  "flex-grow-1"?: boolean | null | undefined;
  /** Matches Rust's flex_initial. */
  "flex-initial"?: boolean | null | undefined;
  /** Matches Rust's flex_none. */
  "flex-none"?: boolean | null | undefined;
  /** Matches Rust's flex_nowrap. */
  "flex-nowrap"?: boolean | null | undefined;
  /** Matches Rust's flex_row. */
  "flex-row"?: boolean | null | undefined;
  /** Matches Rust's flex_row_reverse. */
  "flex-row-reverse"?: boolean | null | undefined;
  /** Matches Rust's flex_shrink_0. */
  "flex-shrink-0"?: boolean | null | undefined;
  /** Matches Rust's flex_shrink_1. */
  "flex-shrink-1"?: boolean | null | undefined;
  /** Matches Rust's flex_wrap. */
  "flex-wrap"?: boolean | "nowrap" | "wrap" | "wrap-reverse" | null | undefined;
  /** Matches Rust's flex_wrap_reverse. */
  "flex-wrap-reverse"?: boolean | null | undefined;
  /** Matches Rust's font_bold. */
  "font-bold"?: boolean | null | undefined;
  /** Matches Rust's font_medium. */
  "font-medium"?: boolean | null | undefined;
  /** Matches Rust's font_normal. */
  "font-normal"?: boolean | null | undefined;
  /** Matches Rust's font_semibold. */
  "font-semibold"?: boolean | null | undefined;
  /** Matches Rust's gap_1. */
  "gap-1"?: boolean | null | undefined;
  /** Matches Rust's gap_2. */
  "gap-2"?: boolean | null | undefined;
  /** Matches Rust's gap_3. */
  "gap-3"?: boolean | null | undefined;
  /** Matches Rust's gap_4. */
  "gap-4"?: boolean | null | undefined;
  /** Matches Rust's gap_5. */
  "gap-5"?: boolean | null | undefined;
  /** Matches Rust's gap_6. */
  "gap-6"?: boolean | null | undefined;
  /** Matches Rust's gap_x. */
  "gap-x"?: number | string | false | null | undefined;
  /** Matches Rust's gap_x_0. */
  "gap-x-0"?: boolean | null | undefined;
  /** Matches Rust's gap_x_1. */
  "gap-x-1"?: boolean | null | undefined;
  /** Matches Rust's gap_x_2. */
  "gap-x-2"?: boolean | null | undefined;
  /** Matches Rust's gap_x_3. */
  "gap-x-3"?: boolean | null | undefined;
  /** Matches Rust's gap_x_4. */
  "gap-x-4"?: boolean | null | undefined;
  /** Matches Rust's gap_x_5. */
  "gap-x-5"?: boolean | null | undefined;
  /** Matches Rust's gap_x_6. */
  "gap-x-6"?: boolean | null | undefined;
  /** Matches Rust's gap_y. */
  "gap-y"?: number | string | false | null | undefined;
  /** Matches Rust's gap_y_0. */
  "gap-y-0"?: boolean | null | undefined;
  /** Matches Rust's gap_y_1. */
  "gap-y-1"?: boolean | null | undefined;
  /** Matches Rust's gap_y_2. */
  "gap-y-2"?: boolean | null | undefined;
  /** Matches Rust's gap_y_3. */
  "gap-y-3"?: boolean | null | undefined;
  /** Matches Rust's gap_y_4. */
  "gap-y-4"?: boolean | null | undefined;
  /** Matches Rust's gap_y_5. */
  "gap-y-5"?: boolean | null | undefined;
  /** Matches Rust's gap_y_6. */
  "gap-y-6"?: boolean | null | undefined;
  /** Matches Rust's grid. */
  grid?: boolean | null | undefined;
  /** Matches Rust's grid_cols. */
  "grid-cols"?: number | false | null | undefined;
  /** Matches Rust's grid_cols_max_content. */
  "grid-cols-max-content"?: number | false | null | undefined;
  /** Matches Rust's grid_cols_min_content. */
  "grid-cols-min-content"?: number | false | null | undefined;
  /** Matches Rust's grid_flow_col. */
  "grid-flow-col"?: boolean | null | undefined;
  /** Matches Rust's grid_flow_col_dense. */
  "grid-flow-col-dense"?: boolean | null | undefined;
  /** Matches Rust's grid_flow_row. */
  "grid-flow-row"?: boolean | null | undefined;
  /** Matches Rust's grid_flow_row_dense. */
  "grid-flow-row-dense"?: boolean | null | undefined;
  /** Matches Rust's grid_rows. */
  "grid-rows"?: number | false | null | undefined;
  /** Matches Rust's grid_rows_max_content. */
  "grid-rows-max-content"?: number | false | null | undefined;
  /** Matches Rust's grid_rows_min_content. */
  "grid-rows-min-content"?: number | false | null | undefined;
  /** Matches Rust's h. */
  h?: number | string | false | null | undefined;
  /** Matches Rust's h_10. */
  "h-10"?: boolean | null | undefined;
  /** Matches Rust's h_12. */
  "h-12"?: boolean | null | undefined;
  /** Matches Rust's h_8. */
  "h-8"?: boolean | null | undefined;
  /** Matches Rust's h_fraction. */
  "h-fraction"?: number | false | null | undefined;
  /** Matches Rust's h_full. */
  "h-full"?: boolean | null | undefined;
  /** Matches Rust's hidden. */
  hidden?: boolean | null | undefined;
  /** Matches Rust's inset_0. */
  "inset-0"?: boolean | null | undefined;
  /** Matches Rust's invisible. */
  invisible?: boolean | null | undefined;
  /** Matches Rust's items_baseline. */
  "items-baseline"?: boolean | null | undefined;
  /** Matches Rust's items_center. */
  "items-center"?: boolean | null | undefined;
  /** Matches Rust's items_end. */
  "items-end"?: boolean | null | undefined;
  /** Matches Rust's items_start. */
  "items-start"?: boolean | null | undefined;
  /** Matches Rust's items_stretch. */
  "items-stretch"?: boolean | null | undefined;
  /** Matches Rust's justify_around. */
  "justify-around"?: boolean | null | undefined;
  /** Matches Rust's justify_between. */
  "justify-between"?: boolean | null | undefined;
  /** Matches Rust's justify_center. */
  "justify-center"?: boolean | null | undefined;
  /** Matches Rust's justify_end. */
  "justify-end"?: boolean | null | undefined;
  /** Matches Rust's justify_evenly. */
  "justify-evenly"?: boolean | null | undefined;
  /** Matches Rust's justify_start. */
  "justify-start"?: boolean | null | undefined;
  /** Matches Rust's ltr. */
  ltr?: boolean | null | undefined;
  /** Matches Rust's m. */
  m?: number | string | false | null | undefined;
  /** Matches Rust's m_0. */
  "m-0"?: boolean | null | undefined;
  /** Matches Rust's m_1. */
  "m-1"?: boolean | null | undefined;
  /** Matches Rust's m_10. */
  "m-10"?: boolean | null | undefined;
  /** Matches Rust's m_12. */
  "m-12"?: boolean | null | undefined;
  /** Matches Rust's m_16. */
  "m-16"?: boolean | null | undefined;
  /** Matches Rust's m_2. */
  "m-2"?: boolean | null | undefined;
  /** Matches Rust's m_20. */
  "m-20"?: boolean | null | undefined;
  /** Matches Rust's m_24. */
  "m-24"?: boolean | null | undefined;
  /** Matches Rust's m_3. */
  "m-3"?: boolean | null | undefined;
  /** Matches Rust's m_32. */
  "m-32"?: boolean | null | undefined;
  /** Matches Rust's m_4. */
  "m-4"?: boolean | null | undefined;
  /** Matches Rust's m_5. */
  "m-5"?: boolean | null | undefined;
  /** Matches Rust's m_6. */
  "m-6"?: boolean | null | undefined;
  /** Matches Rust's m_8. */
  "m-8"?: boolean | null | undefined;
  /** Matches Rust's m_auto. */
  "m-auto"?: boolean | null | undefined;
  /** Matches Rust's max_h. */
  "max-h"?: number | string | false | null | undefined;
  /** Matches Rust's max_w. */
  "max-w"?: number | string | false | null | undefined;
  /** Matches Rust's mb. */
  mb?: number | string | false | null | undefined;
  /** Matches Rust's mb_0. */
  "mb-0"?: boolean | null | undefined;
  /** Matches Rust's mb_1. */
  "mb-1"?: boolean | null | undefined;
  /** Matches Rust's mb_10. */
  "mb-10"?: boolean | null | undefined;
  /** Matches Rust's mb_12. */
  "mb-12"?: boolean | null | undefined;
  /** Matches Rust's mb_16. */
  "mb-16"?: boolean | null | undefined;
  /** Matches Rust's mb_2. */
  "mb-2"?: boolean | null | undefined;
  /** Matches Rust's mb_20. */
  "mb-20"?: boolean | null | undefined;
  /** Matches Rust's mb_24. */
  "mb-24"?: boolean | null | undefined;
  /** Matches Rust's mb_3. */
  "mb-3"?: boolean | null | undefined;
  /** Matches Rust's mb_32. */
  "mb-32"?: boolean | null | undefined;
  /** Matches Rust's mb_4. */
  "mb-4"?: boolean | null | undefined;
  /** Matches Rust's mb_5. */
  "mb-5"?: boolean | null | undefined;
  /** Matches Rust's mb_6. */
  "mb-6"?: boolean | null | undefined;
  /** Matches Rust's mb_8. */
  "mb-8"?: boolean | null | undefined;
  /** Matches Rust's mb_auto. */
  "mb-auto"?: boolean | null | undefined;
  /** Matches Rust's me. */
  me?: number | string | false | null | undefined;
  /** Matches Rust's min_h. */
  "min-h"?: number | string | false | null | undefined;
  /** Matches Rust's min_w. */
  "min-w"?: number | string | false | null | undefined;
  /** Matches Rust's ml. */
  ml?: number | string | false | null | undefined;
  /** Matches Rust's ml_0. */
  "ml-0"?: boolean | null | undefined;
  /** Matches Rust's ml_1. */
  "ml-1"?: boolean | null | undefined;
  /** Matches Rust's ml_10. */
  "ml-10"?: boolean | null | undefined;
  /** Matches Rust's ml_12. */
  "ml-12"?: boolean | null | undefined;
  /** Matches Rust's ml_16. */
  "ml-16"?: boolean | null | undefined;
  /** Matches Rust's ml_2. */
  "ml-2"?: boolean | null | undefined;
  /** Matches Rust's ml_20. */
  "ml-20"?: boolean | null | undefined;
  /** Matches Rust's ml_24. */
  "ml-24"?: boolean | null | undefined;
  /** Matches Rust's ml_3. */
  "ml-3"?: boolean | null | undefined;
  /** Matches Rust's ml_32. */
  "ml-32"?: boolean | null | undefined;
  /** Matches Rust's ml_4. */
  "ml-4"?: boolean | null | undefined;
  /** Matches Rust's ml_5. */
  "ml-5"?: boolean | null | undefined;
  /** Matches Rust's ml_6. */
  "ml-6"?: boolean | null | undefined;
  /** Matches Rust's ml_8. */
  "ml-8"?: boolean | null | undefined;
  /** Matches Rust's ml_auto. */
  "ml-auto"?: boolean | null | undefined;
  /** Matches Rust's mr. */
  mr?: number | string | false | null | undefined;
  /** Matches Rust's mr_0. */
  "mr-0"?: boolean | null | undefined;
  /** Matches Rust's mr_1. */
  "mr-1"?: boolean | null | undefined;
  /** Matches Rust's mr_10. */
  "mr-10"?: boolean | null | undefined;
  /** Matches Rust's mr_12. */
  "mr-12"?: boolean | null | undefined;
  /** Matches Rust's mr_16. */
  "mr-16"?: boolean | null | undefined;
  /** Matches Rust's mr_2. */
  "mr-2"?: boolean | null | undefined;
  /** Matches Rust's mr_20. */
  "mr-20"?: boolean | null | undefined;
  /** Matches Rust's mr_24. */
  "mr-24"?: boolean | null | undefined;
  /** Matches Rust's mr_3. */
  "mr-3"?: boolean | null | undefined;
  /** Matches Rust's mr_32. */
  "mr-32"?: boolean | null | undefined;
  /** Matches Rust's mr_4. */
  "mr-4"?: boolean | null | undefined;
  /** Matches Rust's mr_5. */
  "mr-5"?: boolean | null | undefined;
  /** Matches Rust's mr_6. */
  "mr-6"?: boolean | null | undefined;
  /** Matches Rust's mr_8. */
  "mr-8"?: boolean | null | undefined;
  /** Matches Rust's mr_auto. */
  "mr-auto"?: boolean | null | undefined;
  /** Matches Rust's ms. */
  ms?: number | string | false | null | undefined;
  /** Matches Rust's mt. */
  mt?: number | string | false | null | undefined;
  /** Matches Rust's mt_0. */
  "mt-0"?: boolean | null | undefined;
  /** Matches Rust's mt_1. */
  "mt-1"?: boolean | null | undefined;
  /** Matches Rust's mt_10. */
  "mt-10"?: boolean | null | undefined;
  /** Matches Rust's mt_12. */
  "mt-12"?: boolean | null | undefined;
  /** Matches Rust's mt_16. */
  "mt-16"?: boolean | null | undefined;
  /** Matches Rust's mt_2. */
  "mt-2"?: boolean | null | undefined;
  /** Matches Rust's mt_20. */
  "mt-20"?: boolean | null | undefined;
  /** Matches Rust's mt_24. */
  "mt-24"?: boolean | null | undefined;
  /** Matches Rust's mt_3. */
  "mt-3"?: boolean | null | undefined;
  /** Matches Rust's mt_32. */
  "mt-32"?: boolean | null | undefined;
  /** Matches Rust's mt_4. */
  "mt-4"?: boolean | null | undefined;
  /** Matches Rust's mt_5. */
  "mt-5"?: boolean | null | undefined;
  /** Matches Rust's mt_6. */
  "mt-6"?: boolean | null | undefined;
  /** Matches Rust's mt_8. */
  "mt-8"?: boolean | null | undefined;
  /** Matches Rust's mt_auto. */
  "mt-auto"?: boolean | null | undefined;
  /** Matches Rust's mx. */
  mx?: number | string | false | null | undefined;
  /** Matches Rust's mx_0. */
  "mx-0"?: boolean | null | undefined;
  /** Matches Rust's mx_1. */
  "mx-1"?: boolean | null | undefined;
  /** Matches Rust's mx_10. */
  "mx-10"?: boolean | null | undefined;
  /** Matches Rust's mx_12. */
  "mx-12"?: boolean | null | undefined;
  /** Matches Rust's mx_16. */
  "mx-16"?: boolean | null | undefined;
  /** Matches Rust's mx_2. */
  "mx-2"?: boolean | null | undefined;
  /** Matches Rust's mx_20. */
  "mx-20"?: boolean | null | undefined;
  /** Matches Rust's mx_24. */
  "mx-24"?: boolean | null | undefined;
  /** Matches Rust's mx_3. */
  "mx-3"?: boolean | null | undefined;
  /** Matches Rust's mx_32. */
  "mx-32"?: boolean | null | undefined;
  /** Matches Rust's mx_4. */
  "mx-4"?: boolean | null | undefined;
  /** Matches Rust's mx_5. */
  "mx-5"?: boolean | null | undefined;
  /** Matches Rust's mx_6. */
  "mx-6"?: boolean | null | undefined;
  /** Matches Rust's mx_8. */
  "mx-8"?: boolean | null | undefined;
  /** Matches Rust's mx_auto. */
  "mx-auto"?: boolean | null | undefined;
  /** Matches Rust's my. */
  my?: number | string | false | null | undefined;
  /** Matches Rust's my_0. */
  "my-0"?: boolean | null | undefined;
  /** Matches Rust's my_1. */
  "my-1"?: boolean | null | undefined;
  /** Matches Rust's my_10. */
  "my-10"?: boolean | null | undefined;
  /** Matches Rust's my_12. */
  "my-12"?: boolean | null | undefined;
  /** Matches Rust's my_16. */
  "my-16"?: boolean | null | undefined;
  /** Matches Rust's my_2. */
  "my-2"?: boolean | null | undefined;
  /** Matches Rust's my_20. */
  "my-20"?: boolean | null | undefined;
  /** Matches Rust's my_24. */
  "my-24"?: boolean | null | undefined;
  /** Matches Rust's my_3. */
  "my-3"?: boolean | null | undefined;
  /** Matches Rust's my_32. */
  "my-32"?: boolean | null | undefined;
  /** Matches Rust's my_4. */
  "my-4"?: boolean | null | undefined;
  /** Matches Rust's my_5. */
  "my-5"?: boolean | null | undefined;
  /** Matches Rust's my_6. */
  "my-6"?: boolean | null | undefined;
  /** Matches Rust's my_8. */
  "my-8"?: boolean | null | undefined;
  /** Matches Rust's my_auto. */
  "my-auto"?: boolean | null | undefined;
  /** Matches Rust's overflow_hidden. */
  "overflow-hidden"?: boolean | null | undefined;
  /** Matches Rust's overflow_scroll. */
  "overflow-scroll"?: boolean | null | undefined;
  /** Matches Rust's overflow_x_scroll. */
  "overflow-x-scroll"?: boolean | null | undefined;
  /** Matches Rust's overflow_y_scroll. */
  "overflow-y-scroll"?: boolean | null | undefined;
  /** Matches Rust's p. */
  p?: number | string | false | null | undefined;
  /** Matches Rust's p_1. */
  "p-1"?: boolean | null | undefined;
  /** Matches Rust's p_2. */
  "p-2"?: boolean | null | undefined;
  /** Matches Rust's p_3. */
  "p-3"?: boolean | null | undefined;
  /** Matches Rust's p_4. */
  "p-4"?: boolean | null | undefined;
  /** Matches Rust's p_5. */
  "p-5"?: boolean | null | undefined;
  /** Matches Rust's p_6. */
  "p-6"?: boolean | null | undefined;
  /** Matches Rust's pe. */
  pe?: number | string | false | null | undefined;
  /** Matches Rust's ps. */
  ps?: number | string | false | null | undefined;
  /** Matches Rust's px. */
  px?: number | string | false | null | undefined;
  /** Matches Rust's px_2. */
  "px-2"?: boolean | null | undefined;
  /** Matches Rust's px_3. */
  "px-3"?: boolean | null | undefined;
  /** Matches Rust's px_4. */
  "px-4"?: boolean | null | undefined;
  /** Matches Rust's py. */
  py?: number | string | false | null | undefined;
  /** Matches Rust's py_1. */
  "py-1"?: boolean | null | undefined;
  /** Matches Rust's py_2. */
  "py-2"?: boolean | null | undefined;
  /** Matches Rust's relative. */
  relative?: boolean | null | undefined;
  /** Matches Rust's rounded. */
  rounded?: number | RoundedPreset | false | null | undefined;
  /** Matches Rust's rounded_2xl. */
  "rounded-2xl"?: boolean | null | undefined;
  /** Matches Rust's rounded_b. */
  "rounded-b"?: number | RoundedPreset | false | null | undefined;
  /** Matches Rust's rounded_bl. */
  "rounded-bl"?: number | RoundedPreset | false | null | undefined;
  /** Matches Rust's rounded_br. */
  "rounded-br"?: number | RoundedPreset | false | null | undefined;
  /** Matches Rust's rounded_full. */
  "rounded-full"?: boolean | null | undefined;
  /** Matches Rust's rounded_l. */
  "rounded-l"?: number | RoundedPreset | false | null | undefined;
  /** Matches Rust's rounded_lg. */
  "rounded-lg"?: boolean | null | undefined;
  /** Matches Rust's rounded_md. */
  "rounded-md"?: boolean | null | undefined;
  /** Matches Rust's rounded_r. */
  "rounded-r"?: number | RoundedPreset | false | null | undefined;
  /** Matches Rust's rounded_sm. */
  "rounded-sm"?: boolean | null | undefined;
  /** Matches Rust's rounded_t. */
  "rounded-t"?: number | RoundedPreset | false | null | undefined;
  /** Matches Rust's rounded_tl. */
  "rounded-tl"?: number | RoundedPreset | false | null | undefined;
  /** Matches Rust's rounded_tr. */
  "rounded-tr"?: number | RoundedPreset | false | null | undefined;
  /** Matches Rust's rounded_xl. */
  "rounded-xl"?: boolean | null | undefined;
  /** Matches Rust's row_end. */
  "row-end"?: number | string | false | null | undefined;
  /** Matches Rust's row_end_auto. */
  "row-end-auto"?: boolean | null | undefined;
  /** Matches Rust's row_span. */
  "row-span"?: number | string | false | null | undefined;
  /** Matches Rust's row_span_full. */
  "row-span-full"?: boolean | null | undefined;
  /** Matches Rust's row_start. */
  "row-start"?: number | string | false | null | undefined;
  /** Matches Rust's row_start_auto. */
  "row-start-auto"?: boolean | null | undefined;
  /** Matches Rust's rtl. */
  rtl?: boolean | null | undefined;
  /** Matches Rust's selectable. */
  selectable?: boolean | null | undefined;
  /** Matches Rust's self_baseline. */
  "self-baseline"?: boolean | null | undefined;
  /** Matches Rust's self_center. */
  "self-center"?: boolean | null | undefined;
  /** Matches Rust's self_end. */
  "self-end"?: boolean | null | undefined;
  /** Matches Rust's self_flex_end. */
  "self-flex-end"?: boolean | null | undefined;
  /** Matches Rust's self_flex_start. */
  "self-flex-start"?: boolean | null | undefined;
  /** Matches Rust's self_start. */
  "self-start"?: boolean | null | undefined;
  /** Matches Rust's self_stretch. */
  "self-stretch"?: boolean | null | undefined;
  /** Matches Rust's size; pass [width, height]. */
  size?: readonly [width: number | string, height: number | string] | false | null | undefined;
  /** Matches Rust's size_full. */
  "size-full"?: boolean | null | undefined;
  /** Matches Rust's snap_align. */
  "snap-align"?: "none" | "start" | "center" | "end" | false | null | undefined;
  /** Matches Rust's snap_stop_always. */
  "snap-stop-always"?: boolean | null | undefined;
  /** Matches Rust's sticky. */
  "position-sticky"?: boolean | null | undefined;
  /** Matches Rust's sticky_bottom. */
  "sticky-bottom"?: number | string | false | null | undefined;
  /** Matches Rust's sticky_left. */
  "sticky-left"?: number | string | false | null | undefined;
  /** Matches Rust's sticky_right. */
  "sticky-right"?: number | string | false | null | undefined;
  /** Matches Rust's sticky_top. */
  "sticky-top"?: number | string | false | null | undefined;
  /** Matches Rust's text_2xl. */
  "text-2xl"?: boolean | null | undefined;
  /** Matches Rust's text_3xl. */
  "text-3xl"?: boolean | null | undefined;
  /** Matches Rust's text_base. */
  "text-base"?: boolean | null | undefined;
  /** Matches Rust's text_center. */
  "text-center"?: boolean | null | undefined;
  /** Matches Rust's text_ellipsis. */
  "text-ellipsis"?: boolean | null | undefined;
  /** Matches Rust's text_ellipsis_middle. */
  "text-ellipsis-middle"?: boolean | null | undefined;
  /** Matches Rust's text_ellipsis_start. */
  "text-ellipsis-start"?: boolean | null | undefined;
  /** Matches Rust's text_end. */
  "text-end"?: boolean | null | undefined;
  /** Matches Rust's text_justify. */
  "text-justify"?: boolean | null | undefined;
  /** Matches Rust's text_left. */
  "text-left"?: boolean | null | undefined;
  /** Matches Rust's text_lg. */
  "text-lg"?: boolean | null | undefined;
  /** Matches Rust's text_right. */
  "text-right"?: boolean | null | undefined;
  /** Matches Rust's text_sm. */
  "text-sm"?: boolean | null | undefined;
  /** Matches Rust's text_start. */
  "text-start"?: boolean | null | undefined;
  /** Matches Rust's text_xl. */
  "text-xl"?: boolean | null | undefined;
  /** Matches Rust's text_xs. */
  "text-xs"?: boolean | null | undefined;
  /** Matches Rust's truncate. */
  truncate?: boolean | null | undefined;
  /** Matches Rust's user_select_none. */
  "user-select-none"?: boolean | null | undefined;
  /** Matches Rust's user_select_text. */
  "user-select-text"?: boolean | null | undefined;
  /** Matches Rust's visible. */
  visible?: boolean | null | undefined;
  /** Matches Rust's w. */
  w?: number | string | false | null | undefined;
  /** Matches Rust's w_fraction. */
  "w-fraction"?: number | false | null | undefined;
  /** Matches Rust's w_full. */
  "w-full"?: boolean | null | undefined;
  /** Matches Rust's whitespace_normal. */
  "whitespace-normal"?: boolean | null | undefined;
  /** Matches Rust's whitespace_nowrap. */
  "whitespace-nowrap"?: boolean | null | undefined;
}

export type HelperDeclaration = Record<string, unknown>;
export interface StyleHelperDefinition {
  parameters: number;
  fields: readonly string[];
  resolve: (value: unknown) => HelperDeclaration;
}

export const styleHelpers: Record<string, StyleHelperDefinition> = {
  absolute: { parameters: 0, fields: ["position"], resolve: (value) => ({ position: "absolute" }) },
  "app-region-drag": {
    parameters: 0,
    fields: ["appRegion"],
    resolve: (value) => ({ appRegion: "drag" }),
  },
  "app-region-no-drag": {
    parameters: 0,
    fields: ["appRegion"],
    resolve: (value) => ({ appRegion: "no-drag" }),
  },
  "aspect-square": {
    parameters: 0,
    fields: ["aspectRatio"],
    resolve: (value) => ({ aspectRatio: 1 }),
  },
  block: { parameters: 0, fields: ["display"], resolve: (value) => ({ display: "block" }) },
  "border-dashed": {
    parameters: 0,
    fields: ["borderStyle"],
    resolve: (value) => ({ borderStyle: "dashed" }),
  },
  "border-dotted": {
    parameters: 0,
    fields: ["borderStyle"],
    resolve: (value) => ({ borderStyle: "dotted" }),
  },
  "border-e": {
    parameters: 1,
    fields: ["borderEndWidth"],
    resolve: (value) => ({ borderEndWidth: value }),
  },
  "border-s": {
    parameters: 1,
    fields: ["borderStartWidth"],
    resolve: (value) => ({ borderStartWidth: value }),
  },
  "border-solid": {
    parameters: 0,
    fields: ["borderStyle"],
    resolve: (value) => ({ borderStyle: "solid" }),
  },
  "col-end": {
    parameters: 1,
    fields: ["gridColumnEnd"],
    resolve: (value) => ({ gridColumnEnd: value }),
  },
  "col-end-auto": {
    parameters: 0,
    fields: ["gridColumnEnd"],
    resolve: (value) => ({ gridColumnEnd: 0 }),
  },
  "col-span": {
    parameters: 1,
    fields: ["gridColumnStart", "gridColumnEnd", "gridColumnSpan"],
    resolve: (value) => ({ gridColumnStart: null, gridColumnEnd: null, gridColumnSpan: value }),
  },
  "col-span-full": {
    parameters: 0,
    fields: ["gridColumnSpan", "gridColumnStart", "gridColumnEnd"],
    resolve: (value) => ({ gridColumnSpan: null, gridColumnStart: 1, gridColumnEnd: -1 }),
  },
  "col-start": {
    parameters: 1,
    fields: ["gridColumnStart"],
    resolve: (value) => ({ gridColumnStart: value }),
  },
  "col-start-auto": {
    parameters: 0,
    fields: ["gridColumnStart"],
    resolve: (value) => ({ gridColumnStart: 0 }),
  },
  "content-around": {
    parameters: 0,
    fields: ["alignContent"],
    resolve: (value) => ({ alignContent: "space-around" }),
  },
  "content-between": {
    parameters: 0,
    fields: ["alignContent"],
    resolve: (value) => ({ alignContent: "space-between" }),
  },
  "content-center": {
    parameters: 0,
    fields: ["alignContent"],
    resolve: (value) => ({ alignContent: "center" }),
  },
  "content-end": {
    parameters: 0,
    fields: ["alignContent"],
    resolve: (value) => ({ alignContent: "flex-end" }),
  },
  "content-evenly": {
    parameters: 0,
    fields: ["alignContent"],
    resolve: (value) => ({ alignContent: "space-evenly" }),
  },
  "content-normal": {
    parameters: 0,
    fields: ["alignContent"],
    resolve: (value) => ({ alignContent: "normal" }),
  },
  "content-start": {
    parameters: 0,
    fields: ["alignContent"],
    resolve: (value) => ({ alignContent: "flex-start" }),
  },
  "content-stretch": {
    parameters: 0,
    fields: ["alignContent"],
    resolve: (value) => ({ alignContent: "stretch" }),
  },
  "cursor-alias": { parameters: 0, fields: ["cursor"], resolve: (value) => ({ cursor: "alias" }) },
  "cursor-col-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "col-resize" }),
  },
  "cursor-context-menu": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "context-menu" }),
  },
  "cursor-copy": { parameters: 0, fields: ["cursor"], resolve: (value) => ({ cursor: "copy" }) },
  "cursor-crosshair": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "crosshair" }),
  },
  "cursor-default": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "default" }),
  },
  "cursor-e-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "e-resize" }),
  },
  "cursor-ew-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "ew-resize" }),
  },
  "cursor-grab": { parameters: 0, fields: ["cursor"], resolve: (value) => ({ cursor: "grab" }) },
  "cursor-grabbing": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "grabbing" }),
  },
  "cursor-move": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "grabbing" }),
  },
  "cursor-n-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "n-resize" }),
  },
  "cursor-nesw-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "nesw-resize" }),
  },
  "cursor-no-drop": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "not-allowed" }),
  },
  "cursor-not-allowed": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "not-allowed" }),
  },
  "cursor-ns-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "ns-resize" }),
  },
  "cursor-nwse-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "nwse-resize" }),
  },
  "cursor-pointer": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "pointer" }),
  },
  "cursor-row-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "row-resize" }),
  },
  "cursor-s-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "s-resize" }),
  },
  "cursor-text": { parameters: 0, fields: ["cursor"], resolve: (value) => ({ cursor: "text" }) },
  "cursor-vertical-text": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "vertical-text" }),
  },
  "cursor-w-resize": {
    parameters: 0,
    fields: ["cursor"],
    resolve: (value) => ({ cursor: "w-resize" }),
  },
  flex: { parameters: 0, fields: ["display"], resolve: (value) => ({ display: "flex" }) },
  "flex-1": {
    parameters: 0,
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: (value) => ({ flexGrow: 1, flexShrink: 1, flexBasis: 0 }),
  },
  "flex-auto": {
    parameters: 0,
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: (value) => ({ flexGrow: 1, flexShrink: 1, flexBasis: "auto" }),
  },
  "flex-basis-auto": {
    parameters: 0,
    fields: ["flexBasis"],
    resolve: (value) => ({ flexBasis: "auto" }),
  },
  "flex-col": {
    parameters: 0,
    fields: ["display", "flexDirection"],
    resolve: (value) => ({ display: "flex", flexDirection: "column" }),
  },
  "flex-col-reverse": {
    parameters: 0,
    fields: ["display", "flexDirection"],
    resolve: (value) => ({ display: "flex", flexDirection: "column-reverse" }),
  },
  "flex-grow-0": { parameters: 0, fields: ["flexGrow"], resolve: (value) => ({ flexGrow: 0 }) },
  "flex-grow-1": { parameters: 0, fields: ["flexGrow"], resolve: (value) => ({ flexGrow: 1 }) },
  "flex-initial": {
    parameters: 0,
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: (value) => ({ flexGrow: 0, flexShrink: 1, flexBasis: "auto" }),
  },
  "flex-none": {
    parameters: 0,
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: (value) => ({ flexGrow: 0, flexShrink: 0, flexBasis: "auto" }),
  },
  "flex-nowrap": {
    parameters: 0,
    fields: ["flexWrap"],
    resolve: (value) => ({ flexWrap: "nowrap" }),
  },
  "flex-row": {
    parameters: 0,
    fields: ["display", "flexDirection"],
    resolve: (value) => ({ display: "flex", flexDirection: "row" }),
  },
  "flex-row-reverse": {
    parameters: 0,
    fields: ["display", "flexDirection"],
    resolve: (value) => ({ display: "flex", flexDirection: "row-reverse" }),
  },
  "flex-shrink-0": {
    parameters: 0,
    fields: ["flexShrink"],
    resolve: (value) => ({ flexShrink: 0 }),
  },
  "flex-shrink-1": {
    parameters: 0,
    fields: ["flexShrink"],
    resolve: (value) => ({ flexShrink: 1 }),
  },
  "flex-wrap": { parameters: 0, fields: ["flexWrap"], resolve: (value) => ({ flexWrap: "wrap" }) },
  "flex-wrap-reverse": {
    parameters: 0,
    fields: ["flexWrap"],
    resolve: (value) => ({ flexWrap: "wrap-reverse" }),
  },
  "font-bold": { parameters: 0, fields: ["fontWeight"], resolve: (value) => ({ fontWeight: 700 }) },
  "font-medium": {
    parameters: 0,
    fields: ["fontWeight"],
    resolve: (value) => ({ fontWeight: 500 }),
  },
  "font-normal": {
    parameters: 0,
    fields: ["fontWeight"],
    resolve: (value) => ({ fontWeight: 400 }),
  },
  "font-semibold": {
    parameters: 0,
    fields: ["fontWeight"],
    resolve: (value) => ({ fontWeight: 600 }),
  },
  "gap-1": { parameters: 0, fields: ["gap"], resolve: (value) => ({ gap: 4 }) },
  "gap-2": { parameters: 0, fields: ["gap"], resolve: (value) => ({ gap: 8 }) },
  "gap-3": { parameters: 0, fields: ["gap"], resolve: (value) => ({ gap: 12 }) },
  "gap-4": { parameters: 0, fields: ["gap"], resolve: (value) => ({ gap: 16 }) },
  "gap-5": { parameters: 0, fields: ["gap"], resolve: (value) => ({ gap: 20 }) },
  "gap-6": { parameters: 0, fields: ["gap"], resolve: (value) => ({ gap: 24 }) },
  "gap-x": { parameters: 1, fields: ["columnGap"], resolve: (value) => ({ columnGap: value }) },
  "gap-x-0": { parameters: 0, fields: ["columnGap"], resolve: (value) => ({ columnGap: 0 }) },
  "gap-x-1": { parameters: 0, fields: ["columnGap"], resolve: (value) => ({ columnGap: 4 }) },
  "gap-x-2": { parameters: 0, fields: ["columnGap"], resolve: (value) => ({ columnGap: 8 }) },
  "gap-x-3": { parameters: 0, fields: ["columnGap"], resolve: (value) => ({ columnGap: 12 }) },
  "gap-x-4": { parameters: 0, fields: ["columnGap"], resolve: (value) => ({ columnGap: 16 }) },
  "gap-x-5": { parameters: 0, fields: ["columnGap"], resolve: (value) => ({ columnGap: 20 }) },
  "gap-x-6": { parameters: 0, fields: ["columnGap"], resolve: (value) => ({ columnGap: 24 }) },
  "gap-y": { parameters: 1, fields: ["rowGap"], resolve: (value) => ({ rowGap: value }) },
  "gap-y-0": { parameters: 0, fields: ["rowGap"], resolve: (value) => ({ rowGap: 0 }) },
  "gap-y-1": { parameters: 0, fields: ["rowGap"], resolve: (value) => ({ rowGap: 4 }) },
  "gap-y-2": { parameters: 0, fields: ["rowGap"], resolve: (value) => ({ rowGap: 8 }) },
  "gap-y-3": { parameters: 0, fields: ["rowGap"], resolve: (value) => ({ rowGap: 12 }) },
  "gap-y-4": { parameters: 0, fields: ["rowGap"], resolve: (value) => ({ rowGap: 16 }) },
  "gap-y-5": { parameters: 0, fields: ["rowGap"], resolve: (value) => ({ rowGap: 20 }) },
  "gap-y-6": { parameters: 0, fields: ["rowGap"], resolve: (value) => ({ rowGap: 24 }) },
  grid: { parameters: 0, fields: ["display"], resolve: (value) => ({ display: "grid" }) },
  "grid-cols": {
    parameters: 1,
    fields: ["gridTemplateColumns"],
    resolve: (value) => ({ gridTemplateColumns: gridTracks(value, "0", "1fr") }),
  },
  "grid-cols-max-content": {
    parameters: 1,
    fields: ["gridTemplateColumns"],
    resolve: (value) => ({ gridTemplateColumns: gridTracks(value, "0", "max-content") }),
  },
  "grid-cols-min-content": {
    parameters: 1,
    fields: ["gridTemplateColumns"],
    resolve: (value) => ({ gridTemplateColumns: gridTracks(value, "min-content", "1fr") }),
  },
  "grid-flow-col": {
    parameters: 0,
    fields: ["gridAutoFlow"],
    resolve: (value) => ({ gridAutoFlow: "column" }),
  },
  "grid-flow-col-dense": {
    parameters: 0,
    fields: ["gridAutoFlow"],
    resolve: (value) => ({ gridAutoFlow: "column dense" }),
  },
  "grid-flow-row": {
    parameters: 0,
    fields: ["gridAutoFlow"],
    resolve: (value) => ({ gridAutoFlow: "row" }),
  },
  "grid-flow-row-dense": {
    parameters: 0,
    fields: ["gridAutoFlow"],
    resolve: (value) => ({ gridAutoFlow: "row dense" }),
  },
  "grid-rows": {
    parameters: 1,
    fields: ["gridTemplateRows"],
    resolve: (value) => ({ gridTemplateRows: gridTracks(value, "0", "1fr") }),
  },
  "grid-rows-max-content": {
    parameters: 1,
    fields: ["gridTemplateRows"],
    resolve: (value) => ({ gridTemplateRows: gridTracks(value, "0", "max-content") }),
  },
  "grid-rows-min-content": {
    parameters: 1,
    fields: ["gridTemplateRows"],
    resolve: (value) => ({ gridTemplateRows: gridTracks(value, "min-content", "1fr") }),
  },
  h: { parameters: 1, fields: ["height"], resolve: (value) => ({ height: value }) },
  "h-10": { parameters: 0, fields: ["height"], resolve: (value) => ({ height: 40 }) },
  "h-12": { parameters: 0, fields: ["height"], resolve: (value) => ({ height: 48 }) },
  "h-8": { parameters: 0, fields: ["height"], resolve: (value) => ({ height: 32 }) },
  "h-fraction": {
    parameters: 1,
    fields: ["height"],
    resolve: (value) => ({ height: fraction(value) }),
  },
  "h-full": { parameters: 0, fields: ["height"], resolve: (value) => ({ height: "100%" }) },
  hidden: { parameters: 0, fields: ["display"], resolve: (value) => ({ display: "none" }) },
  "inset-0": {
    parameters: 0,
    fields: ["top", "right", "bottom", "left"],
    resolve: (value) => ({ top: 0, right: 0, bottom: 0, left: 0 }),
  },
  invisible: {
    parameters: 0,
    fields: ["visibility"],
    resolve: (value) => ({ visibility: "hidden" }),
  },
  "items-baseline": {
    parameters: 0,
    fields: ["alignItems"],
    resolve: (value) => ({ alignItems: "baseline" }),
  },
  "items-center": {
    parameters: 0,
    fields: ["alignItems"],
    resolve: (value) => ({ alignItems: "center" }),
  },
  "items-end": {
    parameters: 0,
    fields: ["alignItems"],
    resolve: (value) => ({ alignItems: "flex-end" }),
  },
  "items-start": {
    parameters: 0,
    fields: ["alignItems"],
    resolve: (value) => ({ alignItems: "flex-start" }),
  },
  "items-stretch": {
    parameters: 0,
    fields: ["alignItems"],
    resolve: (value) => ({ alignItems: "stretch" }),
  },
  "justify-around": {
    parameters: 0,
    fields: ["justifyContent"],
    resolve: (value) => ({ justifyContent: "space-around" }),
  },
  "justify-between": {
    parameters: 0,
    fields: ["justifyContent"],
    resolve: (value) => ({ justifyContent: "space-between" }),
  },
  "justify-center": {
    parameters: 0,
    fields: ["justifyContent"],
    resolve: (value) => ({ justifyContent: "center" }),
  },
  "justify-end": {
    parameters: 0,
    fields: ["justifyContent"],
    resolve: (value) => ({ justifyContent: "end" }),
  },
  "justify-evenly": {
    parameters: 0,
    fields: ["justifyContent"],
    resolve: (value) => ({ justifyContent: "space-evenly" }),
  },
  "justify-start": {
    parameters: 0,
    fields: ["justifyContent"],
    resolve: (value) => ({ justifyContent: "start" }),
  },
  ltr: { parameters: 0, fields: ["direction"], resolve: (value) => ({ direction: "ltr" }) },
  m: {
    parameters: 1,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({
      marginTop: value,
      marginRight: value,
      marginBottom: value,
      marginLeft: value,
    }),
  },
  "m-0": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 0, marginRight: 0, marginBottom: 0, marginLeft: 0 }),
  },
  "m-1": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 4, marginRight: 4, marginBottom: 4, marginLeft: 4 }),
  },
  "m-10": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 40, marginRight: 40, marginBottom: 40, marginLeft: 40 }),
  },
  "m-12": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 48, marginRight: 48, marginBottom: 48, marginLeft: 48 }),
  },
  "m-16": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 64, marginRight: 64, marginBottom: 64, marginLeft: 64 }),
  },
  "m-2": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 8, marginRight: 8, marginBottom: 8, marginLeft: 8 }),
  },
  "m-20": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 80, marginRight: 80, marginBottom: 80, marginLeft: 80 }),
  },
  "m-24": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 96, marginRight: 96, marginBottom: 96, marginLeft: 96 }),
  },
  "m-3": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 12, marginRight: 12, marginBottom: 12, marginLeft: 12 }),
  },
  "m-32": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 128, marginRight: 128, marginBottom: 128, marginLeft: 128 }),
  },
  "m-4": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 16, marginRight: 16, marginBottom: 16, marginLeft: 16 }),
  },
  "m-5": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 20, marginRight: 20, marginBottom: 20, marginLeft: 20 }),
  },
  "m-6": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 24, marginRight: 24, marginBottom: 24, marginLeft: 24 }),
  },
  "m-8": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({ marginTop: 32, marginRight: 32, marginBottom: 32, marginLeft: 32 }),
  },
  "m-auto": {
    parameters: 0,
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: (value) => ({
      marginTop: "auto",
      marginRight: "auto",
      marginBottom: "auto",
      marginLeft: "auto",
    }),
  },
  "max-h": { parameters: 1, fields: ["maxHeight"], resolve: (value) => ({ maxHeight: value }) },
  "max-w": { parameters: 1, fields: ["maxWidth"], resolve: (value) => ({ maxWidth: value }) },
  mb: { parameters: 1, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: value }) },
  "mb-0": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 0 }) },
  "mb-1": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 4 }) },
  "mb-10": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 40 }) },
  "mb-12": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 48 }) },
  "mb-16": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 64 }) },
  "mb-2": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 8 }) },
  "mb-20": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 80 }) },
  "mb-24": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 96 }) },
  "mb-3": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 12 }) },
  "mb-32": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 128 }) },
  "mb-4": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 16 }) },
  "mb-5": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 20 }) },
  "mb-6": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 24 }) },
  "mb-8": { parameters: 0, fields: ["marginBottom"], resolve: (value) => ({ marginBottom: 32 }) },
  "mb-auto": {
    parameters: 0,
    fields: ["marginBottom"],
    resolve: (value) => ({ marginBottom: "auto" }),
  },
  me: { parameters: 1, fields: ["marginEnd"], resolve: (value) => ({ marginEnd: value }) },
  "min-h": { parameters: 1, fields: ["minHeight"], resolve: (value) => ({ minHeight: value }) },
  "min-w": { parameters: 1, fields: ["minWidth"], resolve: (value) => ({ minWidth: value }) },
  ml: { parameters: 1, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: value }) },
  "ml-0": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 0 }) },
  "ml-1": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 4 }) },
  "ml-10": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 40 }) },
  "ml-12": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 48 }) },
  "ml-16": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 64 }) },
  "ml-2": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 8 }) },
  "ml-20": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 80 }) },
  "ml-24": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 96 }) },
  "ml-3": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 12 }) },
  "ml-32": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 128 }) },
  "ml-4": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 16 }) },
  "ml-5": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 20 }) },
  "ml-6": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 24 }) },
  "ml-8": { parameters: 0, fields: ["marginLeft"], resolve: (value) => ({ marginLeft: 32 }) },
  "ml-auto": {
    parameters: 0,
    fields: ["marginLeft"],
    resolve: (value) => ({ marginLeft: "auto" }),
  },
  mr: { parameters: 1, fields: ["marginRight"], resolve: (value) => ({ marginRight: value }) },
  "mr-0": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 0 }) },
  "mr-1": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 4 }) },
  "mr-10": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 40 }) },
  "mr-12": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 48 }) },
  "mr-16": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 64 }) },
  "mr-2": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 8 }) },
  "mr-20": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 80 }) },
  "mr-24": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 96 }) },
  "mr-3": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 12 }) },
  "mr-32": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 128 }) },
  "mr-4": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 16 }) },
  "mr-5": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 20 }) },
  "mr-6": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 24 }) },
  "mr-8": { parameters: 0, fields: ["marginRight"], resolve: (value) => ({ marginRight: 32 }) },
  "mr-auto": {
    parameters: 0,
    fields: ["marginRight"],
    resolve: (value) => ({ marginRight: "auto" }),
  },
  ms: { parameters: 1, fields: ["marginStart"], resolve: (value) => ({ marginStart: value }) },
  mt: { parameters: 1, fields: ["marginTop"], resolve: (value) => ({ marginTop: value }) },
  "mt-0": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 0 }) },
  "mt-1": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 4 }) },
  "mt-10": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 40 }) },
  "mt-12": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 48 }) },
  "mt-16": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 64 }) },
  "mt-2": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 8 }) },
  "mt-20": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 80 }) },
  "mt-24": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 96 }) },
  "mt-3": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 12 }) },
  "mt-32": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 128 }) },
  "mt-4": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 16 }) },
  "mt-5": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 20 }) },
  "mt-6": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 24 }) },
  "mt-8": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: 32 }) },
  "mt-auto": { parameters: 0, fields: ["marginTop"], resolve: (value) => ({ marginTop: "auto" }) },
  mx: {
    parameters: 1,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: value, marginRight: value }),
  },
  "mx-0": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 0, marginRight: 0 }),
  },
  "mx-1": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 4, marginRight: 4 }),
  },
  "mx-10": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 40, marginRight: 40 }),
  },
  "mx-12": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 48, marginRight: 48 }),
  },
  "mx-16": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 64, marginRight: 64 }),
  },
  "mx-2": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 8, marginRight: 8 }),
  },
  "mx-20": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 80, marginRight: 80 }),
  },
  "mx-24": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 96, marginRight: 96 }),
  },
  "mx-3": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 12, marginRight: 12 }),
  },
  "mx-32": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 128, marginRight: 128 }),
  },
  "mx-4": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 16, marginRight: 16 }),
  },
  "mx-5": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 20, marginRight: 20 }),
  },
  "mx-6": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 24, marginRight: 24 }),
  },
  "mx-8": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: 32, marginRight: 32 }),
  },
  "mx-auto": {
    parameters: 0,
    fields: ["marginLeft", "marginRight"],
    resolve: (value) => ({ marginLeft: "auto", marginRight: "auto" }),
  },
  my: {
    parameters: 1,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: value, marginBottom: value }),
  },
  "my-0": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 0, marginBottom: 0 }),
  },
  "my-1": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 4, marginBottom: 4 }),
  },
  "my-10": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 40, marginBottom: 40 }),
  },
  "my-12": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 48, marginBottom: 48 }),
  },
  "my-16": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 64, marginBottom: 64 }),
  },
  "my-2": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 8, marginBottom: 8 }),
  },
  "my-20": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 80, marginBottom: 80 }),
  },
  "my-24": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 96, marginBottom: 96 }),
  },
  "my-3": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 12, marginBottom: 12 }),
  },
  "my-32": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 128, marginBottom: 128 }),
  },
  "my-4": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 16, marginBottom: 16 }),
  },
  "my-5": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 20, marginBottom: 20 }),
  },
  "my-6": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 24, marginBottom: 24 }),
  },
  "my-8": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: 32, marginBottom: 32 }),
  },
  "my-auto": {
    parameters: 0,
    fields: ["marginTop", "marginBottom"],
    resolve: (value) => ({ marginTop: "auto", marginBottom: "auto" }),
  },
  "overflow-hidden": {
    parameters: 0,
    fields: ["overflowX", "overflowY"],
    resolve: (value) => ({ overflowX: "hidden", overflowY: "hidden" }),
  },
  "overflow-scroll": {
    parameters: 0,
    fields: ["overflowX", "overflowY"],
    resolve: (value) => ({ overflowX: "scroll", overflowY: "scroll" }),
  },
  "overflow-x-scroll": {
    parameters: 0,
    fields: ["overflowX", "overflowY"],
    resolve: (value) => ({ overflowX: "scroll", overflowY: "hidden" }),
  },
  "overflow-y-scroll": {
    parameters: 0,
    fields: ["overflowX", "overflowY"],
    resolve: (value) => ({ overflowX: "hidden", overflowY: "scroll" }),
  },
  p: {
    parameters: 1,
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: (value) => ({
      paddingTop: value,
      paddingRight: value,
      paddingBottom: value,
      paddingLeft: value,
    }),
  },
  "p-1": {
    parameters: 0,
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: (value) => ({ paddingTop: 4, paddingRight: 4, paddingBottom: 4, paddingLeft: 4 }),
  },
  "p-2": {
    parameters: 0,
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: (value) => ({ paddingTop: 8, paddingRight: 8, paddingBottom: 8, paddingLeft: 8 }),
  },
  "p-3": {
    parameters: 0,
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: (value) => ({ paddingTop: 12, paddingRight: 12, paddingBottom: 12, paddingLeft: 12 }),
  },
  "p-4": {
    parameters: 0,
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: (value) => ({ paddingTop: 16, paddingRight: 16, paddingBottom: 16, paddingLeft: 16 }),
  },
  "p-5": {
    parameters: 0,
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: (value) => ({ paddingTop: 20, paddingRight: 20, paddingBottom: 20, paddingLeft: 20 }),
  },
  "p-6": {
    parameters: 0,
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: (value) => ({ paddingTop: 24, paddingRight: 24, paddingBottom: 24, paddingLeft: 24 }),
  },
  pe: { parameters: 1, fields: ["paddingEnd"], resolve: (value) => ({ paddingEnd: value }) },
  ps: { parameters: 1, fields: ["paddingStart"], resolve: (value) => ({ paddingStart: value }) },
  px: {
    parameters: 1,
    fields: ["paddingLeft", "paddingRight"],
    resolve: (value) => ({ paddingLeft: value, paddingRight: value }),
  },
  "px-2": {
    parameters: 0,
    fields: ["paddingLeft", "paddingRight"],
    resolve: (value) => ({ paddingLeft: 8, paddingRight: 8 }),
  },
  "px-3": {
    parameters: 0,
    fields: ["paddingLeft", "paddingRight"],
    resolve: (value) => ({ paddingLeft: 12, paddingRight: 12 }),
  },
  "px-4": {
    parameters: 0,
    fields: ["paddingLeft", "paddingRight"],
    resolve: (value) => ({ paddingLeft: 16, paddingRight: 16 }),
  },
  py: {
    parameters: 1,
    fields: ["paddingTop", "paddingBottom"],
    resolve: (value) => ({ paddingTop: value, paddingBottom: value }),
  },
  "py-1": {
    parameters: 0,
    fields: ["paddingTop", "paddingBottom"],
    resolve: (value) => ({ paddingTop: 4, paddingBottom: 4 }),
  },
  "py-2": {
    parameters: 0,
    fields: ["paddingTop", "paddingBottom"],
    resolve: (value) => ({ paddingTop: 8, paddingBottom: 8 }),
  },
  relative: { parameters: 0, fields: ["position"], resolve: (value) => ({ position: "relative" }) },
  rounded: {
    parameters: 1,
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: (value) => ({
      borderRadius: value,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-2xl": {
    parameters: 0,
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: (value) => ({
      borderRadius: 16,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-b": {
    parameters: 1,
    fields: ["borderBottomLeftRadius", "borderBottomRightRadius"],
    resolve: (value) => ({ borderBottomLeftRadius: value, borderBottomRightRadius: value }),
  },
  "rounded-bl": {
    parameters: 1,
    fields: ["borderBottomLeftRadius"],
    resolve: (value) => ({ borderBottomLeftRadius: value }),
  },
  "rounded-br": {
    parameters: 1,
    fields: ["borderBottomRightRadius"],
    resolve: (value) => ({ borderBottomRightRadius: value }),
  },
  "rounded-full": {
    parameters: 0,
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: (value) => ({
      borderRadius: 4096,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-l": {
    parameters: 1,
    fields: ["borderTopLeftRadius", "borderBottomLeftRadius"],
    resolve: (value) => ({ borderTopLeftRadius: value, borderBottomLeftRadius: value }),
  },
  "rounded-lg": {
    parameters: 0,
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: (value) => ({
      borderRadius: 8,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-md": {
    parameters: 0,
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: (value) => ({
      borderRadius: 6,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-r": {
    parameters: 1,
    fields: ["borderTopRightRadius", "borderBottomRightRadius"],
    resolve: (value) => ({ borderTopRightRadius: value, borderBottomRightRadius: value }),
  },
  "rounded-sm": {
    parameters: 0,
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: (value) => ({
      borderRadius: 4,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "rounded-t": {
    parameters: 1,
    fields: ["borderTopLeftRadius", "borderTopRightRadius"],
    resolve: (value) => ({ borderTopLeftRadius: value, borderTopRightRadius: value }),
  },
  "rounded-tl": {
    parameters: 1,
    fields: ["borderTopLeftRadius"],
    resolve: (value) => ({ borderTopLeftRadius: value }),
  },
  "rounded-tr": {
    parameters: 1,
    fields: ["borderTopRightRadius"],
    resolve: (value) => ({ borderTopRightRadius: value }),
  },
  "rounded-xl": {
    parameters: 0,
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: (value) => ({
      borderRadius: 12,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  "row-end": { parameters: 1, fields: ["gridRowEnd"], resolve: (value) => ({ gridRowEnd: value }) },
  "row-end-auto": {
    parameters: 0,
    fields: ["gridRowEnd"],
    resolve: (value) => ({ gridRowEnd: 0 }),
  },
  "row-span": {
    parameters: 1,
    fields: ["gridRowStart", "gridRowEnd", "gridRowSpan"],
    resolve: (value) => ({ gridRowStart: null, gridRowEnd: null, gridRowSpan: value }),
  },
  "row-span-full": {
    parameters: 0,
    fields: ["gridRowSpan", "gridRowStart", "gridRowEnd"],
    resolve: (value) => ({ gridRowSpan: null, gridRowStart: 1, gridRowEnd: -1 }),
  },
  "row-start": {
    parameters: 1,
    fields: ["gridRowStart"],
    resolve: (value) => ({ gridRowStart: value }),
  },
  "row-start-auto": {
    parameters: 0,
    fields: ["gridRowStart"],
    resolve: (value) => ({ gridRowStart: 0 }),
  },
  rtl: { parameters: 0, fields: ["direction"], resolve: (value) => ({ direction: "rtl" }) },
  selectable: {
    parameters: 0,
    fields: ["userSelect"],
    resolve: (value) => ({ userSelect: "text" }),
  },
  "self-baseline": {
    parameters: 0,
    fields: ["alignSelf"],
    resolve: (value) => ({ alignSelf: "baseline" }),
  },
  "self-center": {
    parameters: 0,
    fields: ["alignSelf"],
    resolve: (value) => ({ alignSelf: "center" }),
  },
  "self-end": { parameters: 0, fields: ["alignSelf"], resolve: (value) => ({ alignSelf: "end" }) },
  "self-flex-end": {
    parameters: 0,
    fields: ["alignSelf"],
    resolve: (value) => ({ alignSelf: "flex-end" }),
  },
  "self-flex-start": {
    parameters: 0,
    fields: ["alignSelf"],
    resolve: (value) => ({ alignSelf: "flex-start" }),
  },
  "self-start": {
    parameters: 0,
    fields: ["alignSelf"],
    resolve: (value) => ({ alignSelf: "start" }),
  },
  "self-stretch": {
    parameters: 0,
    fields: ["alignSelf"],
    resolve: (value) => ({ alignSelf: "stretch" }),
  },
  size: {
    parameters: 2,
    fields: ["width", "height"],
    resolve: (value) => ({
      width: (value as readonly unknown[])[0],
      height: (value as readonly unknown[])[1],
    }),
  },
  "size-full": {
    parameters: 0,
    fields: ["width", "height"],
    resolve: (value) => ({ width: "100%", height: "100%" }),
  },
  "snap-align": {
    parameters: 1,
    fields: ["scrollSnapAlign"],
    resolve: (value) => ({ scrollSnapAlign: value }),
  },
  "snap-stop-always": {
    parameters: 0,
    fields: ["scrollSnapStop"],
    resolve: (value) => ({ scrollSnapStop: "always" }),
  },
  "position-sticky": {
    parameters: 0,
    fields: ["position"],
    resolve: (value) => ({ position: "sticky" }),
  },
  "sticky-bottom": {
    parameters: 1,
    fields: ["position", "bottom"],
    resolve: (value) => ({ position: "sticky", bottom: value }),
  },
  "sticky-left": {
    parameters: 1,
    fields: ["position", "left"],
    resolve: (value) => ({ position: "sticky", left: value }),
  },
  "sticky-right": {
    parameters: 1,
    fields: ["position", "right"],
    resolve: (value) => ({ position: "sticky", right: value }),
  },
  "sticky-top": {
    parameters: 1,
    fields: ["position", "top"],
    resolve: (value) => ({ position: "sticky", top: value }),
  },
  "text-2xl": {
    parameters: 0,
    fields: ["fontSize", "lineHeight"],
    resolve: (value) => ({ fontSize: 24, lineHeight: 32 }),
  },
  "text-3xl": {
    parameters: 0,
    fields: ["fontSize", "lineHeight"],
    resolve: (value) => ({ fontSize: 30, lineHeight: 36 }),
  },
  "text-base": {
    parameters: 0,
    fields: ["fontSize", "lineHeight"],
    resolve: (value) => ({ fontSize: 16, lineHeight: 24 }),
  },
  "text-center": {
    parameters: 0,
    fields: ["textAlign"],
    resolve: (value) => ({ textAlign: "center" }),
  },
  "text-ellipsis": {
    parameters: 0,
    fields: ["textOverflow"],
    resolve: (value) => ({ textOverflow: "ellipsis" }),
  },
  "text-ellipsis-middle": {
    parameters: 0,
    fields: ["textOverflow"],
    resolve: (value) => ({ textOverflow: "ellipsis-middle" }),
  },
  "text-ellipsis-start": {
    parameters: 0,
    fields: ["textOverflow"],
    resolve: (value) => ({ textOverflow: "ellipsis-start" }),
  },
  "text-end": { parameters: 0, fields: ["textAlign"], resolve: (value) => ({ textAlign: "end" }) },
  "text-justify": {
    parameters: 0,
    fields: ["textAlign"],
    resolve: (value) => ({ textAlign: "justify" }),
  },
  "text-left": {
    parameters: 0,
    fields: ["textAlign"],
    resolve: (value) => ({ textAlign: "left" }),
  },
  "text-lg": {
    parameters: 0,
    fields: ["fontSize", "lineHeight"],
    resolve: (value) => ({ fontSize: 18, lineHeight: 26 }),
  },
  "text-right": {
    parameters: 0,
    fields: ["textAlign"],
    resolve: (value) => ({ textAlign: "right" }),
  },
  "text-sm": {
    parameters: 0,
    fields: ["fontSize", "lineHeight"],
    resolve: (value) => ({ fontSize: 14, lineHeight: 20 }),
  },
  "text-start": {
    parameters: 0,
    fields: ["textAlign"],
    resolve: (value) => ({ textAlign: "start" }),
  },
  "text-xl": {
    parameters: 0,
    fields: ["fontSize", "lineHeight"],
    resolve: (value) => ({ fontSize: 20, lineHeight: 28 }),
  },
  "text-xs": {
    parameters: 0,
    fields: ["fontSize", "lineHeight"],
    resolve: (value) => ({ fontSize: 12, lineHeight: 16 }),
  },
  truncate: {
    parameters: 0,
    fields: ["overflowX", "overflowY", "whiteSpace", "textOverflow"],
    resolve: (value) => ({
      overflowX: "hidden",
      overflowY: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    }),
  },
  "user-select-none": {
    parameters: 0,
    fields: ["userSelect"],
    resolve: (value) => ({ userSelect: "none" }),
  },
  "user-select-text": {
    parameters: 0,
    fields: ["userSelect"],
    resolve: (value) => ({ userSelect: "text" }),
  },
  visible: {
    parameters: 0,
    fields: ["visibility"],
    resolve: (value) => ({ visibility: "visible" }),
  },
  w: { parameters: 1, fields: ["width"], resolve: (value) => ({ width: value }) },
  "w-fraction": {
    parameters: 1,
    fields: ["width"],
    resolve: (value) => ({ width: fraction(value) }),
  },
  "w-full": { parameters: 0, fields: ["width"], resolve: (value) => ({ width: "100%" }) },
  "whitespace-normal": {
    parameters: 0,
    fields: ["whiteSpace"],
    resolve: (value) => ({ whiteSpace: "normal" }),
  },
  "whitespace-nowrap": {
    parameters: 0,
    fields: ["whiteSpace"],
    resolve: (value) => ({ whiteSpace: "nowrap" }),
  },
};

export const helperProperties = new Set(
  Object.values(styleHelpers).flatMap((helper) => helper.fields),
);

function fraction(value: unknown): string {
  const number = Number(value);
  return `${Number.isFinite(number) && number >= 0 ? number * 100 : 0}%`;
}

function gridTracks(value: unknown, minimum: string, maximum: string): string {
  const count = Number(value);
  if (!Number.isFinite(count) || count < 1) return "none";
  return `repeat(${Math.min(Math.trunc(count), 1024)}, minmax(${minimum}, ${maximum}))`;
}
