/**
 * Native modules: Zig under `modules/<name>/main.zig`, compiled into Node-API addons and exposed to
 * the application as typed TypeScript modules.
 *
 * `buildNativeModules` is the whole pipeline. For every module directory it hashes the Zig
 * sources, compiles them with `zig build-lib` against the runtime shipped in `@quickgui/native`
 * when the hash changed, reads the manifest the addon reports, and writes
 * `modules/<name>/index.ts`: typed wrappers that `bindNativeModule` turns into calls. The addon
 * lives under `.quickgui/modules/<name>/<target>/`, and because the generated file `require`s it
 * by a literal relative path, Bun embeds it in the compiled application.
 *
 * The pure pieces — argument lists, the generator, and the Zig signature scanner — are exported
 * so tests can cover them without a compiler.
 */

import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  realpathSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";

import {
  NATIVE_MODULE_ABI,
  nativeModuleBinding,
  parseNativeModuleManifest,
  type NativeFunctionSpec,
  type NativeModuleBinding,
  type NativeModuleManifest,
  type NativeTypeDescriptor,
  type NativeWire,
} from "@quickgui/native/modules";

import type { ResolvedQuickGuiConfig, ZigOptimizeMode } from "./config.ts";
import { CliError } from "./error.ts";
import { targetInfo, type QuickGuiTarget } from "./targets.ts";

/** The file that makes a directory under `modules/` a native module. */
export const NATIVE_MODULE_ENTRY = "main.zig";
/** Oldest Zig the runtime in `@quickgui/native/zig` targets. */
export const MINIMUM_ZIG_VERSION = { major: 0, minor: 16 } as const;
/** Most native modules one project may declare. */
export const MAX_NATIVE_MODULES = 64;
/** Most exported functions one native module may declare. */
export const MAX_NATIVE_MODULE_FUNCTIONS = 1_024;

export interface NativeModuleSource {
  /** Directory name, which is also the addon name and the generated module's identity. */
  name: string;
  directory: string;
  /** Absolute path of `main.zig`. */
  entry: string;
}

export interface ZigToolchain {
  path: string;
  version: string;
}

export interface BuildNativeModulesOptions {
  target: QuickGuiTarget;
  mode: "development" | "production";
  /** Receives one progress line per compiled module. */
  log?: (line: string) => void;
}

export interface BuiltNativeModule {
  name: string;
  /** The compiled addon, under `.quickgui/modules/<name>/<target>/`. */
  addonPath: string;
  /** The generated `modules/<name>/index.ts`. */
  indexPath: string;
  manifest: NativeModuleManifest;
  /** Whether Zig ran, as opposed to the previous addon being reused. */
  rebuilt: boolean;
}

/** Root the CLI compiles: the module's public functions become the addon's exports. */
export const NATIVE_MODULE_ROOT_SOURCE = `// Generated by @quickgui/cli. Do not edit.
comptime {
    @import("quickgui").exportModule(@import("module"));
}
`;

// --- discovery -----------------------------------------------------------------------------------

/** Every `<directory>/<name>/main.zig`, sorted by name. */
export function discoverNativeModules(directory: string): NativeModuleSource[] {
  if (!existsSync(directory) || !statSync(directory).isDirectory()) return [];
  const modules: NativeModuleSource[] = [];
  const entries = readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  for (const name of entries) {
    const entry = join(directory, name, NATIVE_MODULE_ENTRY);
    if (!existsSync(entry) || !statSync(entry).isFile()) continue;
    if (!/^[A-Za-z][A-Za-z0-9_-]*$/.test(name)) {
      throw new CliError(
        `Native module directory name \`${name}\` must start with a letter and contain only letters, digits, hyphens, and underscores`,
      );
    }
    modules.push({ name, directory: join(directory, name), entry });
  }
  if (modules.length > MAX_NATIVE_MODULES) {
    throw new CliError(`A project may declare at most ${MAX_NATIVE_MODULES} native modules`);
  }
  return modules;
}

// --- toolchain -----------------------------------------------------------------------------------

export function parseZigVersion(
  text: string,
): { major: number; minor: number; patch: number } | undefined {
  const match = /^(\d+)\.(\d+)\.(\d+)/.exec(text.trim());
  if (!match) return undefined;
  return { major: Number(match[1]), minor: Number(match[2]), patch: Number(match[3]) };
}

export function zigVersionSupported(version: string): boolean {
  const parsed = parseZigVersion(version);
  if (!parsed) return false;
  if (parsed.major !== MINIMUM_ZIG_VERSION.major) return parsed.major > MINIMUM_ZIG_VERSION.major;
  return parsed.minor >= MINIMUM_ZIG_VERSION.minor;
}

/** Locate a usable Zig: `QUICKGUI_ZIG`, then `zig` on PATH. */
export function findZig(env: Record<string, string | undefined> = process.env): ZigToolchain {
  const candidates: string[] = [];
  if (env.QUICKGUI_ZIG) candidates.push(env.QUICKGUI_ZIG);
  const onPath = Bun.which("zig", env.PATH ? { PATH: env.PATH } : undefined);
  if (onPath) candidates.push(onPath);
  const seen: string[] = [];
  for (const candidate of candidates) {
    if (!existsSync(candidate)) continue;
    const result = Bun.spawnSync([candidate, "version"], { stdout: "pipe", stderr: "pipe" });
    if (result.exitCode !== 0) continue;
    const version = result.stdout.toString().trim();
    if (zigVersionSupported(version)) return { path: candidate, version };
    seen.push(`${candidate} (${version})`);
  }
  const minimum = `${MINIMUM_ZIG_VERSION.major}.${MINIMUM_ZIG_VERSION.minor}`;
  throw new CliError(
    `Native modules need Zig ${minimum} or newer on PATH, or QUICKGUI_ZIG pointing at one. ` +
      (seen.length > 0 ? `Found ${seen.join(", ")}. ` : "") +
      "Install it from https://ziglang.org/download/ (for example `mise use -g zig@0.16.0`).",
  );
}

export function zigTarget(target: QuickGuiTarget): string {
  const info = targetInfo(target);
  if (info.platform === "windows") {
    throw new CliError(
      `Native modules are not supported for ${target} yet: a Windows addon has to link against the host's import library`,
    );
  }
  const architecture = info.architecture === "arm64" ? "aarch64" : "x86_64";
  return info.platform === "darwin" ? `${architecture}-macos` : `${architecture}-linux-gnu`;
}

export interface ZigBuildInput {
  zig: string;
  name: string;
  optimize: ZigOptimizeMode;
  target: QuickGuiTarget;
  /** The generated root that exports the module. */
  root: string;
  /** The module's `main.zig`. */
  entry: string;
  /** `quickgui.zig` from `@quickgui/native/zig`. */
  runtime: string;
  /** Where the `.node` addon is written. */
  output: string;
  cacheDirectory: string;
}

/**
 * The `zig build-lib` invocation for one module.
 *
 * The addon references Node-API symbols the host process provides, so undefined symbols are
 * allowed; the compiler otherwise needs neither a libc nor an SDK for these libraries.
 */
export function zigBuildArguments(input: ZigBuildInput): string[] {
  return [
    input.zig,
    "build-lib",
    "-dynamic",
    `-O${input.optimize}`,
    "-target",
    zigTarget(input.target),
    "-fallow-shlib-undefined",
    "--name",
    input.name,
    `-femit-bin=${input.output}`,
    "--cache-dir",
    input.cacheDirectory,
    "--dep",
    "quickgui",
    "--dep",
    "module",
    `-Mroot=${input.root}`,
    "--dep",
    "quickgui",
    `-Mmodule=${input.entry}`,
    `-Mquickgui=${input.runtime}`,
  ];
}

// --- build ---------------------------------------------------------------------------------------

/** Compile every native module of a project and refresh its generated `index.ts`. */
export async function buildNativeModules(
  config: ResolvedQuickGuiConfig,
  options: BuildNativeModulesOptions,
): Promise<BuiltNativeModule[]> {
  const modules = discoverNativeModules(config.modules.directory);
  if (modules.length === 0) return [];
  zigTarget(options.target);
  const zig = findZig();
  const optimize =
    config.modules.optimize ?? (options.mode === "production" ? "ReleaseFast" : "ReleaseSafe");
  const runtimeDirectory = nativeRuntimeDirectory();
  const cacheDirectory = resolve(config.projectRoot, ".quickgui", "zig-cache");
  const results: BuiltNativeModule[] = [];
  for (const module of modules) {
    const outputDirectory = resolve(
      config.projectRoot,
      ".quickgui",
      "modules",
      module.name,
      options.target,
    );
    mkdirSync(outputDirectory, { recursive: true });
    const addonPath = resolve(outputDirectory, `${module.name}.node`);
    const statePath = resolve(outputDirectory, "build.json");
    const hash = nativeModuleInputsHash(module, {
      zigVersion: zig.version,
      target: options.target,
      optimize,
      runtimeDirectory,
    });
    let manifest = readBuildState(statePath, hash, addonPath);
    let rebuilt = false;
    if (!manifest) {
      const started = performance.now();
      const rootPath = resolve(outputDirectory, "root.zig");
      writeFileSync(rootPath, NATIVE_MODULE_ROOT_SOURCE);
      await runZig(
        zigBuildArguments({
          zig: zig.path,
          name: module.name,
          optimize,
          target: options.target,
          root: rootPath,
          entry: module.entry,
          runtime: resolve(runtimeDirectory, "quickgui.zig"),
          output: addonPath,
          cacheDirectory,
        }),
        config.projectRoot,
        module.name,
      );
      manifest = await readAddonManifest(addonPath, module.name);
      if (manifest.functions.length > MAX_NATIVE_MODULE_FUNCTIONS) {
        throw new CliError(
          `Native module ${module.name} exports ${manifest.functions.length} functions; the limit is ${MAX_NATIVE_MODULE_FUNCTIONS}`,
        );
      }
      writeFileSync(statePath, `${JSON.stringify({ hash, manifest }, null, 2)}\n`);
      rebuilt = true;
      options.log?.(
        `Built native module ${module.name} with Zig ${zig.version} (${optimize}) in ${Math.round(performance.now() - started)} ms`,
      );
    }
    const indexPath = resolve(module.directory, "index.ts");
    const source = generateNativeModuleSource({
      name: module.name,
      manifest,
      addonImportPath: importPath(relative(dirname(indexPath), addonPath)),
      entryDisplayPath: relative(config.projectRoot, module.entry).split(sep).join("/"),
      zigSource: readFileSync(module.entry, "utf8"),
    });
    if (!existsSync(indexPath) || readFileSync(indexPath, "utf8") !== source) {
      writeFileSync(indexPath, source);
    }
    results.push({ name: module.name, addonPath, indexPath, manifest, rebuilt });
  }
  return results;
}

function nativeRuntimeDirectory(): string {
  let entry: string;
  try {
    entry = Bun.resolveSync("@quickgui/native", import.meta.dir);
  } catch (error) {
    throw new CliError("Could not resolve @quickgui/native, which ships the native module runtime", {
      cause: error,
    });
  }
  const directory = resolve(dirname(realpathSync(entry)), "zig");
  if (!existsSync(resolve(directory, "quickgui.zig"))) {
    throw new CliError(`The installed @quickgui/native package has no zig/quickgui.zig at ${directory}`);
  }
  return directory;
}

/** Every `.zig` file under a directory, relative to it, sorted. */
export function zigSourceFiles(directory: string): string[] {
  const files: string[] = [];
  const walk = (current: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      if (entry.name === ".zig-cache" || entry.name === "zig-out" || entry.name === "node_modules") {
        continue;
      }
      const path = join(current, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.isFile() && entry.name.endsWith(".zig")) files.push(relative(directory, path));
    }
  };
  walk(directory);
  return files.sort();
}

function nativeModuleInputsHash(
  module: NativeModuleSource,
  inputs: { zigVersion: string; target: string; optimize: string; runtimeDirectory: string },
): string {
  const hash = createHash("sha256");
  hash.update(`quickgui-native-module:${NATIVE_MODULE_ABI}\0`);
  hash.update(`${inputs.zigVersion}\0${inputs.target}\0${inputs.optimize}\0`);
  hash.update(NATIVE_MODULE_ROOT_SOURCE);
  for (const file of zigSourceFiles(inputs.runtimeDirectory)) {
    hash.update(`runtime:${file}\0`);
    hash.update(readFileSync(join(inputs.runtimeDirectory, file)));
    hash.update("\0");
  }
  for (const file of zigSourceFiles(module.directory)) {
    hash.update(`module:${file}\0`);
    hash.update(readFileSync(join(module.directory, file)));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function readBuildState(
  statePath: string,
  hash: string,
  addonPath: string,
): NativeModuleManifest | undefined {
  if (!existsSync(statePath) || !existsSync(addonPath)) return undefined;
  try {
    const state = JSON.parse(readFileSync(statePath, "utf8")) as { hash?: unknown; manifest?: unknown };
    if (state.hash !== hash || state.manifest === undefined) return undefined;
    return parseNativeModuleManifest(JSON.stringify(state.manifest));
  } catch {
    return undefined;
  }
}

async function runZig(command: string[], cwd: string, moduleName: string): Promise<void> {
  const child = Bun.spawn(command, { cwd, stdin: "ignore", stdout: "pipe", stderr: "pipe" });
  const [status, stdout, stderr] = await Promise.all([
    child.exited,
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
  ]);
  if (status !== 0) {
    const detail = (stderr.trim() || stdout.trim()).replaceAll(cwd + sep, "");
    throw new CliError(
      `Zig could not compile native module ${moduleName}${detail ? `\n${detail}` : ""}`,
    );
  }
}

/**
 * Load the compiled addon in a child process and return its manifest.
 *
 * A child keeps the CLI's own process free of the addon: `dlopen` caches by path, so a module
 * rebuilt during `quickgui dev` could otherwise report the manifest of the previous build.
 */
async function readAddonManifest(addonPath: string, moduleName: string): Promise<NativeModuleManifest> {
  const script = "process.stdout.write(require(process.env.QUICKGUI_MODULE_ADDON).manifest());";
  const child = Bun.spawn([process.execPath, "-e", script], {
    env: { ...process.env, QUICKGUI_MODULE_ADDON: addonPath },
    stdin: "ignore",
    stdout: "pipe",
    stderr: "pipe",
  });
  const [status, stdout, stderr] = await Promise.all([
    child.exited,
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
  ]);
  if (status !== 0) {
    throw new CliError(
      `The compiled native module ${moduleName} could not be loaded${stderr.trim() ? `\n${stderr.trim()}` : ""}`,
    );
  }
  try {
    return parseNativeModuleManifest(stdout);
  } catch (error) {
    throw new CliError(`Native module ${moduleName} reported an invalid manifest`, { cause: error });
  }
}

function importPath(path: string): string {
  const normalized = path.split(sep).join("/");
  return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

// --- Zig source scanning -------------------------------------------------------------------------

export interface ZigFunctionSignature {
  name: string;
  /** Parameter names in declaration order; `_` becomes an empty string. */
  params: string[];
  /** `///` comment lines directly above the function, without the marker. */
  doc: string[];
  /** The declaration from `pub fn` up to the body, on one line. */
  text: string;
}

/**
 * Recover what `@typeInfo` does not carry: parameter names and doc comments of every `pub fn`.
 *
 * This is a lexical scan, not a parser; it handles the shapes real modules use (nested parentheses
 * in types, multi-line parameter lists, string literals) and leaves anything else nameless.
 */
export function extractZigFunctionSignatures(source: string): Map<string, ZigFunctionSignature> {
  const signatures = new Map<string, ZigFunctionSignature>();
  const lines = source.split("\n");
  let doc: string[] = [];
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index]!;
    const docMatch = /^\s*\/\/\/(.*)$/.exec(line);
    if (docMatch) {
      doc.push(docMatch[1]!.replace(/^ /, ""));
      continue;
    }
    const match = /^\s*pub\s+(?:inline\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(/.exec(line);
    if (!match) {
      if (line.trim().length > 0) doc = [];
      continue;
    }
    const name = match[1]!;
    // Collect text from the opening parenthesis until the body starts.
    let text = line.slice(line.indexOf("("));
    let closed = -1;
    let cursor = index;
    for (;;) {
      let depth = 0;
      for (let position = 0; position < text.length; position += 1) {
        const character = text[position];
        if (character === "(") depth += 1;
        else if (character === ")") {
          depth -= 1;
          if (depth === 0) {
            closed = position;
            break;
          }
        }
      }
      if (closed >= 0) break;
      cursor += 1;
      if (cursor >= lines.length) break;
      text += `\n${lines[cursor]}`;
    }
    if (closed < 0) {
      doc = [];
      continue;
    }
    let declaration = text.slice(0, closed + 1);
    let rest = text.slice(closed + 1);
    let bodyAt = findBodyBrace(rest);
    while (bodyAt < 0 && cursor + 1 < lines.length) {
      cursor += 1;
      rest += `\n${lines[cursor]}`;
      bodyAt = findBodyBrace(rest);
    }
    declaration += bodyAt >= 0 ? rest.slice(0, bodyAt) : rest;
    const params = splitTopLevel(declaration.slice(1, closed)).map((parameter) => {
      const cleaned = parameter.replace(/^\s*(?:comptime|noalias)\s+/, "").trim();
      const colon = cleaned.indexOf(":");
      const identifier = (colon >= 0 ? cleaned.slice(0, colon) : cleaned).trim();
      if (identifier === "_" || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(identifier)) return "";
      return identifier;
    });
    signatures.set(name, {
      name,
      params,
      doc,
      text: `pub fn ${name}${declaration.replace(/\s+/g, " ").trim()}`,
    });
    doc = [];
    index = cursor;
  }
  return signatures;
}

/**
 * Index of the `{` that opens the function body in the text after the parameter list, or -1 when
 * the text ends first. A `{` that follows `struct`, `union`, `enum`, `opaque`, or `error` (possibly
 * with a parenthesized tag or backing type) belongs to an anonymous type in the return type and
 * is skipped together with its contents.
 */
function findBodyBrace(text: string): number {
  const typeKeywords = new Set(["struct", "union", "enum", "opaque", "error"]);
  let position = 0;
  while (position < text.length) {
    const brace = text.indexOf("{", position);
    if (brace < 0) return -1;
    let before = brace;
    while (before > 0 && /\s/.test(text[before - 1]!)) before -= 1;
    let keyword: string | undefined;
    if (text[before - 1] === ")") {
      let depth = 0;
      let open = before - 1;
      for (; open >= 0; open -= 1) {
        if (text[open] === ")") depth += 1;
        else if (text[open] === "(") {
          depth -= 1;
          if (depth === 0) break;
        }
      }
      const identifier = /([A-Za-z_][A-Za-z0-9_]*)\s*$/.exec(text.slice(0, Math.max(open, 0)));
      keyword = identifier?.[1];
    } else {
      const identifier = /([A-Za-z_][A-Za-z0-9_]*)$/.exec(text.slice(0, before));
      keyword = identifier?.[1];
    }
    if (keyword === undefined || !typeKeywords.has(keyword)) return brace;
    // Skip the anonymous type's braces; an unclosed one needs more lines.
    let depth = 0;
    let index = brace;
    for (; index < text.length; index += 1) {
      if (text[index] === "{") depth += 1;
      else if (text[index] === "}") {
        depth -= 1;
        if (depth === 0) break;
      }
    }
    if (index >= text.length) return -1;
    position = index + 1;
  }
  return -1;
}

function splitTopLevel(text: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let current = "";
  for (const character of text) {
    if (character === "(" || character === "[" || character === "{") depth += 1;
    else if (character === ")" || character === "]" || character === "}") depth -= 1;
    if (character === "," && depth === 0) {
      parts.push(current);
      current = "";
      continue;
    }
    current += character;
  }
  if (current.trim().length > 0) parts.push(current);
  return parts.filter((part) => part.trim().length > 0);
}

// --- TypeScript generation -----------------------------------------------------------------------

export interface GenerateNativeModuleSourceInput {
  name: string;
  manifest: NativeModuleManifest;
  /** The addon relative to the generated file, using forward slashes. */
  addonImportPath: string;
  /** `main.zig` relative to the project root, for the header comment. */
  entryDisplayPath: string;
  /** Contents of `main.zig`, for parameter names and doc comments. */
  zigSource?: string;
}

const reservedIdentifiers = new Set([
  "arguments", "await", "break", "case", "catch", "class", "const", "continue", "debugger",
  "default", "delete", "do", "else", "enum", "eval", "export", "extends", "false", "finally",
  "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new",
  "null", "package", "private", "protected", "public", "return", "static", "super", "switch",
  "this", "throw", "true", "try", "typeof", "undefined", "var", "void", "while", "with", "yield",
  // Identifiers the generated file uses itself.
  "binding", "bindNativeModule", "loadAddon", "native", "require", "NativeModuleBinding",
]);

const identifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

interface HoistedType {
  tsName: string;
  zigName: string;
  descriptor: NativeTypeDescriptor;
  /** Serialized descriptor, to tell two Zig types with one short name apart. */
  shape: string;
}

/** Write the typed TypeScript module for one compiled native module. */
export function generateNativeModuleSource(input: GenerateNativeModuleSourceInput): string {
  const { name, manifest } = input;
  const signatures = input.zigSource ? extractZigFunctionSignatures(input.zigSource) : new Map();
  const hoisted = new Map<string, HoistedType>();
  const hoistedByShape = new Map<string, HoistedType>();
  const declarationOrder: HoistedType[] = [];

  const hoist = (descriptor: NativeTypeDescriptor & { name: string }): HoistedType | undefined => {
    const shortName = hoistedName(descriptor.name);
    if (!shortName) return undefined;
    const shape = JSON.stringify(descriptor);
    const key = `${descriptor.name}\0${shape}`;
    const existing = hoistedByShape.get(key);
    if (existing) return existing;
    let tsName = shortName;
    if (hoisted.has(tsName)) {
      tsName = descriptor.name.replace(/[^A-Za-z0-9_$]+/g, "_");
      let counter = 2;
      while (hoisted.has(tsName)) tsName = `${shortName}${counter++}`;
    }
    const entry: HoistedType = { tsName, zigName: descriptor.name, descriptor, shape };
    hoisted.set(tsName, entry);
    hoistedByShape.set(key, entry);
    declarationOrder.push(entry);
    return entry;
  };

  const seenRefs = new Map<string, string>();
  const tsType = (descriptor: NativeTypeDescriptor): string => {
    switch (descriptor.kind) {
      case "void":
        return "Record<string, never>";
      case "boolean":
        return "boolean";
      case "number":
        return "number";
      case "string":
        return "string";
      case "bytes":
        return "Uint8Array";
      case "any":
        return "unknown";
      case "optional":
        return `${tsType(descriptor.inner)} | null`;
      case "array":
        return `${parenthesize(tsType(descriptor.element))}[]`;
      case "tuple":
        return `[${descriptor.elements.map(tsType).join(", ")}]`;
      case "ref":
        return seenRefs.get(descriptor.name) ?? "unknown";
      case "enum": {
        const entry = hoist(descriptor);
        return entry ? entry.tsName : enumLiteral(descriptor.values);
      }
      case "struct": {
        const entry = hoist(descriptor);
        if (entry) {
          seenRefs.set(descriptor.name, entry.tsName);
          return entry.tsName;
        }
        return structLiteral(descriptor.fields, tsType, " ");
      }
      case "union": {
        const entry = hoist(descriptor);
        if (entry) {
          seenRefs.set(descriptor.name, entry.tsName);
          return entry.tsName;
        }
        return unionLiteral(descriptor.variants, tsType);
      }
    }
  };

  // Resolve every function's types first so hoisted declarations are complete before emission.
  const functions = manifest.functions.map((spec) => {
    validateFunctionName(name, spec.name, manifest.functions);
    const signature = signatures.get(spec.name) as ZigFunctionSignature | undefined;
    const sourceNames = signature && signature.params.length === spec.params.length ? signature.params : undefined;
    const parameters: { name: string; type: string }[] = [];
    let position = 0;
    spec.params.forEach((parameter, index) => {
      if ("injected" in parameter) return;
      position += 1;
      const candidate = sourceNames?.[index] || `arg${position}`;
      const parameterName =
        identifierPattern.test(candidate) && !reservedIdentifiers.has(candidate) && candidate !== "_"
          ? candidate
          : `${candidate.replace(/[^A-Za-z0-9_$]+/g, "_") || "arg"}_`;
      parameters.push({ name: parameterName, type: parameterType(parameter.wire, parameter.type, tsType) });
    });
    const result = resultType(spec.result.wire, spec.result.type, tsType);
    return { spec, parameters, result, signature };
  });

  const binding = nativeModuleBinding(manifest);
  const lines: string[] = [];
  lines.push(
    `// Generated by @quickgui/cli from ${input.entryDisplayPath}. Do not edit: \`quickgui dev\`,`,
    "// `quickgui build`, and `quickgui modules` rewrite this file whenever the Zig source changes.",
    "/* eslint-disable */",
    'import { bindNativeModule, type NativeModuleBinding } from "@quickgui/native/modules";',
    "",
    `const binding: NativeModuleBinding = ${JSON.stringify(binding)};`,
    "",
    "function loadAddon(): unknown {",
    "  try {",
    "    // A literal relative path lets Bun embed the addon in the compiled application.",
    `    return require(${JSON.stringify(input.addonImportPath)});`,
    "  } catch (error) {",
    `    throw new Error(${JSON.stringify(
      `The native module "${name}" is not built for this host. Run \`quickgui modules\` (or \`quickgui dev\`).`,
    )}, { cause: error });`,
    "  }",
    "}",
    "",
    `const native = bindNativeModule(${JSON.stringify(name)}, loadAddon(), binding);`,
  );

  for (const entry of declarationOrder) {
    lines.push("", ...typeDeclaration(entry, tsType));
  }

  functions.forEach(({ spec, parameters, result, signature }, index) => {
    const parameterList = parameters.map((parameter) => `${parameter.name}: ${parameter.type}`).join(", ");
    const argumentList = parameters.map((parameter) => parameter.name).join(", ");
    const doc = signature?.doc ?? [];
    const zigLine = signature ? `Zig: \`${signature.text}\`` : undefined;
    lines.push("", ...jsDoc([...doc, ...(doc.length > 0 && zigLine ? [""] : []), ...(zigLine ? [zigLine] : [])]));
    lines.push(
      `export function ${spec.name}(${parameterList}): ${result} {`,
      `  return native.call(${index}, [${argumentList}]) as ${result};`,
      "}",
    );
    lines.push(
      "",
      ...jsDoc([
        `Like \`${spec.name}\`, but runs on the native thread pool and resolves when it finishes.`,
        ...(zigLine ? ["", zigLine] : []),
      ]),
      `export function ${spec.name}Async(${parameterList}): Promise<${result}> {`,
      `  return native.callAsync(${index}, [${argumentList}]) as Promise<${result}>;`,
      "}",
    );
  });
  lines.push("");
  return lines.join("\n");
}

function validateFunctionName(module: string, functionName: string, all: readonly NativeFunctionSpec[]): void {
  if (!identifierPattern.test(functionName) || reservedIdentifiers.has(functionName)) {
    throw new CliError(
      `Native module ${module} exports \`${functionName}\`, which is not a usable JavaScript export name; rename it in ${NATIVE_MODULE_ENTRY}`,
    );
  }
  if (functionName.endsWith("Async")) {
    const base = functionName.slice(0, -"Async".length);
    if (all.some((spec) => spec.name === base)) {
      throw new CliError(
        `Native module ${module} exports both \`${base}\` and \`${functionName}\`; the generated \`${base}Async\` wrapper would clash. Rename one of them in ${NATIVE_MODULE_ENTRY}`,
      );
    }
  }
}

/** The TypeScript name for a Zig type name such as `main.DiffFile`, or nothing for anonymous types. */
export function hoistedName(zigName: string): string | undefined {
  if (/__(?:struct|union|enum|opaque)_\d+/.test(zigName)) return undefined;
  if (/[^A-Za-z0-9_.$]/.test(zigName)) return undefined;
  const short = zigName.slice(zigName.lastIndexOf(".") + 1);
  if (!identifierPattern.test(short) || reservedIdentifiers.has(short)) return undefined;
  return short;
}

function parameterType(
  wire: NativeWire,
  descriptor: NativeTypeDescriptor,
  tsType: (descriptor: NativeTypeDescriptor) => string,
): string {
  switch (wire) {
    case "void":
      return "undefined";
    case "boolean":
      return "boolean";
    case "number":
      return "number";
    case "string":
      return "string | Uint8Array";
    case "bytes":
      return "Uint8Array";
    case "json":
      return tsType(descriptor);
  }
}

function resultType(
  wire: NativeWire,
  descriptor: NativeTypeDescriptor,
  tsType: (descriptor: NativeTypeDescriptor) => string,
): string {
  switch (wire) {
    case "void":
      return "void";
    case "boolean":
      return "boolean";
    case "number":
      return "number";
    case "string":
      return "string";
    case "bytes":
      return "Uint8Array";
    case "json":
      return tsType(descriptor);
  }
}

function typeDeclaration(
  entry: HoistedType,
  tsType: (descriptor: NativeTypeDescriptor) => string,
): string[] {
  const descriptor = entry.descriptor;
  const header = `/** Zig \`${entry.zigName}\`. */`;
  switch (descriptor.kind) {
    case "struct":
      return [header, `export interface ${entry.tsName} ${structLiteral(descriptor.fields, tsType, "\n")}`];
    case "enum":
      return [header, `export type ${entry.tsName} = ${enumLiteral(descriptor.values)};`];
    case "union":
      return [header, `export type ${entry.tsName} = ${unionLiteral(descriptor.variants, tsType)};`];
    default:
      return [];
  }
}

function structLiteral(
  fields: readonly { name: string; type: NativeTypeDescriptor; hasDefault: boolean }[],
  tsType: (descriptor: NativeTypeDescriptor) => string,
  separator: " " | "\n",
): string {
  if (fields.length === 0) return "Record<string, never>";
  const members = fields.map(
    (field) => `${propertyName(field.name)}${field.hasDefault ? "?" : ""}: ${tsType(field.type)};`,
  );
  if (separator === "\n") return `{\n${members.map((member) => `  ${member}`).join("\n")}\n}`;
  return `{ ${members.join(" ")} }`;
}

function enumLiteral(values: readonly string[]): string {
  return values.length === 0 ? "never" : values.map((value) => JSON.stringify(value)).join(" | ");
}

function unionLiteral(
  variants: readonly { name: string; type: NativeTypeDescriptor }[],
  tsType: (descriptor: NativeTypeDescriptor) => string,
): string {
  return variants.length === 0
    ? "never"
    : variants.map((variant) => `{ ${propertyName(variant.name)}: ${tsType(variant.type)} }`).join(" | ");
}

function propertyName(name: string): string {
  return identifierPattern.test(name) ? name : JSON.stringify(name);
}

function parenthesize(type: string): string {
  return type.includes(" | ") || type.includes(" & ") ? `(${type})` : type;
}

function jsDoc(lines: readonly string[]): string[] {
  const content = lines.map((line) => line.replaceAll("*/", "*\\/"));
  if (content.length === 0) return [];
  if (content.length === 1) return [`/** ${content[0]} */`];
  return ["/**", ...content.map((line) => (line.length > 0 ? ` * ${line}` : " *")), " */"];
}
