// Code generated by optionsgen; DO NOT EDIT.

package ui

import "github.com/egoist/quickgui/go/native"

// ObjectFit sets the corresponding style property.
func (element *Element) ObjectFit(value string) *Element {
	return element.configureStyle("ObjectFit", ObjectFit(value))
}

// WordWrap sets the corresponding style property.
func (element *Element) WordWrap(value string) *Element {
	return element.configureStyle("OverflowWrap", WordWrap(value))
}

// TransitionTimingFunction sets the corresponding style property.
func (element *Element) TransitionTimingFunction(value any) *Element {
	return element.configureStyle("TransitionEasing", TransitionTimingFunction(value))
}

// PaddingInlineStart sets the corresponding style property.
func (element *Element) PaddingInlineStart(value any) *Element {
	return element.configureStyle("PaddingStart", PaddingInlineStart(value))
}

// PaddingInlineEnd sets the corresponding style property.
func (element *Element) PaddingInlineEnd(value any) *Element {
	return element.configureStyle("PaddingEnd", PaddingInlineEnd(value))
}

// MarginInlineStart sets the corresponding style property.
func (element *Element) MarginInlineStart(value any) *Element {
	return element.configureStyle("MarginStart", MarginInlineStart(value))
}

// MarginInlineEnd sets the corresponding style property.
func (element *Element) MarginInlineEnd(value any) *Element {
	return element.configureStyle("MarginEnd", MarginInlineEnd(value))
}

// BorderInlineStartWidth sets the corresponding style property.
func (element *Element) BorderInlineStartWidth(value any) *Element {
	return element.configureStyle("BorderStartWidth", BorderInlineStartWidth(value))
}

// BorderInlineEndWidth sets the corresponding style property.
func (element *Element) BorderInlineEndWidth(value any) *Element {
	return element.configureStyle("BorderEndWidth", BorderInlineEndWidth(value))
}

// AspectRatio sets the corresponding style property.
func (element *Element) AspectRatio(value any) *Element {
	return element.configureStyle("AspectRatio", AspectRatio(value))
}

// GridColumn sets the corresponding style property.
func (element *Element) GridColumn(value any) *Element {
	return element.configureStyle("GridColumn", GridColumn(value))
}

// GridRow sets the corresponding style property.
func (element *Element) GridRow(value any) *Element {
	return element.configureStyle("GridRow", GridRow(value))
}

// BorderStartWidth sets the corresponding style property.
func (element *Element) BorderStartWidth(value any) *Element {
	return element.configureStyle("BorderStartWidth", BorderStartWidth(value))
}

// BorderEndWidth sets the corresponding style property.
func (element *Element) BorderEndWidth(value any) *Element {
	return element.configureStyle("BorderEndWidth", BorderEndWidth(value))
}

// Background sets the corresponding style property.
func (element *Element) Background(value any) *Element {
	return element.configureStyle("Background", Background(value))
}

// BackgroundGradient sets the corresponding style property.
func (element *Element) BackgroundGradient(value any) *Element {
	return element.configureStyle("BackgroundGradient", BackgroundGradient(value))
}

// TransitionProperty sets the corresponding style property.
func (element *Element) TransitionProperty(value any) *Element {
	return element.configureStyle("TransitionProperty", TransitionProperty(value))
}

// TransitionDuration sets the corresponding style property.
func (element *Element) TransitionDuration(value any) *Element {
	return element.configureStyle("TransitionDuration", TransitionDuration(value))
}

// TransitionEasing sets the corresponding style property.
func (element *Element) TransitionEasing(value any) *Element {
	return element.configureStyle("TransitionEasing", TransitionEasing(value))
}

// TransitionMaxFps sets the corresponding style property.
func (element *Element) TransitionMaxFps(value any) *Element {
	return element.configureStyle("TransitionMaxFps", TransitionMaxFps(value))
}

// MarkdownCodeBackground sets the corresponding style property.
func (element *Element) MarkdownCodeBackground(value any) *Element {
	return element.configureStyle("MarkdownCodeBackground", MarkdownCodeBackground(value))
}

// MarkdownBorderColor sets the corresponding style property.
func (element *Element) MarkdownBorderColor(value any) *Element {
	return element.configureStyle("MarkdownBorderColor", MarkdownBorderColor(value))
}

// MarkdownMutedColor sets the corresponding style property.
func (element *Element) MarkdownMutedColor(value any) *Element {
	return element.configureStyle("MarkdownMutedColor", MarkdownMutedColor(value))
}

// MarkdownLinkColor sets the corresponding style property.
func (element *Element) MarkdownLinkColor(value any) *Element {
	return element.configureStyle("MarkdownLinkColor", MarkdownLinkColor(value))
}

// MarkdownCodeTextColor sets the corresponding style property.
func (element *Element) MarkdownCodeTextColor(value any) *Element {
	return element.configureStyle("MarkdownCodeTextColor", MarkdownCodeTextColor(value))
}

// MarkdownBlockGap sets the corresponding style property.
func (element *Element) MarkdownBlockGap(value any) *Element {
	return element.configureStyle("MarkdownBlockGap", MarkdownBlockGap(value))
}

// MarkdownCodeFontSize sets the corresponding style property.
func (element *Element) MarkdownCodeFontSize(value any) *Element {
	return element.configureStyle("MarkdownCodeFontSize", MarkdownCodeFontSize(value))
}

// ScrollToEndRevision sets the corresponding style property.
func (element *Element) ScrollToEndRevision(value any) *Element {
	return element.configureStyle("ScrollToEndRevision", ScrollToEndRevision(value))
}

// TextDecoration sets the corresponding style property.
func (element *Element) TextDecoration(value string) *Element {
	return element.configureStyle("TextDecoration", TextDecoration(value))
}

// InvalidStyle merges the Invalid interaction style.
func (element *Element) InvalidStyle(options ...StyleDeclaration) *Element {
	return element.configureStyle("Invalid", InvalidStyle(options...))
}

// Dragging merges the Dragging interaction style.
func (element *Element) Dragging(options ...StyleDeclaration) *Element {
	return element.configureStyle("Dragging", Dragging(options...))
}

// DragOver merges the DragOver interaction style.
func (element *Element) DragOver(options ...StyleDeclaration) *Element {
	return element.configureStyle("DragOver", DragOver(options...))
}

// FocusWithin merges the FocusWithin interaction style.
func (element *Element) FocusWithin(options ...StyleDeclaration) *Element {
	return element.configureStyle("FocusWithin", FocusWithin(options...))
}

// GridTemplateColumns sets the corresponding style property.
func (element *Element) GridTemplateColumns(value any) *Element {
	return element.configureStyle("GridTemplateColumns", GridTemplateColumns(value))
}

// GridTemplateRows sets the corresponding style property.
func (element *Element) GridTemplateRows(value any) *Element {
	return element.configureStyle("GridTemplateRows", GridTemplateRows(value))
}

// GridAutoFlow sets the corresponding style property.
func (element *Element) GridAutoFlow(value string) *Element {
	return element.configureStyle("GridAutoFlow", GridAutoFlow(value))
}

// GridColumnStart sets the corresponding style property.
func (element *Element) GridColumnStart(value any) *Element {
	return element.configureStyle("GridColumnStart", GridColumnStart(value))
}

// GridColumnEnd sets the corresponding style property.
func (element *Element) GridColumnEnd(value any) *Element {
	return element.configureStyle("GridColumnEnd", GridColumnEnd(value))
}

// GridColumnSpan sets the corresponding style property.
func (element *Element) GridColumnSpan(value any) *Element {
	return element.configureStyle("GridColumnSpan", GridColumnSpan(value))
}

// GridRowStart sets the corresponding style property.
func (element *Element) GridRowStart(value any) *Element {
	return element.configureStyle("GridRowStart", GridRowStart(value))
}

// GridRowEnd sets the corresponding style property.
func (element *Element) GridRowEnd(value any) *Element {
	return element.configureStyle("GridRowEnd", GridRowEnd(value))
}

// GridRowSpan sets the corresponding style property.
func (element *Element) GridRowSpan(value any) *Element {
	return element.configureStyle("GridRowSpan", GridRowSpan(value))
}

// PaddingStart sets the corresponding style property.
func (element *Element) PaddingStart(value any) *Element {
	return element.configureStyle("PaddingStart", PaddingStart(value))
}

// PaddingEnd sets the corresponding style property.
func (element *Element) PaddingEnd(value any) *Element {
	return element.configureStyle("PaddingEnd", PaddingEnd(value))
}

// MarginStart sets the corresponding style property.
func (element *Element) MarginStart(value any) *Element {
	return element.configureStyle("MarginStart", MarginStart(value))
}

// MarginEnd sets the corresponding style property.
func (element *Element) MarginEnd(value any) *Element {
	return element.configureStyle("MarginEnd", MarginEnd(value))
}

// BorderTopWidth sets the corresponding style property.
func (element *Element) BorderTopWidth(value any) *Element {
	return element.configureStyle("BorderTopWidth", BorderTopWidth(value))
}

// BorderRightWidth sets the corresponding style property.
func (element *Element) BorderRightWidth(value any) *Element {
	return element.configureStyle("BorderRightWidth", BorderRightWidth(value))
}

// BorderBottomWidth sets the corresponding style property.
func (element *Element) BorderBottomWidth(value any) *Element {
	return element.configureStyle("BorderBottomWidth", BorderBottomWidth(value))
}

// BorderLeftWidth sets the corresponding style property.
func (element *Element) BorderLeftWidth(value any) *Element {
	return element.configureStyle("BorderLeftWidth", BorderLeftWidth(value))
}

// BorderTopLeftRadius sets the corresponding style property.
func (element *Element) BorderTopLeftRadius(value any) *Element {
	return element.configureStyle("BorderTopLeftRadius", BorderTopLeftRadius(value))
}

// BorderTopRightRadius sets the corresponding style property.
func (element *Element) BorderTopRightRadius(value any) *Element {
	return element.configureStyle("BorderTopRightRadius", BorderTopRightRadius(value))
}

// BorderBottomLeftRadius sets the corresponding style property.
func (element *Element) BorderBottomLeftRadius(value any) *Element {
	return element.configureStyle("BorderBottomLeftRadius", BorderBottomLeftRadius(value))
}

// BorderBottomRightRadius sets the corresponding style property.
func (element *Element) BorderBottomRightRadius(value any) *Element {
	return element.configureStyle("BorderBottomRightRadius", BorderBottomRightRadius(value))
}

// BorderStyle sets the corresponding style property.
func (element *Element) BorderStyle(value string) *Element {
	return element.configureStyle("BorderStyle", BorderStyle(value))
}

// BoxShadow sets the corresponding style property.
func (element *Element) BoxShadow(value any) *Element {
	return element.configureStyle("BoxShadow", BoxShadow(value))
}

// TextShadow sets the corresponding style property.
func (element *Element) TextShadow(value any) *Element {
	return element.configureStyle("TextShadow", TextShadow(value))
}

// TextDecorationLine sets the corresponding style property.
func (element *Element) TextDecorationLine(value string) *Element {
	return element.configureStyle("TextDecorationLine", TextDecorationLine(value))
}

// TextDecorationColor sets the corresponding style property.
func (element *Element) TextDecorationColor(value any) *Element {
	return element.configureStyle("TextDecorationColor", TextDecorationColor(value))
}

// TextDecorationStyle sets the corresponding style property.
func (element *Element) TextDecorationStyle(value string) *Element {
	return element.configureStyle("TextDecorationStyle", TextDecorationStyle(value))
}

// TextDecorationThickness sets the corresponding style property.
func (element *Element) TextDecorationThickness(value any) *Element {
	return element.configureStyle("TextDecorationThickness", TextDecorationThickness(value))
}

// WordSpacing sets the corresponding style property.
func (element *Element) WordSpacing(value any) *Element {
	return element.configureStyle("WordSpacing", WordSpacing(value))
}

// WordBreak sets the corresponding style property.
func (element *Element) WordBreak(value string) *Element {
	return element.configureStyle("WordBreak", WordBreak(value))
}

// OverflowWrap sets the corresponding style property.
func (element *Element) OverflowWrap(value string) *Element {
	return element.configureStyle("OverflowWrap", OverflowWrap(value))
}

// Hyphens sets the corresponding style property.
func (element *Element) Hyphens(value string) *Element {
	return element.configureStyle("Hyphens", Hyphens(value))
}

// TextDirection sets the corresponding style property.
func (element *Element) TextDirection(value string) *Element {
	return element.configureStyle("TextDirection", TextDirection(value))
}

// Direction sets the corresponding style property.
func (element *Element) Direction(value string) *Element {
	return element.configureStyle("Direction", Direction(value))
}

// BackgroundImage sets the corresponding style property.
func (element *Element) BackgroundImage(value string) *Element {
	return element.configureStyle("BackgroundImage", BackgroundImage(value))
}

// BackgroundSize sets the corresponding style property.
func (element *Element) BackgroundSize(value string) *Element {
	return element.configureStyle("BackgroundSize", BackgroundSize(value))
}

// BackgroundRepeat sets the corresponding style property.
func (element *Element) BackgroundRepeat(value string) *Element {
	return element.configureStyle("BackgroundRepeat", BackgroundRepeat(value))
}

// BackgroundPosition sets the corresponding style property.
func (element *Element) BackgroundPosition(value string) *Element {
	return element.configureStyle("BackgroundPosition", BackgroundPosition(value))
}

// Filter sets the corresponding style property.
func (element *Element) Filter(value any) *Element {
	return element.configureStyle("Filter", Filter(value))
}

// BackdropFilter sets the corresponding style property.
func (element *Element) BackdropFilter(value any) *Element {
	return element.configureStyle("BackdropFilter", BackdropFilter(value))
}

// MixBlendMode sets the corresponding style property.
func (element *Element) MixBlendMode(value string) *Element {
	return element.configureStyle("MixBlendMode", MixBlendMode(value))
}

// Transition sets the corresponding style property.
func (element *Element) Transition(value any) *Element {
	return element.configureStyle("Transition", Transition(value))
}

// ScrollSnapType sets the corresponding style property.
func (element *Element) ScrollSnapType(value string) *Element {
	return element.configureStyle("ScrollSnapType", ScrollSnapType(value))
}

// ScrollSnapX sets the corresponding style property.
func (element *Element) ScrollSnapX(value string) *Element {
	return element.configureStyle("ScrollSnapX", ScrollSnapX(value))
}

// ScrollSnapY sets the corresponding style property.
func (element *Element) ScrollSnapY(value string) *Element {
	return element.configureStyle("ScrollSnapY", ScrollSnapY(value))
}

// ScrollSnapAlign sets the corresponding style property.
func (element *Element) ScrollSnapAlign(value string) *Element {
	return element.configureStyle("ScrollSnapAlign", ScrollSnapAlign(value))
}

// ScrollSnapStop sets the corresponding style property.
func (element *Element) ScrollSnapStop(value string) *Element {
	return element.configureStyle("ScrollSnapStop", ScrollSnapStop(value))
}

// Display sets the corresponding style property.
func (element *Element) Display(value string) *Element {
	return element.configureStyle("Display", Display(value))
}

// FlexDirection sets the corresponding style property.
func (element *Element) FlexDirection(value string) *Element {
	return element.configureStyle("FlexDirection", FlexDirection(value))
}

// FlexGrow sets the corresponding style property.
func (element *Element) FlexGrow(value any) *Element {
	return element.configureStyle("FlexGrow", FlexGrow(value))
}

// FlexShrink sets the corresponding style property.
func (element *Element) FlexShrink(value any) *Element {
	return element.configureStyle("FlexShrink", FlexShrink(value))
}

// FlexBasis sets the corresponding style property.
func (element *Element) FlexBasis(value any) *Element {
	return element.configureStyle("FlexBasis", FlexBasis(value))
}

// AlignItems sets the corresponding style property.
func (element *Element) AlignItems(value string) *Element {
	return element.configureStyle("AlignItems", AlignItems(value))
}

// AlignSelf sets the corresponding style property.
func (element *Element) AlignSelf(value string) *Element {
	return element.configureStyle("AlignSelf", AlignSelf(value))
}

// JustifyContent sets the corresponding style property.
func (element *Element) JustifyContent(value string) *Element {
	return element.configureStyle("JustifyContent", JustifyContent(value))
}

// AlignContent sets the corresponding style property.
func (element *Element) AlignContent(value string) *Element {
	return element.configureStyle("AlignContent", AlignContent(value))
}

// Gap sets the corresponding style property.
func (element *Element) Gap(value any) *Element {
	return element.configureStyle("Gap", Gap(value))
}

// ColumnGap sets the corresponding style property.
func (element *Element) ColumnGap(value any) *Element {
	return element.configureStyle("ColumnGap", ColumnGap(value))
}

// RowGap sets the corresponding style property.
func (element *Element) RowGap(value any) *Element {
	return element.configureStyle("RowGap", RowGap(value))
}

// Width sets the corresponding style property.
func (element *Element) Width(value any) *Element {
	return element.configureStyle("Width", Width(value))
}

// Height sets the corresponding style property.
func (element *Element) Height(value any) *Element {
	return element.configureStyle("Height", Height(value))
}

// MinWidth sets the corresponding style property.
func (element *Element) MinWidth(value any) *Element {
	return element.configureStyle("MinWidth", MinWidth(value))
}

// MinHeight sets the corresponding style property.
func (element *Element) MinHeight(value any) *Element {
	return element.configureStyle("MinHeight", MinHeight(value))
}

// MaxWidth sets the corresponding style property.
func (element *Element) MaxWidth(value any) *Element {
	return element.configureStyle("MaxWidth", MaxWidth(value))
}

// MaxHeight sets the corresponding style property.
func (element *Element) MaxHeight(value any) *Element {
	return element.configureStyle("MaxHeight", MaxHeight(value))
}

// Padding sets the corresponding style property.
func (element *Element) Padding(value any) *Element {
	return element.configureStyle("Padding", Padding(value))
}

// PaddingTop sets the corresponding style property.
func (element *Element) PaddingTop(value any) *Element {
	return element.configureStyle("PaddingTop", PaddingTop(value))
}

// PaddingRight sets the corresponding style property.
func (element *Element) PaddingRight(value any) *Element {
	return element.configureStyle("PaddingRight", PaddingRight(value))
}

// PaddingBottom sets the corresponding style property.
func (element *Element) PaddingBottom(value any) *Element {
	return element.configureStyle("PaddingBottom", PaddingBottom(value))
}

// PaddingLeft sets the corresponding style property.
func (element *Element) PaddingLeft(value any) *Element {
	return element.configureStyle("PaddingLeft", PaddingLeft(value))
}

// Margin sets the corresponding style property.
func (element *Element) Margin(value any) *Element {
	return element.configureStyle("Margin", Margin(value))
}

// MarginTop sets the corresponding style property.
func (element *Element) MarginTop(value any) *Element {
	return element.configureStyle("MarginTop", MarginTop(value))
}

// MarginRight sets the corresponding style property.
func (element *Element) MarginRight(value any) *Element {
	return element.configureStyle("MarginRight", MarginRight(value))
}

// MarginBottom sets the corresponding style property.
func (element *Element) MarginBottom(value any) *Element {
	return element.configureStyle("MarginBottom", MarginBottom(value))
}

// MarginLeft sets the corresponding style property.
func (element *Element) MarginLeft(value any) *Element {
	return element.configureStyle("MarginLeft", MarginLeft(value))
}

// BackgroundColor sets the corresponding style property.
func (element *Element) BackgroundColor(value any) *Element {
	return element.configureStyle("BackgroundColor", BackgroundColor(value))
}

// TextColor sets the corresponding style property.
func (element *Element) TextColor(value any) *Element {
	return element.configureStyle("TextColor", TextColor(value))
}

// Opacity sets the corresponding style property.
func (element *Element) Opacity(value any) *Element {
	return element.configureStyle("Opacity", Opacity(value))
}

// BorderWidth sets the corresponding style property.
func (element *Element) BorderWidth(value any) *Element {
	return element.configureStyle("BorderWidth", BorderWidth(value))
}

// BorderColor sets the corresponding style property.
func (element *Element) BorderColor(value any) *Element {
	return element.configureStyle("BorderColor", BorderColor(value))
}

// BorderRadius sets the corresponding style property.
func (element *Element) BorderRadius(value any) *Element {
	return element.configureStyle("BorderRadius", BorderRadius(value))
}

// FontSize sets the corresponding style property.
func (element *Element) FontSize(value any) *Element {
	return element.configureStyle("FontSize", FontSize(value))
}

// FontFamily sets the corresponding style property.
func (element *Element) FontFamily(value string) *Element {
	return element.configureStyle("FontFamily", FontFamily(value))
}

// FontWeight sets the corresponding style property.
func (element *Element) FontWeight(value any) *Element {
	return element.configureStyle("FontWeight", FontWeight(value))
}

// LineHeight sets the corresponding style property.
func (element *Element) LineHeight(value any) *Element {
	return element.configureStyle("LineHeight", LineHeight(value))
}

// TextAlign sets the corresponding style property.
func (element *Element) TextAlign(value string) *Element {
	return element.configureStyle("TextAlign", TextAlign(value))
}

// Cursor sets the corresponding style property.
func (element *Element) Cursor(value string) *Element {
	return element.configureStyle("Cursor", Cursor(value))
}

// AppRegion sets the corresponding style property.
func (element *Element) AppRegion(value string) *Element {
	return element.configureStyle("AppRegion", AppRegion(value))
}

// UserSelect sets the corresponding style property.
func (element *Element) UserSelect(value string) *Element {
	return element.configureStyle("UserSelect", UserSelect(value))
}

// Position sets the corresponding style property.
func (element *Element) Position(value string) *Element {
	return element.configureStyle("Position", Position(value))
}

// Overflow sets the corresponding style property.
func (element *Element) Overflow(value string) *Element {
	return element.configureStyle("Overflow", Overflow(value))
}

// OverflowX sets the corresponding style property.
func (element *Element) OverflowX(value string) *Element {
	return element.configureStyle("OverflowX", OverflowX(value))
}

// OverflowY sets the corresponding style property.
func (element *Element) OverflowY(value string) *Element {
	return element.configureStyle("OverflowY", OverflowY(value))
}

// Visibility sets the corresponding style property.
func (element *Element) Visibility(value string) *Element {
	return element.configureStyle("Visibility", Visibility(value))
}

// LetterSpacing sets the corresponding style property.
func (element *Element) LetterSpacing(value any) *Element {
	return element.configureStyle("LetterSpacing", LetterSpacing(value))
}

// TextTransform sets the corresponding style property.
func (element *Element) TextTransform(value string) *Element {
	return element.configureStyle("TextTransform", TextTransform(value))
}

// LineClamp sets the corresponding style property.
func (element *Element) LineClamp(value any) *Element {
	return element.configureStyle("LineClamp", LineClamp(value))
}

// WhiteSpace sets the corresponding style property.
func (element *Element) WhiteSpace(value string) *Element {
	return element.configureStyle("WhiteSpace", WhiteSpace(value))
}

// TextOverflow sets the corresponding style property.
func (element *Element) TextOverflow(value string) *Element {
	return element.configureStyle("TextOverflow", TextOverflow(value))
}

// Top sets the corresponding style property.
func (element *Element) Top(value any) *Element {
	return element.configureStyle("Top", Top(value))
}

// Right sets the corresponding style property.
func (element *Element) Right(value any) *Element {
	return element.configureStyle("Right", Right(value))
}

// Bottom sets the corresponding style property.
func (element *Element) Bottom(value any) *Element {
	return element.configureStyle("Bottom", Bottom(value))
}

// Left sets the corresponding style property.
func (element *Element) Left(value any) *Element {
	return element.configureStyle("Left", Left(value))
}

// Outline sets the corresponding style property.
func (element *Element) Outline(value any) *Element {
	return element.configureStyle("Outline", Outline(value))
}

// OutlineWidth sets the corresponding style property.
func (element *Element) OutlineWidth(value any) *Element {
	return element.configureStyle("OutlineWidth", OutlineWidth(value))
}

// OutlineColor sets the corresponding style property.
func (element *Element) OutlineColor(value any) *Element {
	return element.configureStyle("OutlineColor", OutlineColor(value))
}

// OutlineOffset sets the corresponding style property.
func (element *Element) OutlineOffset(value any) *Element {
	return element.configureStyle("OutlineOffset", OutlineOffset(value))
}

// OutlineStyle sets the corresponding style property.
func (element *Element) OutlineStyle(value string) *Element {
	return element.configureStyle("OutlineStyle", OutlineStyle(value))
}

// Transform sets the corresponding style property.
func (element *Element) Transform(value any) *Element {
	return element.configureStyle("Transform", Transform(value))
}

// TransformOrigin sets the corresponding style property.
func (element *Element) TransformOrigin(value string) *Element {
	return element.configureStyle("TransformOrigin", TransformOrigin(value))
}

// Hover merges the Hover interaction style.
func (element *Element) Hover(options ...StyleDeclaration) *Element {
	return element.configureStyle("Hover", Hover(options...))
}

// Active merges the Active interaction style.
func (element *Element) Active(options ...StyleDeclaration) *Element {
	return element.configureStyle("Active", Active(options...))
}

// FocusStyle merges the Focus interaction style.
func (element *Element) FocusStyle(options ...StyleDeclaration) *Element {
	return element.configureStyle("Focus", Focus(options...))
}

// DisabledStyle merges the Disabled interaction style.
func (element *Element) DisabledStyle(options ...StyleDeclaration) *Element {
	return element.configureStyle("Disabled", DisabledStyle(options...))
}

// SelectedStyle merges the Selected interaction style.
func (element *Element) SelectedStyle(options ...StyleDeclaration) *Element {
	return element.configureStyle("Selected", SelectedStyle(options...))
}

// OnMouseEnter configures the corresponding node property.
func (element *Element) OnMouseEnter(value func(*native.Event)) *Element {
	return element.configureProperty("OnMouseEnter", OnMouseEnter(value))
}

// OnMouseLeave configures the corresponding node property.
func (element *Element) OnMouseLeave(value func(*native.Event)) *Element {
	return element.configureProperty("OnMouseLeave", OnMouseLeave(value))
}

// OnDismiss configures the corresponding node property.
func (element *Element) OnDismiss(value func(*native.Event)) *Element {
	return element.configureProperty("OnDismiss", OnDismiss(value))
}

// OnStatus configures the corresponding node property.
func (element *Element) OnStatus(value func(*native.Event)) *Element {
	return element.configureProperty("OnStatus", OnStatus(value))
}

// OnPointer configures the corresponding node property.
func (element *Element) OnPointer(value func(*native.Event)) *Element {
	return element.configureProperty("OnPointer", OnPointer(value))
}

// OnPresentationChange configures the corresponding node property.
func (element *Element) OnPresentationChange(value func(*native.Event)) *Element {
	return element.configureProperty("OnPresentationChange", OnPresentationChange(value))
}

// OnSelect configures the corresponding node property.
func (element *Element) OnSelect(value func(*native.Event)) *Element {
	return element.configureProperty("OnSelect", OnSelect(value))
}

// OnKeyDown configures the corresponding node property.
func (element *Element) OnKeyDown(value func(*native.Event)) *Element {
	return element.configureProperty("OnKeyDown", OnKeyDown(value))
}

// OnKeyUp configures the corresponding node property.
func (element *Element) OnKeyUp(value func(*native.Event)) *Element {
	return element.configureProperty("OnKeyUp", OnKeyUp(value))
}

// OnMouseDown configures the corresponding node property.
func (element *Element) OnMouseDown(value func(*native.Event)) *Element {
	return element.configureProperty("OnMouseDown", OnMouseDown(value))
}

// OnMouseUp configures the corresponding node property.
func (element *Element) OnMouseUp(value func(*native.Event)) *Element {
	return element.configureProperty("OnMouseUp", OnMouseUp(value))
}

// OnMouseMove configures the corresponding node property.
func (element *Element) OnMouseMove(value func(*native.Event)) *Element {
	return element.configureProperty("OnMouseMove", OnMouseMove(value))
}

// OnDoubleClick configures the corresponding node property.
func (element *Element) OnDoubleClick(value func(*native.Event)) *Element {
	return element.configureProperty("OnDoubleClick", OnDoubleClick(value))
}

// OnWheel configures the corresponding node property.
func (element *Element) OnWheel(value func(*native.Event)) *Element {
	return element.configureProperty("OnWheel", OnWheel(value))
}

// OnContextMenu configures the corresponding node property.
func (element *Element) OnContextMenu(value func(*native.Event)) *Element {
	return element.configureProperty("OnContextMenu", OnContextMenu(value))
}

// OnPinch configures the corresponding node property.
func (element *Element) OnPinch(value func(*native.Event)) *Element {
	return element.configureProperty("OnPinch", OnPinch(value))
}

// OnRotate configures the corresponding node property.
func (element *Element) OnRotate(value func(*native.Event)) *Element {
	return element.configureProperty("OnRotate", OnRotate(value))
}

// OnSmartMagnify configures the corresponding node property.
func (element *Element) OnSmartMagnify(value func(*native.Event)) *Element {
	return element.configureProperty("OnSmartMagnify", OnSmartMagnify(value))
}

// OnPressure configures the corresponding node property.
func (element *Element) OnPressure(value func(*native.Event)) *Element {
	return element.configureProperty("OnPressure", OnPressure(value))
}

// OnFocus configures the corresponding node property.
func (element *Element) OnFocus(value func(*native.Event)) *Element {
	return element.configureProperty("OnFocus", OnFocus(value))
}

// OnBlur configures the corresponding node property.
func (element *Element) OnBlur(value func(*native.Event)) *Element {
	return element.configureProperty("OnBlur", OnBlur(value))
}

// OnAction configures the corresponding node property.
func (element *Element) OnAction(value func(*native.Event)) *Element {
	return element.configureProperty("OnAction", OnAction(value))
}

// OnDragStart configures the corresponding node property.
func (element *Element) OnDragStart(value func(*native.Event)) *Element {
	return element.configureProperty("OnDragStart", OnDragStart(value))
}

// OnDragEnd configures the corresponding node property.
func (element *Element) OnDragEnd(value func(*native.Event)) *Element {
	return element.configureProperty("OnDragEnd", OnDragEnd(value))
}

// OnDrop configures the corresponding node property.
func (element *Element) OnDrop(value func(*native.Event)) *Element {
	return element.configureProperty("OnDrop", OnDrop(value))
}

// OnFilesDropped configures the corresponding node property.
func (element *Element) OnFilesDropped(value func(*native.Event)) *Element {
	return element.configureProperty("OnFilesDropped", OnFilesDropped(value))
}

// OnComponentChange configures the corresponding node property.
func (element *Element) OnComponentChange(value func(*native.Event)) *Element {
	return element.configureProperty("OnComponentChange", OnComponentChange(value))
}

// OnCommit configures the corresponding node property.
func (element *Element) OnCommit(value func(*native.Event)) *Element {
	return element.configureProperty("OnCommit", OnCommit(value))
}

// Disabled configures the corresponding node property.
func (element *Element) Disabled(value any) *Element {
	return element.configureProperty("Disabled", Disabled(value))
}

// Value configures the corresponding node property.
func (element *Element) Value(value any) *Element {
	return element.configureProperty("Value", Value(value))
}

// Placeholder configures the corresponding node property.
func (element *Element) Placeholder(value string) *Element {
	return element.configureProperty("Placeholder", Placeholder(value))
}

// Multiline configures the corresponding node property.
func (element *Element) Multiline(value bool) *Element {
	return element.configureProperty("Multiline", Multiline(value))
}

// AriaLabel configures the corresponding node property.
func (element *Element) AriaLabel(value any) *Element {
	return element.configureProperty("AriaLabel", AriaLabel(value))
}

// Selected configures the corresponding node property.
func (element *Element) Selected(value any) *Element {
	return element.configureProperty("Selected", Selected(value))
}

// Group configures the corresponding node property.
func (element *Element) Group(value any) *Element {
	return element.configureProperty("Group", Group(value))
}

// FocusOnPointer configures the corresponding node property.
func (element *Element) FocusOnPointer(value any) *Element {
	return element.configureProperty("FocusOnPointer", FocusOnPointer(value))
}

// FocusableWhenDisabled configures the corresponding node property.
func (element *Element) FocusableWhenDisabled(value any) *Element {
	return element.configureProperty("FocusableWhenDisabled", FocusableWhenDisabled(value))
}

// HitSlop configures the corresponding node property.
func (element *Element) HitSlop(value any) *Element {
	return element.configureProperty("HitSlop", HitSlop(value))
}

// HitSlopTop configures the corresponding node property.
func (element *Element) HitSlopTop(value any) *Element {
	return element.configureProperty("HitSlopTop", HitSlopTop(value))
}

// HitSlopRight configures the corresponding node property.
func (element *Element) HitSlopRight(value any) *Element {
	return element.configureProperty("HitSlopRight", HitSlopRight(value))
}

// HitSlopBottom configures the corresponding node property.
func (element *Element) HitSlopBottom(value any) *Element {
	return element.configureProperty("HitSlopBottom", HitSlopBottom(value))
}

// HitSlopLeft configures the corresponding node property.
func (element *Element) HitSlopLeft(value any) *Element {
	return element.configureProperty("HitSlopLeft", HitSlopLeft(value))
}

// Password configures the corresponding node property.
func (element *Element) Password(value any) *Element {
	return element.configureProperty("Password", Password(value))
}

// Streaming configures the corresponding node property.
func (element *Element) Streaming(value any) *Element {
	return element.configureProperty("Streaming", Streaming(value))
}

// EstimatedItemHeight configures the corresponding node property.
func (element *Element) EstimatedItemHeight(value any) *Element {
	return element.configureProperty("EstimatedItemHeight", EstimatedItemHeight(value))
}

// Overscan configures the corresponding node property.
func (element *Element) Overscan(value any) *Element {
	return element.configureProperty("Overscan", Overscan(value))
}

// ListAlignment configures the corresponding node property.
func (element *Element) ListAlignment(value string) *Element {
	return element.configureProperty("ListAlignment", ListAlignment(value))
}

// FollowMode configures the corresponding node property.
func (element *Element) FollowMode(value string) *Element {
	return element.configureProperty("FollowMode", FollowMode(value))
}

// ShaderParameters configures the corresponding node property.
func (element *Element) ShaderParameters(value any) *Element {
	return element.configureProperty("ShaderParameters", ShaderParameters(value))
}

// Invalid configures the corresponding node property.
func (element *Element) Invalid(value any) *Element {
	return element.configureProperty("Invalid", Invalid(value))
}

// Role configures the corresponding node property.
func (element *Element) Role(value any) *Element {
	return element.configureProperty("Role", Role(value))
}

// TabIndex configures the corresponding node property.
func (element *Element) TabIndex(value any) *Element {
	return element.configureProperty("TabIndex", TabIndex(value))
}

// Overlay configures the corresponding node property.
func (element *Element) Overlay(value any) *Element {
	return element.configureProperty("Overlay", Overlay(value))
}

// FocusTrap configures the corresponding node property.
func (element *Element) FocusTrap(value any) *Element {
	return element.configureProperty("FocusTrap", FocusTrap(value))
}

// RestorePreviousFocus configures the corresponding node property.
func (element *Element) RestorePreviousFocus(value any) *Element {
	return element.configureProperty("RestorePreviousFocus", RestorePreviousFocus(value))
}

// AutoFocus configures the corresponding node property.
func (element *Element) AutoFocus(value any) *Element {
	return element.configureProperty("AutoFocus", AutoFocus(value))
}

// AriaModal configures the corresponding node property.
func (element *Element) AriaModal(value any) *Element {
	return element.configureProperty("AriaModal", AriaModal(value))
}

// DismissOnEscape configures the corresponding node property.
func (element *Element) DismissOnEscape(value any) *Element {
	return element.configureProperty("DismissOnEscape", DismissOnEscape(value))
}

// DismissOnPointerOutside configures the corresponding node property.
func (element *Element) DismissOnPointerOutside(value any) *Element {
	return element.configureProperty("DismissOnPointerOutside", DismissOnPointerOutside(value))
}

// TooltipText configures the corresponding node property.
func (element *Element) TooltipText(value any) *Element {
	return element.configureProperty("TooltipText", TooltipText(value))
}

// TooltipPlacement configures the corresponding node property.
func (element *Element) TooltipPlacement(value any) *Element {
	return element.configureProperty("TooltipPlacement", TooltipPlacement(value))
}

// TooltipDelay configures the corresponding node property.
func (element *Element) TooltipDelay(value any) *Element {
	return element.configureProperty("TooltipDelay", TooltipDelay(value))
}

// TooltipGap configures the corresponding node property.
func (element *Element) TooltipGap(value any) *Element {
	return element.configureProperty("TooltipGap", TooltipGap(value))
}

// TooltipViewportMargin configures the corresponding node property.
func (element *Element) TooltipViewportMargin(value any) *Element {
	return element.configureProperty("TooltipViewportMargin", TooltipViewportMargin(value))
}

// AnchorTarget configures the corresponding node property.
func (element *Element) AnchorTarget(value any) *Element {
	return element.configureProperty("AnchorTarget", AnchorTarget(value))
}

// AnchorPlacement configures the corresponding node property.
func (element *Element) AnchorPlacement(value any) *Element {
	return element.configureProperty("AnchorPlacement", AnchorPlacement(value))
}

// AnchorGap configures the corresponding node property.
func (element *Element) AnchorGap(value any) *Element {
	return element.configureProperty("AnchorGap", AnchorGap(value))
}

// ViewportMargin configures the corresponding node property.
func (element *Element) ViewportMargin(value any) *Element {
	return element.configureProperty("ViewportMargin", ViewportMargin(value))
}

// Keymap configures the corresponding node property.
func (element *Element) Keymap(value any) *Element {
	return element.configureProperty("Keymap", Keymap(value))
}

// Draggable configures the corresponding node property.
func (element *Element) Draggable(value any) *Element {
	return element.configureProperty("Draggable", Draggable(value))
}

// DropKinds configures the corresponding node property.
func (element *Element) DropKinds(value any) *Element {
	return element.configureProperty("DropKinds", DropKinds(value))
}
