// Code generated by optionsgen; DO NOT EDIT.

package ui

import (
	"github.com/egoist/quickgui/go/native"
	"github.com/egoist/quickgui/go/protocol"
)

func applyElementBinding(node *native.Node, props *Props, field elementBinding) {
	switch field {
	case 0:
		applyStyle(node, Style{ObjectFit: props.Style.ObjectFit})
	case 1:
		applyStyle(node, Style{WordWrap: props.Style.WordWrap})
	case 2:
		applyStyle(node, Style{TransitionTimingFunction: props.Style.TransitionTimingFunction})
	case 3:
		applyStyle(node, Style{PaddingInlineStart: props.Style.PaddingInlineStart})
	case 4:
		applyStyle(node, Style{PaddingInlineEnd: props.Style.PaddingInlineEnd})
	case 5:
		applyStyle(node, Style{MarginInlineStart: props.Style.MarginInlineStart})
	case 6:
		applyStyle(node, Style{MarginInlineEnd: props.Style.MarginInlineEnd})
	case 7:
		applyStyle(node, Style{BorderInlineStartWidth: props.Style.BorderInlineStartWidth})
	case 8:
		applyStyle(node, Style{BorderInlineEndWidth: props.Style.BorderInlineEndWidth})
	case 9:
		applyStyle(node, Style{AspectRatio: props.Style.AspectRatio})
	case 10:
		applyStyle(node, Style{GridColumn: props.Style.GridColumn})
	case 11:
		applyStyle(node, Style{GridRow: props.Style.GridRow})
	case 12:
		applyStyle(node, Style{BorderStartWidth: props.Style.BorderStartWidth})
	case 13:
		applyStyle(node, Style{BorderEndWidth: props.Style.BorderEndWidth})
	case 14:
		applyStyle(node, Style{Background: props.Style.Background})
	case 15:
		applyStyle(node, Style{BackgroundGradient: props.Style.BackgroundGradient})
	case 16:
		applyStyle(node, Style{TransitionProperty: props.Style.TransitionProperty})
	case 17:
		applyStyle(node, Style{TransitionDuration: props.Style.TransitionDuration})
	case 18:
		applyStyle(node, Style{TransitionEasing: props.Style.TransitionEasing})
	case 19:
		applyStyle(node, Style{TransitionMaxFps: props.Style.TransitionMaxFps})
	case 20:
		applyStyle(node, Style{MarkdownCodeBackground: props.Style.MarkdownCodeBackground})
	case 21:
		applyStyle(node, Style{MarkdownBorderColor: props.Style.MarkdownBorderColor})
	case 22:
		applyStyle(node, Style{MarkdownMutedColor: props.Style.MarkdownMutedColor})
	case 23:
		applyStyle(node, Style{MarkdownLinkColor: props.Style.MarkdownLinkColor})
	case 24:
		applyStyle(node, Style{MarkdownCodeTextColor: props.Style.MarkdownCodeTextColor})
	case 25:
		applyStyle(node, Style{MarkdownBlockGap: props.Style.MarkdownBlockGap})
	case 26:
		applyStyle(node, Style{MarkdownCodeFontSize: props.Style.MarkdownCodeFontSize})
	case 27:
		applyStyle(node, Style{ScrollToEndRevision: props.Style.ScrollToEndRevision})
	case 28:
		applyStyle(node, Style{TextDecoration: props.Style.TextDecoration})
	case 29:
		applyStyle(node, Style{Invalid: props.Style.Invalid})
	case 30:
		applyStyle(node, Style{Dragging: props.Style.Dragging})
	case 31:
		applyStyle(node, Style{DragOver: props.Style.DragOver})
	case 32:
		applyStyle(node, Style{FocusWithin: props.Style.FocusWithin})
	case 33:
		applyStyle(node, Style{GroupActive: props.Style.GroupActive, groupActiveRules: props.Style.groupActiveRules})
	case 35:
		applyStyle(node, Style{GridTemplateColumns: props.Style.GridTemplateColumns})
	case 36:
		applyStyle(node, Style{GridTemplateRows: props.Style.GridTemplateRows})
	case 37:
		applyStyle(node, Style{GridAutoFlow: props.Style.GridAutoFlow})
	case 38:
		applyStyle(node, Style{GridColumnStart: props.Style.GridColumnStart})
	case 39:
		applyStyle(node, Style{GridColumnEnd: props.Style.GridColumnEnd})
	case 40:
		applyStyle(node, Style{GridColumnSpan: props.Style.GridColumnSpan})
	case 41:
		applyStyle(node, Style{GridRowStart: props.Style.GridRowStart})
	case 42:
		applyStyle(node, Style{GridRowEnd: props.Style.GridRowEnd})
	case 43:
		applyStyle(node, Style{GridRowSpan: props.Style.GridRowSpan})
	case 44:
		applyStyle(node, Style{PaddingStart: props.Style.PaddingStart})
	case 45:
		applyStyle(node, Style{PaddingEnd: props.Style.PaddingEnd})
	case 46:
		applyStyle(node, Style{MarginStart: props.Style.MarginStart})
	case 47:
		applyStyle(node, Style{MarginEnd: props.Style.MarginEnd})
	case 48:
		applyStyle(node, Style{BorderTopWidth: props.Style.BorderTopWidth})
	case 49:
		applyStyle(node, Style{BorderRightWidth: props.Style.BorderRightWidth})
	case 50:
		applyStyle(node, Style{BorderBottomWidth: props.Style.BorderBottomWidth})
	case 51:
		applyStyle(node, Style{BorderLeftWidth: props.Style.BorderLeftWidth})
	case 52:
		applyStyle(node, Style{BorderTopLeftRadius: props.Style.BorderTopLeftRadius})
	case 53:
		applyStyle(node, Style{BorderTopRightRadius: props.Style.BorderTopRightRadius})
	case 54:
		applyStyle(node, Style{BorderBottomLeftRadius: props.Style.BorderBottomLeftRadius})
	case 55:
		applyStyle(node, Style{BorderBottomRightRadius: props.Style.BorderBottomRightRadius})
	case 56:
		applyStyle(node, Style{BorderStyle: props.Style.BorderStyle})
	case 57:
		applyStyle(node, Style{BoxShadow: props.Style.BoxShadow})
	case 58:
		applyStyle(node, Style{TextShadow: props.Style.TextShadow})
	case 59:
		applyStyle(node, Style{TextDecorationLine: props.Style.TextDecorationLine})
	case 60:
		applyStyle(node, Style{TextDecorationColor: props.Style.TextDecorationColor})
	case 61:
		applyStyle(node, Style{TextDecorationStyle: props.Style.TextDecorationStyle})
	case 62:
		applyStyle(node, Style{TextDecorationThickness: props.Style.TextDecorationThickness})
	case 63:
		applyStyle(node, Style{WordSpacing: props.Style.WordSpacing})
	case 64:
		applyStyle(node, Style{WordBreak: props.Style.WordBreak})
	case 65:
		applyStyle(node, Style{OverflowWrap: props.Style.OverflowWrap})
	case 66:
		applyStyle(node, Style{Hyphens: props.Style.Hyphens})
	case 67:
		applyStyle(node, Style{TextDirection: props.Style.TextDirection})
	case 68:
		applyStyle(node, Style{Direction: props.Style.Direction})
	case 69:
		applyStyle(node, Style{BackgroundImage: props.Style.BackgroundImage})
	case 70:
		applyStyle(node, Style{BackgroundSize: props.Style.BackgroundSize})
	case 71:
		applyStyle(node, Style{BackgroundRepeat: props.Style.BackgroundRepeat})
	case 72:
		applyStyle(node, Style{BackgroundPosition: props.Style.BackgroundPosition})
	case 73:
		applyStyle(node, Style{Filter: props.Style.Filter})
	case 74:
		applyStyle(node, Style{BackdropFilter: props.Style.BackdropFilter})
	case 75:
		applyStyle(node, Style{MixBlendMode: props.Style.MixBlendMode})
	case 76:
		applyStyle(node, Style{Transition: props.Style.Transition})
	case 77:
		applyStyle(node, Style{ScrollSnapType: props.Style.ScrollSnapType})
	case 78:
		applyStyle(node, Style{ScrollSnapX: props.Style.ScrollSnapX})
	case 79:
		applyStyle(node, Style{ScrollSnapY: props.Style.ScrollSnapY})
	case 80:
		applyStyle(node, Style{ScrollSnapAlign: props.Style.ScrollSnapAlign})
	case 81:
		applyStyle(node, Style{ScrollSnapStop: props.Style.ScrollSnapStop})
	case 82:
		applyStyle(node, Style{Display: props.Style.Display})
	case 83:
		applyStyle(node, Style{Flex: props.Style.Flex})
	case 84:
		applyStyle(node, Style{FlexDirection: props.Style.FlexDirection})
	case 85:
		applyStyle(node, Style{FlexWrap: props.Style.FlexWrap})
	case 86:
		applyStyle(node, Style{FlexGrow: props.Style.FlexGrow})
	case 87:
		applyStyle(node, Style{FlexShrink: props.Style.FlexShrink})
	case 88:
		applyStyle(node, Style{FlexBasis: props.Style.FlexBasis})
	case 89:
		applyStyle(node, Style{AlignItems: props.Style.AlignItems})
	case 90:
		applyStyle(node, Style{AlignSelf: props.Style.AlignSelf})
	case 91:
		applyStyle(node, Style{JustifyContent: props.Style.JustifyContent})
	case 92:
		applyStyle(node, Style{AlignContent: props.Style.AlignContent})
	case 93:
		applyStyle(node, Style{Gap: props.Style.Gap})
	case 94:
		applyStyle(node, Style{ColumnGap: props.Style.ColumnGap})
	case 95:
		applyStyle(node, Style{RowGap: props.Style.RowGap})
	case 96:
		applyStyle(node, Style{Width: props.Style.Width})
	case 97:
		applyStyle(node, Style{Height: props.Style.Height})
	case 98:
		applyStyle(node, Style{MinWidth: props.Style.MinWidth})
	case 99:
		applyStyle(node, Style{MinHeight: props.Style.MinHeight})
	case 100:
		applyStyle(node, Style{MaxWidth: props.Style.MaxWidth})
	case 101:
		applyStyle(node, Style{MaxHeight: props.Style.MaxHeight})
	case 102:
		applyStyle(node, Style{Padding: props.Style.Padding})
	case 103:
		applyStyle(node, Style{PaddingTop: props.Style.PaddingTop})
	case 104:
		applyStyle(node, Style{PaddingRight: props.Style.PaddingRight})
	case 105:
		applyStyle(node, Style{PaddingBottom: props.Style.PaddingBottom})
	case 106:
		applyStyle(node, Style{PaddingLeft: props.Style.PaddingLeft})
	case 107:
		applyStyle(node, Style{Margin: props.Style.Margin})
	case 108:
		applyStyle(node, Style{MarginTop: props.Style.MarginTop})
	case 109:
		applyStyle(node, Style{MarginRight: props.Style.MarginRight})
	case 110:
		applyStyle(node, Style{MarginBottom: props.Style.MarginBottom})
	case 111:
		applyStyle(node, Style{MarginLeft: props.Style.MarginLeft})
	case 112:
		applyStyle(node, Style{BackgroundColor: props.Style.BackgroundColor})
	case 113:
		applyStyle(node, Style{TextColor: props.Style.TextColor})
	case 114:
		applyStyle(node, Style{Opacity: props.Style.Opacity})
	case 115:
		applyStyle(node, Style{BorderWidth: props.Style.BorderWidth})
	case 116:
		applyStyle(node, Style{BorderColor: props.Style.BorderColor})
	case 117:
		applyStyle(node, Style{BorderRadius: props.Style.BorderRadius})
	case 118:
		applyStyle(node, Style{FontSize: props.Style.FontSize})
	case 119:
		applyStyle(node, Style{FontFamily: props.Style.FontFamily})
	case 120:
		applyStyle(node, Style{FontWeight: props.Style.FontWeight})
	case 121:
		applyStyle(node, Style{LineHeight: props.Style.LineHeight})
	case 122:
		applyStyle(node, Style{TextAlign: props.Style.TextAlign})
	case 123:
		applyStyle(node, Style{Cursor: props.Style.Cursor})
	case 124:
		applyStyle(node, Style{AppRegion: props.Style.AppRegion})
	case 125:
		applyStyle(node, Style{UserSelect: props.Style.UserSelect})
	case 126:
		applyStyle(node, Style{Position: props.Style.Position})
	case 127:
		applyStyle(node, Style{Overflow: props.Style.Overflow})
	case 128:
		applyStyle(node, Style{OverflowX: props.Style.OverflowX})
	case 129:
		applyStyle(node, Style{OverflowY: props.Style.OverflowY})
	case 130:
		applyStyle(node, Style{Visibility: props.Style.Visibility})
	case 131:
		applyStyle(node, Style{LetterSpacing: props.Style.LetterSpacing})
	case 132:
		applyStyle(node, Style{TextTransform: props.Style.TextTransform})
	case 133:
		applyStyle(node, Style{LineClamp: props.Style.LineClamp})
	case 134:
		applyStyle(node, Style{WhiteSpace: props.Style.WhiteSpace})
	case 135:
		applyStyle(node, Style{TextOverflow: props.Style.TextOverflow})
	case 136:
		applyStyle(node, Style{Top: props.Style.Top})
	case 137:
		applyStyle(node, Style{Right: props.Style.Right})
	case 138:
		applyStyle(node, Style{Bottom: props.Style.Bottom})
	case 139:
		applyStyle(node, Style{Left: props.Style.Left})
	case 140:
		applyStyle(node, Style{Outline: props.Style.Outline})
	case 141:
		applyStyle(node, Style{OutlineWidth: props.Style.OutlineWidth})
	case 142:
		applyStyle(node, Style{OutlineColor: props.Style.OutlineColor})
	case 143:
		applyStyle(node, Style{OutlineOffset: props.Style.OutlineOffset})
	case 144:
		applyStyle(node, Style{OutlineStyle: props.Style.OutlineStyle})
	case 145:
		applyStyle(node, Style{Transform: props.Style.Transform})
	case 146:
		applyStyle(node, Style{TransformOrigin: props.Style.TransformOrigin})
	case 147:
		applyStyle(node, Style{Hover: props.Style.Hover})
	case 148:
		applyStyle(node, Style{Active: props.Style.Active})
	case 149:
		applyStyle(node, Style{Focus: props.Style.Focus})
	case 150:
		applyStyle(node, Style{Disabled: props.Style.Disabled})
	case 151:
		applyStyle(node, Style{Selected: props.Style.Selected})
	case 152:
		applyStyle(node, Style{GroupHover: props.Style.GroupHover, groupHoverRules: props.Style.groupHoverRules})
	case propertyBindingOffset + 2:
		setFluentListener(node, protocol.EventClick, props.OnClick)
	case propertyBindingOffset + 3:
		setFluentListener(node, protocol.EventMouseEnter, props.OnMouseEnter)
	case propertyBindingOffset + 4:
		setFluentListener(node, protocol.EventMouseLeave, props.OnMouseLeave)
	case propertyBindingOffset + 5:
		setFluentListener(node, protocol.EventInput, props.OnInput)
	case propertyBindingOffset + 6:
		setFluentListener(node, protocol.EventSubmit, props.OnSubmit)
	case propertyBindingOffset + 7:
		setFluentListener(node, protocol.EventDismiss, props.OnDismiss)
	case propertyBindingOffset + 8:
		setFluentListener(node, protocol.EventTerminal, props.OnStatus)
	case propertyBindingOffset + 9:
		setFluentListener(node, protocol.EventPointer, props.OnPointer)
	case propertyBindingOffset + 10:
		setFluentListener(node, protocol.EventPresentation, props.OnPresentationChange)
	case propertyBindingOffset + 11:
		setFluentListener(node, protocol.EventMenuSelect, props.OnSelect)
	case propertyBindingOffset + 12:
		setFluentListener(node, protocol.EventKeyDown, props.OnKeyDown)
	case propertyBindingOffset + 13:
		setFluentListener(node, protocol.EventKeyUp, props.OnKeyUp)
	case propertyBindingOffset + 14:
		setFluentListener(node, protocol.EventMouseDown, props.OnMouseDown)
	case propertyBindingOffset + 15:
		setFluentListener(node, protocol.EventMouseUp, props.OnMouseUp)
	case propertyBindingOffset + 16:
		setFluentListener(node, protocol.EventMouseMove, props.OnMouseMove)
	case propertyBindingOffset + 17:
		setFluentListener(node, protocol.EventDoubleClick, props.OnDoubleClick)
	case propertyBindingOffset + 18:
		setFluentListener(node, protocol.EventWheel, props.OnWheel)
	case propertyBindingOffset + 19:
		setFluentListener(node, protocol.EventContextMenu, props.OnContextMenu)
	case propertyBindingOffset + 20:
		setFluentListener(node, protocol.EventPinch, props.OnPinch)
	case propertyBindingOffset + 21:
		setFluentListener(node, protocol.EventRotate, props.OnRotate)
	case propertyBindingOffset + 22:
		setFluentListener(node, protocol.EventSmartMagnify, props.OnSmartMagnify)
	case propertyBindingOffset + 23:
		setFluentListener(node, protocol.EventPressure, props.OnPressure)
	case propertyBindingOffset + 24:
		setFluentListener(node, protocol.EventFocus, props.OnFocus)
	case propertyBindingOffset + 25:
		setFluentListener(node, protocol.EventBlur, props.OnBlur)
	case propertyBindingOffset + 26:
		setFluentListener(node, protocol.EventAction, props.OnAction)
	case propertyBindingOffset + 27:
		setFluentListener(node, protocol.EventDragStart, props.OnDragStart)
	case propertyBindingOffset + 28:
		setFluentListener(node, protocol.EventDragEnd, props.OnDragEnd)
	case propertyBindingOffset + 29:
		setFluentListener(node, protocol.EventDrop, props.OnDrop)
	case propertyBindingOffset + 30:
		setFluentListener(node, protocol.EventFilesDropped, props.OnFilesDropped)
	case propertyBindingOffset + 31:
		setFluentListener(node, protocol.EventComponentChange, props.OnComponentChange)
	case propertyBindingOffset + 32:
		setFluentListener(node, protocol.EventCommit, props.OnCommit)
	case propertyBindingOffset + 33:
		applyPropValues(node, Props{Disabled: props.Disabled})
	case propertyBindingOffset + 34:
		applyPropValues(node, Props{Value: props.Value})
	case propertyBindingOffset + 35:
		applyPropValues(node, Props{Placeholder: props.Placeholder})
	case propertyBindingOffset + 36:
		applyPropValues(node, Props{Multiline: props.Multiline})
	case propertyBindingOffset + 37:
		applyPropValues(node, Props{AriaLabel: props.AriaLabel})
	case propertyBindingOffset + 38:
		applyPropValues(node, Props{Selected: props.Selected})
	case propertyBindingOffset + 39:
		applyPropValues(node, Props{Group: props.Group})
	case propertyBindingOffset + 40:
		applyPropValues(node, Props{FocusOnPointer: props.FocusOnPointer})
	case propertyBindingOffset + 41:
		applyPropValues(node, Props{FocusableWhenDisabled: props.FocusableWhenDisabled})
	case propertyBindingOffset + 42:
		applyPropValues(node, Props{HitSlop: props.HitSlop})
	case propertyBindingOffset + 43:
		applyPropValues(node, Props{HitSlopTop: props.HitSlopTop})
	case propertyBindingOffset + 44:
		applyPropValues(node, Props{HitSlopRight: props.HitSlopRight})
	case propertyBindingOffset + 45:
		applyPropValues(node, Props{HitSlopBottom: props.HitSlopBottom})
	case propertyBindingOffset + 46:
		applyPropValues(node, Props{HitSlopLeft: props.HitSlopLeft})
	case propertyBindingOffset + 48:
		applyPropValues(node, Props{Password: props.Password})
	case propertyBindingOffset + 49:
		applyPropValues(node, Props{Streaming: props.Streaming})
	case propertyBindingOffset + 50:
		applyPropValues(node, Props{EstimatedItemHeight: props.EstimatedItemHeight})
	case propertyBindingOffset + 51:
		applyPropValues(node, Props{Overscan: props.Overscan})
	case propertyBindingOffset + 52:
		applyPropValues(node, Props{ListAlignment: props.ListAlignment})
	case propertyBindingOffset + 53:
		applyPropValues(node, Props{FollowMode: props.FollowMode})
	case propertyBindingOffset + 54:
		applyPropValues(node, Props{ObjectFit: props.ObjectFit})
	case propertyBindingOffset + 55:
		applyPropValues(node, Props{ShaderParameters: props.ShaderParameters})
	case propertyBindingOffset + 56:
		applyPropValues(node, Props{Invalid: props.Invalid})
	case propertyBindingOffset + 57:
		applyPropValues(node, Props{Role: props.Role})
	case propertyBindingOffset + 58:
		applyPropValues(node, Props{TabIndex: props.TabIndex})
	case propertyBindingOffset + 59:
		applyPropValues(node, Props{Overlay: props.Overlay})
	case propertyBindingOffset + 60:
		applyPropValues(node, Props{FocusTrap: props.FocusTrap})
	case propertyBindingOffset + 61:
		applyPropValues(node, Props{RestorePreviousFocus: props.RestorePreviousFocus})
	case propertyBindingOffset + 62:
		applyPropValues(node, Props{AutoFocus: props.AutoFocus})
	case propertyBindingOffset + 63:
		applyPropValues(node, Props{AriaModal: props.AriaModal})
	case propertyBindingOffset + 64:
		applyPropValues(node, Props{DismissOnEscape: props.DismissOnEscape})
	case propertyBindingOffset + 65:
		applyPropValues(node, Props{DismissOnPointerOutside: props.DismissOnPointerOutside})
	case propertyBindingOffset + 66:
		applyPropValues(node, Props{TooltipText: props.TooltipText})
	case propertyBindingOffset + 67:
		applyPropValues(node, Props{TooltipPlacement: props.TooltipPlacement})
	case propertyBindingOffset + 68:
		applyPropValues(node, Props{TooltipDelay: props.TooltipDelay})
	case propertyBindingOffset + 69:
		applyPropValues(node, Props{TooltipGap: props.TooltipGap})
	case propertyBindingOffset + 70:
		applyPropValues(node, Props{TooltipViewportMargin: props.TooltipViewportMargin})
	case propertyBindingOffset + 71:
		applyPropValues(node, Props{AnchorTarget: props.AnchorTarget})
	case propertyBindingOffset + 72:
		applyPropValues(node, Props{AnchorPlacement: props.AnchorPlacement})
	case propertyBindingOffset + 73:
		applyPropValues(node, Props{AnchorGap: props.AnchorGap})
	case propertyBindingOffset + 74:
		applyPropValues(node, Props{ViewportMargin: props.ViewportMargin})
	case propertyBindingOffset + 75:
		applyPropValues(node, Props{Keymap: props.Keymap})
	case propertyBindingOffset + 76:
		applyPropValues(node, Props{Draggable: props.Draggable})
	case propertyBindingOffset + 77:
		applyPropValues(node, Props{DropKinds: props.DropKinds})
	}
}
