// Code generated by optionsgen; DO NOT EDIT.

package ui

import "github.com/egoist/quickgui/go/native"

// GridTemplateColumns sets the corresponding style property.
func GridTemplateColumns(value string) StyleOption {
	return func(style *Style) { style.GridTemplateColumns = value }
}

// GridTemplateRows sets the corresponding style property.
func GridTemplateRows(value string) StyleOption {
	return func(style *Style) { style.GridTemplateRows = value }
}

// GridAutoFlow sets the corresponding style property.
func GridAutoFlow(value string) StyleOption {
	return func(style *Style) { style.GridAutoFlow = value }
}

// GridColumnStart sets the corresponding style property.
func GridColumnStart(value any) StyleOption {
	return func(style *Style) { style.GridColumnStart = value }
}

// GridColumnEnd sets the corresponding style property.
func GridColumnEnd(value any) StyleOption {
	return func(style *Style) { style.GridColumnEnd = value }
}

// GridColumnSpan sets the corresponding style property.
func GridColumnSpan(value any) StyleOption {
	return func(style *Style) { style.GridColumnSpan = value }
}

// GridRowStart sets the corresponding style property.
func GridRowStart(value any) StyleOption {
	return func(style *Style) { style.GridRowStart = value }
}

// GridRowEnd sets the corresponding style property.
func GridRowEnd(value any) StyleOption {
	return func(style *Style) { style.GridRowEnd = value }
}

// GridRowSpan sets the corresponding style property.
func GridRowSpan(value any) StyleOption {
	return func(style *Style) { style.GridRowSpan = value }
}

// PaddingStart sets the corresponding style property.
func PaddingStart(value any) StyleOption {
	return func(style *Style) { style.PaddingStart = value }
}

// PaddingEnd sets the corresponding style property.
func PaddingEnd(value any) StyleOption {
	return func(style *Style) { style.PaddingEnd = value }
}

// MarginStart sets the corresponding style property.
func MarginStart(value any) StyleOption {
	return func(style *Style) { style.MarginStart = value }
}

// MarginEnd sets the corresponding style property.
func MarginEnd(value any) StyleOption {
	return func(style *Style) { style.MarginEnd = value }
}

// BorderTopWidth sets the corresponding style property.
func BorderTopWidth(value any) StyleOption {
	return func(style *Style) { style.BorderTopWidth = value }
}

// BorderRightWidth sets the corresponding style property.
func BorderRightWidth(value any) StyleOption {
	return func(style *Style) { style.BorderRightWidth = value }
}

// BorderBottomWidth sets the corresponding style property.
func BorderBottomWidth(value any) StyleOption {
	return func(style *Style) { style.BorderBottomWidth = value }
}

// BorderLeftWidth sets the corresponding style property.
func BorderLeftWidth(value any) StyleOption {
	return func(style *Style) { style.BorderLeftWidth = value }
}

// BorderTopLeftRadius sets the corresponding style property.
func BorderTopLeftRadius(value any) StyleOption {
	return func(style *Style) { style.BorderTopLeftRadius = value }
}

// BorderTopRightRadius sets the corresponding style property.
func BorderTopRightRadius(value any) StyleOption {
	return func(style *Style) { style.BorderTopRightRadius = value }
}

// BorderBottomLeftRadius sets the corresponding style property.
func BorderBottomLeftRadius(value any) StyleOption {
	return func(style *Style) { style.BorderBottomLeftRadius = value }
}

// BorderBottomRightRadius sets the corresponding style property.
func BorderBottomRightRadius(value any) StyleOption {
	return func(style *Style) { style.BorderBottomRightRadius = value }
}

// BorderStyle sets the corresponding style property.
func BorderStyle(value string) StyleOption {
	return func(style *Style) { style.BorderStyle = value }
}

// BoxShadow sets the corresponding style property.
func BoxShadow(value string) StyleOption {
	return func(style *Style) { style.BoxShadow = value }
}

// TextShadow sets the corresponding style property.
func TextShadow(value string) StyleOption {
	return func(style *Style) { style.TextShadow = value }
}

// TextDecorationLine sets the corresponding style property.
func TextDecorationLine(value string) StyleOption {
	return func(style *Style) { style.TextDecorationLine = value }
}

// TextDecorationColor sets the corresponding style property.
func TextDecorationColor(value any) StyleOption {
	return func(style *Style) { style.TextDecorationColor = value }
}

// TextDecorationStyle sets the corresponding style property.
func TextDecorationStyle(value string) StyleOption {
	return func(style *Style) { style.TextDecorationStyle = value }
}

// TextDecorationThickness sets the corresponding style property.
func TextDecorationThickness(value any) StyleOption {
	return func(style *Style) { style.TextDecorationThickness = value }
}

// WordSpacing sets the corresponding style property.
func WordSpacing(value any) StyleOption {
	return func(style *Style) { style.WordSpacing = value }
}

// WordBreak sets the corresponding style property.
func WordBreak(value string) StyleOption {
	return func(style *Style) { style.WordBreak = value }
}

// OverflowWrap sets the corresponding style property.
func OverflowWrap(value string) StyleOption {
	return func(style *Style) { style.OverflowWrap = value }
}

// Hyphens sets the corresponding style property.
func Hyphens(value string) StyleOption {
	return func(style *Style) { style.Hyphens = value }
}

// TextDirection sets the corresponding style property.
func TextDirection(value string) StyleOption {
	return func(style *Style) { style.TextDirection = value }
}

// Direction sets the corresponding style property.
func Direction(value string) StyleOption {
	return func(style *Style) { style.Direction = value }
}

// BackgroundImage sets the corresponding style property.
func BackgroundImage(value string) StyleOption {
	return func(style *Style) { style.BackgroundImage = value }
}

// BackgroundSize sets the corresponding style property.
func BackgroundSize(value string) StyleOption {
	return func(style *Style) { style.BackgroundSize = value }
}

// BackgroundRepeat sets the corresponding style property.
func BackgroundRepeat(value string) StyleOption {
	return func(style *Style) { style.BackgroundRepeat = value }
}

// BackgroundPosition sets the corresponding style property.
func BackgroundPosition(value string) StyleOption {
	return func(style *Style) { style.BackgroundPosition = value }
}

// Filter sets the corresponding style property.
func Filter(value string) StyleOption {
	return func(style *Style) { style.Filter = value }
}

// BackdropFilter sets the corresponding style property.
func BackdropFilter(value string) StyleOption {
	return func(style *Style) { style.BackdropFilter = value }
}

// MixBlendMode sets the corresponding style property.
func MixBlendMode(value string) StyleOption {
	return func(style *Style) { style.MixBlendMode = value }
}

// Transition sets the corresponding style property.
func Transition(value string) StyleOption {
	return func(style *Style) { style.Transition = value }
}

// ScrollSnapType sets the corresponding style property.
func ScrollSnapType(value string) StyleOption {
	return func(style *Style) { style.ScrollSnapType = value }
}

// ScrollSnapAlign sets the corresponding style property.
func ScrollSnapAlign(value string) StyleOption {
	return func(style *Style) { style.ScrollSnapAlign = value }
}

// ScrollSnapStop sets the corresponding style property.
func ScrollSnapStop(value string) StyleOption {
	return func(style *Style) { style.ScrollSnapStop = value }
}

// Display sets the corresponding style property.
func Display(value string) StyleOption {
	return func(style *Style) { style.Display = value }
}

// Flex sets the corresponding style property.
func Flex(value any) StyleOption {
	return func(style *Style) { style.Flex = value }
}

// FlexDirection sets the corresponding style property.
func FlexDirection(value string) StyleOption {
	return func(style *Style) { style.FlexDirection = value }
}

// FlexWrap sets the corresponding style property.
func FlexWrap(value string) StyleOption {
	return func(style *Style) { style.FlexWrap = value }
}

// FlexGrow sets the corresponding style property.
func FlexGrow(value any) StyleOption {
	return func(style *Style) { style.FlexGrow = value }
}

// FlexShrink sets the corresponding style property.
func FlexShrink(value any) StyleOption {
	return func(style *Style) { style.FlexShrink = value }
}

// FlexBasis sets the corresponding style property.
func FlexBasis(value any) StyleOption {
	return func(style *Style) { style.FlexBasis = value }
}

// AlignItems sets the corresponding style property.
func AlignItems(value string) StyleOption {
	return func(style *Style) { style.AlignItems = value }
}

// AlignSelf sets the corresponding style property.
func AlignSelf(value string) StyleOption {
	return func(style *Style) { style.AlignSelf = value }
}

// JustifyContent sets the corresponding style property.
func JustifyContent(value string) StyleOption {
	return func(style *Style) { style.JustifyContent = value }
}

// AlignContent sets the corresponding style property.
func AlignContent(value string) StyleOption {
	return func(style *Style) { style.AlignContent = value }
}

// Gap sets the corresponding style property.
func Gap(value any) StyleOption {
	return func(style *Style) { style.Gap = value }
}

// ColumnGap sets the corresponding style property.
func ColumnGap(value any) StyleOption {
	return func(style *Style) { style.ColumnGap = value }
}

// RowGap sets the corresponding style property.
func RowGap(value any) StyleOption {
	return func(style *Style) { style.RowGap = value }
}

// Width sets the corresponding style property.
func Width(value any) StyleOption {
	return func(style *Style) { style.Width = value }
}

// Height sets the corresponding style property.
func Height(value any) StyleOption {
	return func(style *Style) { style.Height = value }
}

// MinWidth sets the corresponding style property.
func MinWidth(value any) StyleOption {
	return func(style *Style) { style.MinWidth = value }
}

// MinHeight sets the corresponding style property.
func MinHeight(value any) StyleOption {
	return func(style *Style) { style.MinHeight = value }
}

// MaxWidth sets the corresponding style property.
func MaxWidth(value any) StyleOption {
	return func(style *Style) { style.MaxWidth = value }
}

// MaxHeight sets the corresponding style property.
func MaxHeight(value any) StyleOption {
	return func(style *Style) { style.MaxHeight = value }
}

// Padding sets the corresponding style property.
func Padding(value any) StyleOption {
	return func(style *Style) { style.Padding = value }
}

// PaddingTop sets the corresponding style property.
func PaddingTop(value any) StyleOption {
	return func(style *Style) { style.PaddingTop = value }
}

// PaddingRight sets the corresponding style property.
func PaddingRight(value any) StyleOption {
	return func(style *Style) { style.PaddingRight = value }
}

// PaddingBottom sets the corresponding style property.
func PaddingBottom(value any) StyleOption {
	return func(style *Style) { style.PaddingBottom = value }
}

// PaddingLeft sets the corresponding style property.
func PaddingLeft(value any) StyleOption {
	return func(style *Style) { style.PaddingLeft = value }
}

// Margin sets the corresponding style property.
func Margin(value any) StyleOption {
	return func(style *Style) { style.Margin = value }
}

// MarginTop sets the corresponding style property.
func MarginTop(value any) StyleOption {
	return func(style *Style) { style.MarginTop = value }
}

// MarginRight sets the corresponding style property.
func MarginRight(value any) StyleOption {
	return func(style *Style) { style.MarginRight = value }
}

// MarginBottom sets the corresponding style property.
func MarginBottom(value any) StyleOption {
	return func(style *Style) { style.MarginBottom = value }
}

// MarginLeft sets the corresponding style property.
func MarginLeft(value any) StyleOption {
	return func(style *Style) { style.MarginLeft = value }
}

// BackgroundColor sets the corresponding style property.
func BackgroundColor(value any) StyleOption {
	return func(style *Style) { style.BackgroundColor = value }
}

// Color sets the corresponding style property.
func Color(value any) StyleOption {
	return func(style *Style) { style.Color = value }
}

// Opacity sets the corresponding style property.
func Opacity(value any) StyleOption {
	return func(style *Style) { style.Opacity = value }
}

// BorderWidth sets the corresponding style property.
func BorderWidth(value any) StyleOption {
	return func(style *Style) { style.BorderWidth = value }
}

// BorderColor sets the corresponding style property.
func BorderColor(value any) StyleOption {
	return func(style *Style) { style.BorderColor = value }
}

// BorderRadius sets the corresponding style property.
func BorderRadius(value any) StyleOption {
	return func(style *Style) { style.BorderRadius = value }
}

// FontSize sets the corresponding style property.
func FontSize(value any) StyleOption {
	return func(style *Style) { style.FontSize = value }
}

// FontFamily sets the corresponding style property.
func FontFamily(value string) StyleOption {
	return func(style *Style) { style.FontFamily = value }
}

// FontWeight sets the corresponding style property.
func FontWeight(value any) StyleOption {
	return func(style *Style) { style.FontWeight = value }
}

// LineHeight sets the corresponding style property.
func LineHeight(value any) StyleOption {
	return func(style *Style) { style.LineHeight = value }
}

// TextAlign sets the corresponding style property.
func TextAlign(value string) StyleOption {
	return func(style *Style) { style.TextAlign = value }
}

// Cursor sets the corresponding style property.
func Cursor(value string) StyleOption {
	return func(style *Style) { style.Cursor = value }
}

// AppRegion sets the corresponding style property.
func AppRegion(value string) StyleOption {
	return func(style *Style) { style.AppRegion = value }
}

// UserSelect sets the corresponding style property.
func UserSelect(value string) StyleOption {
	return func(style *Style) { style.UserSelect = value }
}

// Position sets the corresponding style property.
func Position(value string) StyleOption {
	return func(style *Style) { style.Position = value }
}

// Overflow sets the corresponding style property.
func Overflow(value string) StyleOption {
	return func(style *Style) { style.Overflow = value }
}

// OverflowX sets the corresponding style property.
func OverflowX(value string) StyleOption {
	return func(style *Style) { style.OverflowX = value }
}

// OverflowY sets the corresponding style property.
func OverflowY(value string) StyleOption {
	return func(style *Style) { style.OverflowY = value }
}

// Visibility sets the corresponding style property.
func Visibility(value string) StyleOption {
	return func(style *Style) { style.Visibility = value }
}

// LetterSpacing sets the corresponding style property.
func LetterSpacing(value any) StyleOption {
	return func(style *Style) { style.LetterSpacing = value }
}

// TextTransform sets the corresponding style property.
func TextTransform(value string) StyleOption {
	return func(style *Style) { style.TextTransform = value }
}

// LineClamp sets the corresponding style property.
func LineClamp(value any) StyleOption {
	return func(style *Style) { style.LineClamp = value }
}

// WhiteSpace sets the corresponding style property.
func WhiteSpace(value string) StyleOption {
	return func(style *Style) { style.WhiteSpace = value }
}

// TextOverflow sets the corresponding style property.
func TextOverflow(value string) StyleOption {
	return func(style *Style) { style.TextOverflow = value }
}

// Top sets the corresponding style property.
func Top(value any) StyleOption {
	return func(style *Style) { style.Top = value }
}

// Right sets the corresponding style property.
func Right(value any) StyleOption {
	return func(style *Style) { style.Right = value }
}

// Bottom sets the corresponding style property.
func Bottom(value any) StyleOption {
	return func(style *Style) { style.Bottom = value }
}

// Left sets the corresponding style property.
func Left(value any) StyleOption {
	return func(style *Style) { style.Left = value }
}

// Outline sets the corresponding style property.
func Outline(value string) StyleOption {
	return func(style *Style) { style.Outline = value }
}

// OutlineWidth sets the corresponding style property.
func OutlineWidth(value any) StyleOption {
	return func(style *Style) { style.OutlineWidth = value }
}

// OutlineColor sets the corresponding style property.
func OutlineColor(value any) StyleOption {
	return func(style *Style) { style.OutlineColor = value }
}

// OutlineOffset sets the corresponding style property.
func OutlineOffset(value any) StyleOption {
	return func(style *Style) { style.OutlineOffset = value }
}

// OutlineStyle sets the corresponding style property.
func OutlineStyle(value string) StyleOption {
	return func(style *Style) { style.OutlineStyle = value }
}

// Transform sets the corresponding style property.
func Transform(value string) StyleOption {
	return func(style *Style) { style.Transform = value }
}

// TransformOrigin sets the corresponding style property.
func TransformOrigin(value string) StyleOption {
	return func(style *Style) { style.TransformOrigin = value }
}

// Hover configures the Hover interaction style.
func Hover(options ...StyleOption) StyleOption {
	return func(style *Style) {
		nested := &Style{}
		for _, option := range options {
			option(nested)
		}
		style.Hover = nested
	}
}

// Active configures the Active interaction style.
func Active(options ...StyleOption) StyleOption {
	return func(style *Style) {
		nested := &Style{}
		for _, option := range options {
			option(nested)
		}
		style.Active = nested
	}
}

// Focus configures the Focus interaction style.
func Focus(options ...StyleOption) StyleOption {
	return func(style *Style) {
		nested := &Style{}
		for _, option := range options {
			option(nested)
		}
		style.Focus = nested
	}
}

// DisabledStyle configures the Disabled interaction style.
func DisabledStyle(options ...StyleOption) StyleOption {
	return func(style *Style) {
		nested := &Style{}
		for _, option := range options {
			option(nested)
		}
		style.Disabled = nested
	}
}

// SelectedStyle configures the Selected interaction style.
func SelectedStyle(options ...StyleOption) StyleOption {
	return func(style *Style) {
		nested := &Style{}
		for _, option := range options {
			option(nested)
		}
		style.Selected = nested
	}
}

// OnInput configures the corresponding node property.
func OnInput(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnInput = value })
}

// OnSubmit configures the corresponding node property.
func OnSubmit(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnSubmit = value })
}

// OnDoubleClick configures the corresponding node property.
func OnDoubleClick(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnDoubleClick = value })
}

// OnContextMenu configures the corresponding node property.
func OnContextMenu(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnContextMenu = value })
}

// OnPointer configures the corresponding node property.
func OnPointer(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnPointer = value })
}

// Disabled configures the corresponding node property.
func Disabled(value any) Option {
	return propertyOption(func(props *Props) { props.Disabled = value })
}

// Value configures the corresponding node property.
func Value(value any) Option {
	return propertyOption(func(props *Props) { props.Value = value })
}

// Placeholder configures the corresponding node property.
func Placeholder(value string) Option {
	return propertyOption(func(props *Props) { props.Placeholder = value })
}

// Multiline configures the corresponding node property.
func Multiline(value bool) Option {
	return propertyOption(func(props *Props) { props.Multiline = value })
}

// AriaLabel configures the corresponding node property.
func AriaLabel(value string) Option {
	return propertyOption(func(props *Props) { props.AriaLabel = value })
}

// Selected configures the corresponding node property.
func Selected(value bool) Option {
	return propertyOption(func(props *Props) { props.Selected = value })
}

// Group configures the corresponding node property.
func Group(value any) Option {
	return propertyOption(func(props *Props) { props.Group = value })
}

// FocusOnPointer configures the corresponding node property.
func FocusOnPointer(value *bool) Option {
	return propertyOption(func(props *Props) { props.FocusOnPointer = value })
}

// HitSlop configures the corresponding node property.
func HitSlop(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlop = value })
}

// HitSlopTop configures the corresponding node property.
func HitSlopTop(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlopTop = value })
}

// HitSlopRight configures the corresponding node property.
func HitSlopRight(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlopRight = value })
}

// HitSlopBottom configures the corresponding node property.
func HitSlopBottom(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlopBottom = value })
}

// HitSlopLeft configures the corresponding node property.
func HitSlopLeft(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlopLeft = value })
}

// Ref configures the corresponding node property.
func Ref(value func(*native.Node)) Option {
	return propertyOption(func(props *Props) { props.Ref = value })
}

// Password configures the corresponding node property.
func Password(value any) Option {
	return propertyOption(func(props *Props) { props.Password = value })
}

// Streaming configures the corresponding node property.
func Streaming(value any) Option {
	return propertyOption(func(props *Props) { props.Streaming = value })
}

// EstimatedItemHeight configures the corresponding node property.
func EstimatedItemHeight(value any) Option {
	return propertyOption(func(props *Props) { props.EstimatedItemHeight = value })
}

// Overscan configures the corresponding node property.
func Overscan(value any) Option {
	return propertyOption(func(props *Props) { props.Overscan = value })
}

// ListAlignment configures the corresponding node property.
func ListAlignment(value string) Option {
	return propertyOption(func(props *Props) { props.ListAlignment = value })
}

// FollowMode configures the corresponding node property.
func FollowMode(value string) Option {
	return propertyOption(func(props *Props) { props.FollowMode = value })
}

// ObjectFit configures the corresponding node property.
func ObjectFit(value string) Option {
	return propertyOption(func(props *Props) { props.ObjectFit = value })
}

// ShaderParameters configures the corresponding node property.
func ShaderParameters(value any) Option {
	return propertyOption(func(props *Props) { props.ShaderParameters = value })
}
