import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  moonComponents,
  booleanProperties,
  numberProperties,
  jsonProperties,
  extraProperties,
} from "./moonbit-components";

const root = resolve(import.meta.dir, "..");
const constants = readFileSync(resolve(root, "moonbit/protocol/constants.mbt"), "utf8");
const existing = (
  await Promise.all(
    ["element.mbt", "collections.mbt", "style_generated.mbt", "style.mbt"].map((file) =>
      Bun.file(resolve(root, "moonbit/ui", file)).text(),
    ),
  )
).join("\n");
const snake = (name: string) => name.replaceAll("-", "_");
const pascal = (name: string) =>
  name
    .split("-")
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
const slots = [
  ...new Set(moonComponents.flatMap((component) => Object.keys(component.parts))),
].sort();
const allProperties = [
  ...new Set([
    ...moonComponents.flatMap((component) => component.properties),
    ...extraProperties,
    ...booleanProperties,
    ...numberProperties,
    ...jsonProperties,
  ]),
].filter((name) => constants.includes(`pub const ${name} :`));
for (const match of constants.matchAll(/pub const (SWIFT_UI_[A-Z_]+) :/g)) {
  const name = match[1]!;
  if (name === "SWIFT_UI_EMBEDDED_WINDOW") continue;
  allProperties.push(name);
  if (
    name.includes("MATCH_CONTENTS") ||
    name === "SWIFT_UI_IS_PRESENTED" ||
    name === "SWIFT_UI_COLOR_SUPPORTS_OPACITY"
  )
    booleanProperties.push(name);
  if (name === "SWIFT_UI_MODIFIERS") jsonProperties.push(name);
}
const value = (name: string, expression: string) =>
  booleanProperties.includes(name)
    ? `@protocol.Boolean(${expression})`
    : numberProperties.includes(name)
      ? `@protocol.Number(${expression})`
      : jsonProperties.includes(name)
        ? `@protocol.Text(${expression}.stringify())`
        : `@protocol.Text(${expression})`;
const propertyType = (name: string) =>
  booleanProperties.includes(name)
    ? "Bool"
    : numberProperties.includes(name)
      ? "Float"
      : jsonProperties.includes(name)
        ? "Json"
        : "String";
const header = "// Generated by scripts/generate-moonbit-components.ts. Do not edit.\n";
let source =
  header +
  "\n///|\npub(all) enum Slot {\n" +
  slots.map((slot) => `  ${pascal(slot)}`).join("\n") +
  "\n} derive(Eq, Debug)\n";
source +=
  "\n///|\nfn slot_name(slot : Slot) -> String {\n  match slot {\n" +
  slots.map((slot) => `    ${pascal(slot)} => ${JSON.stringify(slot)}`).join("\n") +
  "\n  }\n}\n";
source += "\n///|\nfn component_spec(kind : String) -> ComponentSpec {\n  match kind {\n";
for (const component of moonComponents) {
  const defaults = Object.entries(component.defaults ?? {})
    .map(([name, data]) => {
      const encoded = jsonProperties.includes(name)
        ? `@protocol.Text(${JSON.stringify(JSON.stringify(data))})`
        : value(name, JSON.stringify(data));
      return `(@protocol.${name}, ${encoded})`;
    })
    .join(", ");
  source += `    ${JSON.stringify(component.name)} => {\n      role: ${JSON.stringify(component.root ?? component.name)},\n      tag: @protocol.TAG_${component.tag ?? "VIEW"},\n      slots: Map([${Object.entries(
    component.parts,
  )
    .map(([name, role]) => `(${JSON.stringify(name)}, ${JSON.stringify(role)})`)
    .join(
      ", ",
    )}]),\n      properties: [${[...new Set(component.properties)].map((name) => `@protocol.${name}`).join(", ")}],\n      defaults: Map([${defaults}]),\n    }\n`;
}
source += '    _ => abort("Unknown QuickGUI component: \\{kind}")\n  }\n}\n';
for (const component of moonComponents) {
  const name = component.name === "table" ? "data_table" : snake(component.name);
  source += `\n///|\npub fn ${name}(children : Array[Element]) -> Element {\n  configure_element(component_root(${JSON.stringify(component.name)}), children)\n}\n`;
}
for (const tag of [
  "HOST",
  "BUTTON",
  "SLIDER",
  "TOGGLE",
  "PROGRESS_VIEW",
  "STEPPER",
  "TEXT_FIELD",
  "PICKER",
  "DATE_PICKER",
  "COLOR_PICKER",
  "GAUGE",
  "POPOVER",
  "POPOVER_TRIGGER",
  "POPOVER_CONTENT",
]) {
  const container = ["HOST", "POPOVER", "POPOVER_TRIGGER", "POPOVER_CONTENT"].includes(tag);
  source += `\n///|\npub fn swift_ui_${tag.toLowerCase()}(${container ? "children : Array[Element]" : ""}) -> Element {\n  configure_element(element(@protocol.TAG_SWIFT_UI_${tag}), ${container ? "children" : "([] : Array[Element])"})\n}\n`;
}
for (const name of allProperties) {
  const method = name.toLowerCase();
  const type = propertyType(name);
  if (!existing.includes(`Element::${method}(`)) {
    const numeric = numberProperties.includes(name);
    source += `\n///|\npub fn${numeric ? "[T : IntoValue]" : ""} Element::${method}(self : Element, value : ${numeric ? "T" : type}) -> Element {\n  self.property(@protocol.${name}, ${numeric ? "value.into_value()" : value(name, "value")})\n}\n`;
  }
  if (!existing.includes(`Element::bind_${method}(`)) {
    source += `\n///|\npub fn Element::bind_${method}(self : Element, read : () -> ${type}) -> Element {\n  self.bind(@protocol.${name}, () => ${value(name, "read()")})\n}\n`;
  }
}
const file = resolve(root, "moonbit/ui/components_generated.mbt");
const fmt = Bun.spawnSync(
  [Bun.which("moonfmt") ?? resolve(root, "target/moonbit-toolchain/bin/moonfmt"), "-"],
  { stdin: Buffer.from(source) },
);
if (fmt.exitCode) throw new Error(fmt.stderr.toString());
source = fmt.stdout.toString();
if (process.argv.includes("--check")) {
  if (source !== readFileSync(file, "utf8"))
    throw new Error("Run bun scripts/generate-moonbit-components.ts");
} else {
  writeFileSync(file, source);
}
