#!/usr/bin/env bun
/** Keep the MoonBit wire constants sourced from the Rust decoder. */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const host = readFileSync(resolve(root, "crates/quickgui-host/src/lib.rs"), "utf8");
const tree = readFileSync(resolve(root, "crates/quickgui-host/src/tree.rs"), "utf8");
const version = /const PROTOCOL_VERSION: u16 = (\d+);/.exec(host)?.[1];
if (!version) throw new Error("Rust host protocol version not found");
const properties = [...host.matchAll(/pub const ([A-Z_0-9]+): u16 = (\d+);/g)];
const tags = [...tree.matchAll(/(\d+) => Ok\(Self::([A-Za-z]+)\),/g)];
if (properties.length < 100 || tags.length < 10)
  throw new Error("Rust protocol definitions not found");
const declarations = [
  `pub const VERSION : Int = ${version}`,
  ...["MAX_BATCH_BYTES", "MAX_MUTATIONS", "MAX_NODES", "MAX_STRING_BYTES"].map((name) => {
    const match = new RegExp(`const ${name}: usize = ([0-9_ *]+);`).exec(host);
    if (!match) throw new Error(`Missing Rust limit ${name}`);
    const value = match[1]!
      .split("*")
      .reduce((result, part) => result * Number(part.replaceAll("_", "").trim()), 1);
    return `pub const ${name} : Int = ${value}`;
  }),
  ...properties.map(([, name, id]) => `pub const ${name} : Int = ${id}`),
  ...tags.map(
    ([, id, name]) =>
      `pub const TAG_${name!.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase()} : Int = ${id}`,
  ),
];
function emit(relative: string, items: string[]) {
  const source =
    "// Generated by bun scripts/generate-moonbit.ts. Do not edit.\n" +
    items.map((item) => `\n///|\n${item}\n`).join("");
  const formatter = Bun.which("moonfmt") ?? resolve(root, "target/moonbit-toolchain/bin/moonfmt");
  if (!existsSync(formatter)) throw new Error("Install MoonBit to generate formatted bindings");
  const result = Bun.spawnSync([formatter, "-"], {
    stdin: Buffer.from(source),
    stdout: "pipe",
    stderr: "pipe",
  });
  if (result.exitCode !== 0) throw new Error(result.stderr.toString());
  const contents = result.stdout.toString();
  const path = resolve(root, relative);
  if (process.argv.includes("--check")) {
    if (readFileSync(path, "utf8") !== contents)
      throw new Error(`${relative} is stale; run bun scripts/generate-moonbit.ts`);
  } else writeFileSync(path, contents);
}
emit("moonbit/protocol/constants.mbt", declarations);

// Public fluent spellings; all IDs still come from the Rust wire schema above.
const fields = `display flex_direction flex_wrap flex_grow flex_shrink flex_basis
align_items align_self justify_content align_content gap column_gap row_gap width height
min_width min_height max_width max_height padding padding_top padding_right padding_bottom padding_left
margin margin_top margin_right margin_bottom margin_left opacity border_width border_radius font_size
font_family font_weight line_height text_align cursor app_region user_select position overflow overflow_x
overflow_y visibility letter_spacing text_transform line_clamp white_space text_overflow top right bottom left
outline_width outline_offset outline_style transform transform_origin border_top_width border_right_width
border_bottom_width border_left_width border_style box_shadow text_shadow text_decoration_line text_decoration_style
text_decoration_thickness word_spacing word_break overflow_wrap hyphens background_image background_size
background_repeat background_position filter backdrop_filter mix_blend_mode transition transition_property
transition_duration transition_easing transition_max_fps grid_template_columns grid_template_rows grid_auto_flow
grid_column_start grid_column_end grid_column_span grid_row_start grid_row_end grid_row_span aspect_ratio
value placeholder multiline disabled`
  .trim()
  .split(/\s+/);
const known = new Set(properties.map(([, name]) => name));
const methods: string[] = [];
for (const name of fields) {
  const code =
    ({ transition_property: "TRANSITION_PROPERTIES" } as Record<string, string>)[name] ??
    name.toUpperCase();
  if (!known.has(code)) throw new Error(`Unknown fluent property: ${code}`);
  const key = name.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
  methods.push(
    `pub fn[T : IntoValue] Element::${name}(self : Element, value : T) -> Element {\n  self.property(@protocol.${code}, IntoValue::into_value(value))\n}`,
  );
  methods.push(
    `pub fn[T : IntoValue] Style::${name}(self : Style, value : T) -> Style {\n  self.property(@protocol.${code}, "${key}", IntoValue::into_value(value))\n}`,
  );
}
for (const [name, code, key] of [
  ["bg", "BACKGROUND_COLOR", "backgroundColor"],
  ["text_color", "COLOR", "color"],
  ["border_color", "BORDER_COLOR", "borderColor"],
  ["outline_color", "OUTLINE_COLOR", "outlineColor"],
]) {
  methods.push(
    `pub fn Element::${name}(self : Element, value : Color) -> Element {\n  self.property(@protocol.${code}, IntoValue::into_value(value))\n}`,
  );
  methods.push(
    `pub fn Style::${name}(self : Style, value : Color) -> Style {\n  self.property(@protocol.${code}, "${key}", IntoValue::into_value(value))\n}`,
  );
}
emit("moonbit/ui/style_generated.mbt", methods);
