// Command protocolgen keeps the Go wire constants sourced from the Rust decoder.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strings"
)

func mustRead(path string) string {
	b, e := os.ReadFile(path)
	if e != nil {
		panic(e)
	}
	return string(b)
}

func main() {
	check := flag.Bool("check", false, "verify generated constants are current")
	flag.Parse()
	rust := mustRead("../../crates/quickgui-host/src/lib.rs")
	tree := mustRead("../../crates/quickgui-host/src/tree.rs")
	version := regexp.MustCompile(`const PROTOCOL_VERSION: u16 = (\d+);`).FindStringSubmatch(rust)[1]
	out := "// Code generated by go generate; DO NOT EDIT.\npackage protocol\n\n"
	out += "const Version uint32 = " + version + "\nconst (\n"
	props := regexp.MustCompile(`pub const ([A-Z_0-9]+): u16 = (\d+);`).FindAllStringSubmatch(rust, -1)
	for _, p := range props {
		out += fmt.Sprintf("%s uint16 = %s\n", pascal(p[1]), p[2])
	}
	out += ")\nconst (\n"
	for _, n := range regexp.MustCompile(`(\d+) => Ok\(Self::([A-Za-z]+)\),`).FindAllStringSubmatch(tree, -1) {
		out += fmt.Sprintf("Tag%s uint8 = %s\n", strings.NewReplacer("SwiftUi", "SwiftUI", "QuickGui", "QuickGUI").Replace(n[2]), n[1])
	}
	out += ")\n"
	formatted, e := format.Source([]byte(out))
	if e != nil {
		panic(e)
	}
	if *check {
		if !bytes.Equal(formatted, []byte(mustRead("constants_generated.go"))) {
			panic("Go protocol is stale; run go generate ./protocol")
		}
		return
	}
	if e = os.WriteFile("constants_generated.go", formatted, 0644); e != nil {
		panic(e)
	}
}

func pascal(s string) string {
	var b strings.Builder
	for _, p := range strings.Split(strings.ToLower(s), "_") {
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return strings.NewReplacer("SwiftUi", "SwiftUI", "QuickGui", "QuickGUI").Replace(b.String())
}
