[package]
name = "quick-git-io"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
name = "quickgui_quick_git_io"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1"
base64 = "0.22"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[profile.release]
panic = "abort"
strip = "symbols"

[workspace]
