// Command optionsgen keeps functional options aligned with the Go style record.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"regexp"
)

func main() {
	check := flag.Bool("check", false, "verify generated options")
	flag.Parse()
	var output, methods, bindings bytes.Buffer
	output.WriteString("// Code generated by optionsgen; DO NOT EDIT.\n\npackage ui\n\nimport \"github.com/egoist/quickgui/go/native\"\n\n")
	methods.WriteString("// Code generated by optionsgen; DO NOT EDIT.\n\npackage ui\n\nimport \"github.com/egoist/quickgui/go/native\"\n\n")
	bindings.WriteString("// Code generated by optionsgen; DO NOT EDIT.\n\npackage ui\n\nimport (\"github.com/egoist/quickgui/go/native\"; \"github.com/egoist/quickgui/go/protocol\")\n\nfunc applyElementBinding(node *native.Node, props *Props, field elementBinding) {\nswitch field {\n")
	primitiveSource, err := os.ReadFile("primitive.go")
	must(err)
	events := map[string]string{}
	for _, match := range regexp.MustCompile(`\{protocol\.(Event\w+), props\.(\w+)\}`).FindAllStringSubmatch(string(primitiveSource), -1) {
		events[match[2]] = match[1]
	}
	for _, source := range []struct{ file, record string }{{"style.go", "Style"}, {"runtime.go", "Props"}} {
		files := token.NewFileSet()
		file, err := parser.ParseFile(files, source.file, nil, 0)
		must(err)
		ast.Inspect(file, func(node ast.Node) bool {
			spec, ok := node.(*ast.TypeSpec)
			if !ok || spec.Name.Name != source.record {
				return true
			}
			for index, field := range spec.Type.(*ast.StructType).Fields.List {
				name := field.Names[0].Name
				if ast.IsExported(name) {
					if source.record == "Style" {
						extra := ""
						if name == "GroupHover" {
							extra = ", groupHoverRules: props.Style.groupHoverRules"
						} else if name == "GroupActive" {
							extra = ", groupActiveRules: props.Style.groupActiveRules"
						}
						fmt.Fprintf(&bindings, "case %d: applyStyle(node, Style{%s: props.Style.%s%s})\n", index, name, name, extra)
					} else if event, ok := events[name]; ok {
						fmt.Fprintf(&bindings, "case propertyBindingOffset + %d: setFluentListener(node, protocol.%s, props.%s)\n", index, event, name)
					} else if name != "Style" && name != "Children" && name != "Ref" {
						fmt.Fprintf(&bindings, "case propertyBindingOffset + %d: applyPropValues(node, Props{%s: props.%s})\n", index, name, name)
					}
				}
				if !ast.IsExported(name) || (source.record == "Style" && (name == "GroupHover" || name == "GroupActive")) {
					continue
				}
				if source.record == "Props" && (name == "Style" || name == "Children" || name == "OnClick" || name == "ObjectFit") {
					continue
				}
				var fieldType bytes.Buffer
				must(format.Node(&fieldType, files, field.Type))
				if source.record == "Style" {
					if fieldType.String() == "*Style" {
						function := name
						if name == "Disabled" || name == "Selected" || name == "Invalid" {
							function += "Style"
						}
						fmt.Fprintf(&output, "// %s merges options into the %s interaction style.\nfunc %s(options ...StyleDeclaration) StyleOption {\nreturn func(style *Style) {\nnested := mergeStateStyles(style.%s, nil)\nfor _, option := range options { option.applyStyle(nested) }\nstyle.%s = nested\n}\n}\n\n", function, name, function, name, name)
						method := function
						if name == "Focus" {
							method = "FocusStyle"
						}
						fmt.Fprintf(&methods, "// %s merges the %s interaction style.\nfunc (element *Element) %s(options ...StyleDeclaration) *Element {\nreturn element.configureStyle(%q, %s(options...))\n}\n\n", method, name, method, name, function)
					} else {
						// Aliases write the same field so the last declaration wins in
						// either order, just like composing Style values.
						target := name
						if canonical, ok := styleAliases[name]; ok {
							target = canonical
						}
						fmt.Fprintf(&output, "// %s sets the corresponding style property.\nfunc %s(value %s) StyleOption {\nreturn func(style *Style) { style.%s = value }\n}\n\n", name, name, fieldType.String(), target)
						if name != "Flex" && name != "FlexWrap" {
							fmt.Fprintf(&methods, "// %s sets the corresponding style property.\nfunc (element *Element) %s(value %s) *Element {\nreturn element.configureStyle(%q, %s(value))\n}\n\n", name, name, fieldType.String(), target, name)
						}
					}
				} else {
					fmt.Fprintf(&output, "// %s configures the corresponding node property.\nfunc %s(value %s) Option {\nreturn propertyOption(func(props *Props) { props.%s = value })\n}\n\n", name, name, fieldType.String(), name)
					if name != "Ref" && name != "OnInput" && name != "OnSubmit" {
						fmt.Fprintf(&methods, "// %s configures the corresponding node property.\nfunc (element *Element) %s(value %s) *Element {\nreturn element.configureProperty(%q, %s(value))\n}\n\n", name, name, fieldType.String(), name, name)
					}
				}
			}
			return false
		})
	}
	bindings.WriteString("}\n}\n")
	for _, result := range []struct {
		path string
		data []byte
	}{{"options_generated.go", output.Bytes()}, {"element_generated.go", methods.Bytes()}, {"element_bindings_generated.go", bindings.Bytes()}} {
		formatted, err := format.Source(result.data)
		must(err)
		if *check {
			existing, err := os.ReadFile(result.path)
			must(err)
			if !bytes.Equal(existing, formatted) {
				panic(result.path + " is stale; run go generate ./ui")
			}
		} else {
			must(os.WriteFile(result.path, formatted, 0o644))
		}
	}
}

var styleAliases = map[string]string{
	"WordWrap":                 "OverflowWrap",
	"TransitionTimingFunction": "TransitionEasing",
	"PaddingInlineStart":       "PaddingStart",
	"PaddingInlineEnd":         "PaddingEnd",
	"MarginInlineStart":        "MarginStart",
	"MarginInlineEnd":          "MarginEnd",
	"BorderInlineStartWidth":   "BorderStartWidth",
	"BorderInlineEndWidth":     "BorderEndWidth",
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
