// Command optionsgen keeps functional options aligned with the Go style record.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
)

func main() {
	check := flag.Bool("check", false, "verify generated options")
	flag.Parse()
	var output bytes.Buffer
	output.WriteString("// Code generated by optionsgen; DO NOT EDIT.\n\npackage ui\n\nimport \"github.com/egoist/quickgui/go/native\"\n\n")
	for _, source := range []struct{ file, record string }{{"style.go", "Style"}, {"runtime.go", "Props"}} {
		files := token.NewFileSet()
		file, err := parser.ParseFile(files, source.file, nil, 0)
		must(err)
		ast.Inspect(file, func(node ast.Node) bool {
			spec, ok := node.(*ast.TypeSpec)
			if !ok || spec.Name.Name != source.record {
				return true
			}
			for _, field := range spec.Type.(*ast.StructType).Fields.List {
				name := field.Names[0].Name
				if !ast.IsExported(name) || (source.record == "Style" && name == "GroupHover") {
					continue
				}
				if source.record == "Props" && (name == "Style" || name == "Children" || name == "OnClick") {
					continue
				}
				var fieldType bytes.Buffer
				must(format.Node(&fieldType, files, field.Type))
				if source.record == "Style" {
					if fieldType.String() == "*Style" {
						function := name
						if name == "Disabled" || name == "Selected" {
							function += "Style"
						}
						fmt.Fprintf(&output, "// %s configures the %s interaction style.\nfunc %s(options ...StyleOption) StyleOption {\nreturn func(style *Style) {\nnested := &Style{}\nfor _, option := range options { option(nested) }\nstyle.%s = nested\n}\n}\n\n", function, name, function, name)
					} else {
						fmt.Fprintf(&output, "// %s sets the corresponding style property.\nfunc %s(value %s) StyleOption {\nreturn func(style *Style) { style.%s = value }\n}\n\n", name, name, fieldType.String(), name)
					}
				} else {
					fmt.Fprintf(&output, "// %s configures the corresponding node property.\nfunc %s(value %s) Option {\nreturn propertyOption(func(props *Props) { props.%s = value })\n}\n\n", name, name, fieldType.String(), name)
				}
			}
			return false
		})
	}
	formatted, err := format.Source(output.Bytes())
	must(err)
	const path = "options_generated.go"
	if *check {
		existing, err := os.ReadFile(path)
		must(err)
		if !bytes.Equal(existing, formatted) {
			panic("functional options are stale; run go generate ./ui")
		}
		return
	}
	must(os.WriteFile(path, formatted, 0o644))
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
