/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function applyBatch(app: number, window: number, batch: Buffer): number

export declare function closeWindow(app: number, window: number): boolean

export declare function createAnchoredWindow(app: number, parent: number, anchor: number, options?: NativeWindowOptions | undefined | null): number

export declare function createApp(): number

export declare function createWindow(app: number, options?: NativeWindowOptions | undefined | null): number

export declare function destroyApp(app: number): boolean

export declare function focusNode(app: number, window: number, node: number): boolean

export interface NativeEvent {
  kind: string
  window: number
  target: number
  value?: string
}

export interface NativeWindowOptions {
  title?: string
  width?: number
  height?: number
  minimumWidth?: number
  minimumHeight?: number
  background?: number
  titleBarStyle?: string
  trafficLightX?: number
  trafficLightY?: number
  transparent?: boolean
  blur?: boolean
  popupPlacement?: string
  popupGap?: number
  popupOffsetX?: number
  popupOffsetY?: number
  popupGrab?: boolean
  popupAcceptsKeyFocus?: boolean
}

export declare function protocolVersion(): number

/** Return `-1` while running or the non-negative native exit code after termination. */
export declare function pumpApp(app: number, timeoutMs?: number | undefined | null): number

export declare function startApp(app: number): void

export declare function takeEvents(app: number): Array<NativeEvent>
