/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Stateful CPU sampler. Each `sample()` reports usage since the previous call on this instance. */
export declare class NativeCpuUsageSampler {
  constructor()
  sample(): Promise<NativeCpuUsage>
}

export declare class NativePowerAssertion {
  constructor(kind: string, reason: string)
  get kind(): string
  get reason(): string
  get active(): boolean
  release(): boolean
}

/**
 * Synchronous binding for core-owned, CPU-only route matching and memory history.
 *
 * This object never reaches the application or window runtime and therefore never waits for the
 * native main thread. Solid turns the snapshots returned by its mutation methods into signals.
 */
export declare class NativeRouter {
  constructor(routes: Array<NativeRouteDefinition>, initialDestination?: string | undefined | null)
  state(): NativeRouterState
  resolve(destination: string): NativeRouteLocation
  isActive(destination: string, end?: boolean | undefined | null): boolean
  push(destination: string): NativeRouterState
  replace(destination: string): NativeRouterState
  go(delta: number): NativeRouterState
  back(): NativeRouterState
  forward(): NativeRouterState
}

export declare function abortAppHost(message: string): void

export declare function addCrashExtraParameter(key: string, value: string): Promise<boolean>

export declare function addHostedRecentDocument(app: number, path: string): void

export declare function addRecentDocument(app: number, path: string): void

export declare function applyBatch(app: number, window: number, batch: Buffer): number

export declare function applyHostedBatch(app: number, window: number, batch: Buffer): number

export declare function checkForUpdate(endpoint: string, options: NativeUpdateClientOptions): Promise<NativeAvailableUpdate | undefined>

export declare function clearHostedRecentDocuments(app: number): void

export declare function clearRecentDocuments(app: number): void

export declare function closeHostedWindow(app: number, window: number): void

export declare function closeWindow(app: number, window: number): boolean

export declare function configureApp(app: number, options: NativeAppOptions): void

export declare function configureHostedApp(app: number, options: NativeAppOptions): Promise<void>

export declare function createApp(options?: NativeAppOptions | undefined | null): number

export declare function createEmbeddedView(app: number, parent: number, matchHorizontal: boolean, matchVertical: boolean, options?: NativeWindowOptions | undefined | null, initialBatch?: Buffer | undefined | null): number

export declare function createHostedApp(options?: NativeAppOptions | undefined | null): number

export declare function createHostedEmbeddedView(app: number, parent: number, matchHorizontal: boolean, matchVertical: boolean, options?: NativeWindowOptions | undefined | null, initialBatch?: Buffer | undefined | null): number

export declare function createHostedSystemPopover(app: number, parent: number, anchor: number, options?: NativeWindowOptions | undefined | null, initialBatch?: Buffer | undefined | null): number

export declare function createHostedWindow(app: number, options?: NativeWindowOptions | undefined | null, initialBatch?: Buffer | undefined | null): number

export declare function createSystemPopover(app: number, parent: number, anchor: number, options?: NativeWindowOptions | undefined | null, initialBatch?: Buffer | undefined | null): number

export declare function createWindow(app: number, options?: NativeWindowOptions | undefined | null, initialBatch?: Buffer | undefined | null): number

export declare function defaultUpdateTarget(): string

export declare function deleteCrashReport(id: string): Promise<boolean>

export declare function deleteSecureStorage(service: string, account: string): Promise<boolean>

export declare function destroyApp(app: number): boolean

export declare function destroyHostedApp(app: number): void

export declare function disableAutoStart(options: NativeAutoStartOptions): Promise<void>

export declare function dismissHostedNotification(app: number, tag: string): Promise<void>

export declare function dismissNotification(app: number, tag: string): void

export declare function enableAutoStart(options: NativeAutoStartOptions): Promise<void>

export declare function exitApp(app: number): boolean

export declare function exitAppWithCode(app: number, code: number): boolean

export declare function exitHostedApp(app: number): Promise<boolean>

export declare function exitHostedAppWithCode(app: number, code: number): Promise<boolean>

export declare function focusHostedNode(app: number, window: number, node: number): void

export declare function focusNode(app: number, window: number, node: number): boolean

export declare function getAppInfo(app: number): NativeAppInfo | null

export declare function getApplicationsFolderSupport(app: number): NativeApplicationsFolderSupport

export declare function getAppPaths(app: number): NativeAppPaths | null

export declare function getCursorScreenPosition(app: number): NativePoint

export declare function getDesktopIntegrationSupport(app: number): NativeDesktopIntegrationSupport

export declare function getDisplays(app: number): Array<NativeDisplay>

export declare function getHostedAppInfo(app: number): Promise<NativeAppInfo | null>

export declare function getHostedApplicationsFolderSupport(app: number): Promise<NativeApplicationsFolderSupport>

export declare function getHostedAppPaths(app: number): Promise<NativeAppPaths | null>

export declare function getHostedCursorScreenPosition(app: number): Promise<NativePoint>

export declare function getHostedDesktopIntegrationSupport(app: number): Promise<NativeDesktopIntegrationSupport>

export declare function getHostedDisplays(app: number): Promise<Array<NativeDisplay>>

export declare function getHostedKeyboardLayout(app: number): Promise<NativeKeyboardLayout>

export declare function getHostedSystemInfo(app: number): Promise<NativeSystemInfo>

export declare function getHostedSystemPreferences(app: number): Promise<NativeSystemPreferences>

export declare function getHostedWindowRegistry(app: number): Promise<NativeWindowRegistry>

export declare function getHostedWindowRestoreState(app: number, window: number): Promise<NativeWindowRestoreState>

export declare function getHostedWindowState(app: number, window: number): Promise<NativeWindowState>

export declare function getKeyboardLayout(app: number): NativeKeyboardLayout

export declare function getLastCrashReport(): Promise<NativeCrashReport[]>

export declare function getPendingCrashReports(): Promise<NativeCrashReport[]>

export declare function getPermissionStatus(kind: string): string

export declare function getPowerState(): NativePowerState

export declare function getProcessMetrics(): Promise<NativeProcessMetrics>

export declare function getSecureStorage(service: string, account: string): Promise<Buffer | undefined>

export declare function getSessionState(): string

export declare function getSystemIdleState(thresholdSeconds: number): string

export declare function getSystemIdleTime(): number

export declare function getSystemInfo(app: number): NativeSystemInfo

export declare function getSystemMemory(): Promise<NativeSystemMemory>

export declare function getSystemPreferences(app: number): NativeSystemPreferences

export declare function getWindowRegistry(app: number): NativeWindowRegistry

export declare function getWindowRestoreState(app: number, window: number): NativeWindowRestoreState

export declare function getWindowState(app: number, window: number): NativeWindowState

export interface HostedAppUpdate {
  events: Array<NativeEvent>
  exitCode?: number
}

export declare function installUpdate(update: NativeAvailableUpdate, artifact: string, installOptions: NativeUpdateInstallOptions, options: NativeUpdateClientOptions): Promise<NativeInstalledUpdate>

/** Whether this process is running from an installed application bundle. */
export declare function isApplicationPackaged(): boolean

export declare function isAppReady(app: number): boolean

export declare function isAutoStartEnabled(options: NativeAutoStartOptions): Promise<boolean>

export declare function isAutoStartSupported(): boolean

export declare function isCrashReporterStarted(): boolean

export declare function isProtocolRegistered(options: NativeProtocolRegistrationOptions): Promise<boolean>

export declare function isSecureStorageSupported(): boolean

export interface NativeAboutPanelOptions {
  applicationName?: string
  applicationVersion?: string
  version?: string
  copyright?: string
  credits?: string
  icon?: NativeImageSource
}

export interface NativeAppInfo {
  name: string
  version: string
  identifier: string
}

/** Whether this process can relocate its bundle into an `/Applications` directory. */
export interface NativeApplicationsFolderSupport {
  supported: boolean
  alreadyInstalled: boolean
}

export interface NativeAppOptions {
  name?: string
  version?: string
  identifier?: string
  resourceDir?: string
  configDir?: string
  dataDir?: string
  localDataDir?: string
  cacheDir?: string
  logDir?: string
  runtimeDir?: string
  tempDir?: string
  /** `default`, `last-window-closed`, or `explicit`. */
  quitMode?: string
  /** OpenType font files embedded by the JavaScript host and registered by the Rust core. */
  fontData?: Array<Buffer>
}

export interface NativeAppPaths {
  executable: string
  executableDir: string
  resourceDir: string
  homeDir?: string
  configDir?: string
  dataDir?: string
  localDataDir?: string
  cacheDir?: string
  logDir?: string
  runtimeDir?: string
  tempDir: string
  audioDir?: string
  desktopDir?: string
  documentDir?: string
  downloadDir?: string
  pictureDir?: string
  videoDir?: string
}

export interface NativeAutoStartOptions {
  appName: string
  executable?: string
  arguments?: Array<string>
  mode?: string
  bundleIdentifier?: string
}

export interface NativeAvailableUpdate {
  version: string
  currentVersion: string
  target: string
  url: string
  signature: string
  notes?: string
  publishedAt?: string
}

export interface NativeBatteryState {
  chargePercent?: number
  status: string
}

export interface NativeClipboardEntry {
  kind: string
  text?: string
  metadata?: string
  format?: string
  data?: Buffer
  paths?: Array<string>
  url?: string
}

export interface NativeClipboardItem {
  entries: Array<NativeClipboardEntry>
}

export interface NativeCpuUsage {
  percent?: number
  intervalSeconds: number
  cpuSeconds: number
  totalCpuSeconds: number
}

export interface NativeCrashLocation {
  file: string
  line: number
  column: number
}

export interface NativeCrashParameter {
  key: string
  value: string
}

export interface NativeCrashReport {
  schemaVersion: number
  id: string
  kind: string
  timestamp: string
  appName: string
  appVersion: string
  appIdentifier: string
  operatingSystem: string
  operatingSystemVersion?: string
  architecture: string
  processId: number
  thread?: string
  message: string
  location?: NativeCrashLocation
  backtrace?: string
  signal?: number
  signalName?: string
  faultAddress?: string
  parameters: Array<NativeCrashParameter>
}

export interface NativeCrashReporterOptions {
  appName: string
  appVersion: string
  appIdentifier: string
  directory?: string
  maxReports?: number
  maxReportBytes?: number
  parameters?: Array<NativeCrashParameter>
  uploadEndpoint?: string
  backtrace?: string
  captureSignals?: boolean
}

export interface NativeCrashUploadSummary {
  attempted: number
  uploaded: number
  failed: number
}

export interface NativeDesktopIntegrationSupport {
  systemNotifications: boolean
  scheduledNotifications: boolean
  notificationReplies: boolean
  nativeApplicationMenus: boolean
  nativePopupMenus: boolean
  trayIcons: boolean
  programmableTrayPopup: boolean
  globalShortcuts: boolean
  singleInstance: boolean
  dynamicProtocolRegistration: boolean
  autostart: boolean
  windowIcons: boolean
  windowFocusability: boolean
  windowOpacity: boolean
  skipTaskbar: boolean
  visibleOnAllWorkspaces: boolean
  cursorControl: boolean
  cursorScreenPosition: boolean
  taskbarProgress: boolean
  taskbarOverlayIcons: boolean
  dockBadges: boolean
  dockIcons: boolean
  dockMenus: boolean
  recentDocuments: boolean
  fileIcons: boolean
  nativeAboutPanel: boolean
  userTasks: boolean
}

export interface NativeDialogButton {
  label: string
  role?: string
}

export interface NativeDialogOptions {
  level?: string
  message: string
  detail?: string
  buttons: Array<NativeDialogButton>
}

export interface NativeDisplay {
  id: string
  uuid?: string
  name: string
  bounds: NativeRect
  workArea: NativeRect
  scaleFactor: number
  refreshRate?: number
  primary: boolean
}

export interface NativeEvent {
  kind: string
  window: number
  target: number
  value?: string
  paths?: Array<string>
  data?: Buffer
  width?: number
  height?: number
  error?: string
}

export interface NativeFileDialogFilter {
  name: string
  extensions: Array<string>
}

export interface NativeImageSource {
  /** Encoded image bytes, or raw RGBA8 when width and height are both supplied. */
  data?: Buffer
  /** Image path used when data is omitted. */
  path?: string
  width?: number
  height?: number
}

export interface NativeInstalledUpdate {
  version: string
  disposition: string
  installedPath: string
  backupPath?: string
  installerProcessId?: number
  requiresApplicationExit: boolean
  relaunchRecommended: boolean
}

export interface NativeKeyboardLayout {
  id: string
  name: string
}

export interface NativeNotificationAction {
  id: string
  label: string
  kind?: string
  placeholder?: string
}

export interface NativeNotificationAttachment {
  id: string
  path: string
}

export interface NativeNotificationOptions {
  tag: string
  title: string
  body: string
  subtitle?: string
  actions: Array<NativeNotificationAction>
  /** `default`, `silent`, or a platform-recognized named sound. */
  sound?: string
  iconPath?: string
  attachments?: Array<NativeNotificationAttachment>
  /** Absolute Unix epoch milliseconds. */
  deliveryAtMs?: number
}

export interface NativeOpenDialogOptions {
  files: boolean
  directories: boolean
  multiple: boolean
  title?: string
  prompt?: string
  directory?: string
  suggestedName?: string
  filters: Array<NativeFileDialogFilter>
  showsHiddenFiles: boolean
}

export interface NativePoint {
  x: number
  y: number
}

export interface NativePowerState {
  source: string
  battery?: NativeBatteryState
  thermalState: string
  lowPowerMode?: boolean
  cpuSpeedLimitPercent?: number
}

export interface NativeProcessMetrics {
  cpuUserSeconds: number
  cpuSystemSeconds: number
  residentBytes: number
  footprintBytes?: number
  virtualBytes: number
  threadCount?: number
  uptimeSeconds: number
}

export interface NativeProtocolRegistrationOptions {
  scheme: string
  appName: string
  appId: string
  executable?: string
  arguments?: Array<string>
}

export interface NativeRect {
  x: number
  y: number
  width: number
  height: number
}

export interface NativeRelaunchOptions {
  executable?: string
  arguments?: Array<string>
  clearArguments?: boolean
  workingDirectory?: string
}

export interface NativeRouteDefinition {
  id: string
  path?: string
  parentId?: string
}

export interface NativeRouteLocation {
  href: string
  pathname: string
  search: string
  hash: string
  query: Array<NativeRouteValue>
}

export interface NativeRouteMatch {
  routeIds: Array<string>
  params: Array<NativeRouteValue>
}

export interface NativeRouterState {
  location: NativeRouteLocation
  matched?: NativeRouteMatch
  historyIndex: number
  historyLength: number
  canGoBack: boolean
  canGoForward: boolean
}

export interface NativeRouteValue {
  name: string
  value: string
}

export interface NativeSaveDialogOptions {
  directory: string
  title?: string
  suggestedName?: string
  prompt?: string
  filters: Array<NativeFileDialogFilter>
  showsHiddenFiles: boolean
}

export interface NativeSystemColor {
  red: number
  green: number
  blue: number
  alpha: number
}

export interface NativeSystemInfo {
  operatingSystem: string
  family: string
  name: string
  version?: string
  edition?: string
  codename?: string
  architecture: string
  bitness: string
  hostname?: string
  locale?: string
  preferredLanguages: Array<string>
  languagesTruncated: boolean
}

export interface NativeSystemMemory {
  totalBytes: number
  availableBytes: number
  freeBytes: number
  usedBytes: number
}

export interface NativeSystemPreferences {
  colorScheme: string
  reduceMotion?: boolean
  reduceTransparency?: boolean
  increaseContrast?: boolean
  differentiateWithoutColor?: boolean
  invertColors?: boolean
  forcedColors?: boolean
  screenReader?: boolean
  switchControl?: boolean
  accentColor?: NativeSystemColor
  highlightColor?: NativeSystemColor
  highlightTextColor?: NativeSystemColor
  windowBackgroundColor?: NativeSystemColor
  windowTextColor?: NativeSystemColor
  controlBackgroundColor?: NativeSystemColor
  controlTextColor?: NativeSystemColor
  linkColor?: NativeSystemColor
}

export interface NativeTrayIconOptions {
  id: number
  /** Encoded image bytes, or raw RGBA8 when width and height are both supplied. */
  iconData?: Buffer
  /** Image path used when iconData is omitted. */
  iconPath?: string
  width?: number
  height?: number
  tooltip?: string
  title?: string
  iconIsTemplate?: boolean
  menuOnLeftClick?: boolean
  visible?: boolean
  /** Bounded JSON encoding of the declarative tray menu. */
  menu: string
}

export interface NativeUpdateClientOptions {
  currentVersion: string
  publicKey: string
  target?: string
  maximumDownloadBytes?: number
}

export interface NativeUpdateInstallOptions {
  targetExecutable?: string
  retainBackup?: boolean
  windowsMode?: string
  installerArguments?: Array<string>
}

export interface NativeUpdateProgress {
  phase: string
  chunkBytes?: number
  downloadedBytes?: number
  totalBytes?: number
  path?: string
}

export interface NativeUserTask {
  title: string
  arguments: string
  program?: string
  description?: string
  workingDirectory?: string
  iconPath?: string
  iconIndex?: number
}

export interface NativeWindowOptions {
  title?: string
  width?: number
  height?: number
  x?: number
  y?: number
  /** `normal`, `maximized`, or `fullscreen`. */
  initialState?: string
  displayId?: string
  /** Set to false to remove QuickGUI's default minimum size. */
  minimumSizeEnabled?: boolean
  minimumWidth?: number
  minimumHeight?: number
  maximumWidth?: number
  maximumHeight?: number
  representedFile?: string
  documentEdited?: boolean
  tabbingIdentifier?: string
  background?: number
  performanceProfile?: string
  appearance?: string
  vibrancy?: string
  visualEffectState?: string
  titleBarStyle?: string
  kind?: string
  focus?: boolean
  focusable?: boolean
  show?: boolean
  movable?: boolean
  resizable?: boolean
  minimizable?: boolean
  maximizable?: boolean
  closable?: boolean
  decorated?: boolean
  shadow?: boolean
  contentProtected?: boolean
  windowLevel?: string
  skipTaskbar?: boolean
  visibleOnAllWorkspaces?: boolean
  opacity?: number
  icon?: NativeImageSource
  taskbarProgressState?: string
  taskbarProgress?: number
  taskbarOverlayIcon?: NativeImageSource
  taskbarOverlayDescription?: string
  cursorVisible?: boolean
  cursorGrab?: string
  cursorHitTest?: boolean
  cursorX?: number
  cursorY?: number
  /** Bounded JSON encoding of a per-window native menu. Omitted windows inherit the app menu. */
  menu?: string
  /**
   * Persisted geometry and display identity captured with `window.getRestoreState()`.
   *
   * The core re-validates every field, so a stale value can never place a window off every
   * connected display.
   */
  restoreState?: NativeWindowRestoreState
  lineScrollPixels?: number
  keySequenceTimeoutMs?: number
  reduceMotion?: boolean
  trafficLightX?: number
  trafficLightY?: number
  transparent?: boolean
  blur?: boolean
  popoverPlacement?: string
  popoverGap?: number
  popoverOffsetX?: number
  popoverOffsetY?: number
  popoverViewportMargin?: number
  popoverDismissOnEscape?: boolean
  popoverDismissOnPointerOutside?: boolean
  popoverGrab?: boolean
  popoverAcceptsKeyFocus?: boolean
}

export interface NativeWindowRegistry {
  windows: Array<number>
  activeWindow?: number
  truncated: boolean
}

/**
 * Persistable window geometry and display identity.
 *
 * `displayUuid` is the textual form of the stable physical display identity, so a stored state
 * survives a reboot that renumbers process-level display ids.
 */
export interface NativeWindowRestoreState {
  x: number
  y: number
  width: number
  height: number
  maximized: boolean
  fullscreen: boolean
  displayId?: string
  displayUuid?: string
  scaleFactor: number
}

export interface NativeWindowState {
  displayId?: string
  kind: string
  x: number
  y: number
  width: number
  height: number
  viewportWidth: number
  viewportHeight: number
  minimumWidth?: number
  minimumHeight?: number
  maximumWidth?: number
  maximumHeight?: number
  scaleFactor: number
  appearance: string
  backgroundAppearance: string
  vibrancy?: string
  visualEffectState: string
  focused: boolean
  focusable: boolean
  visible: boolean
  minimized: boolean
  maximized: boolean
  fullscreen: boolean
  occluded: boolean
  movable: boolean
  resizable: boolean
  minimizable: boolean
  maximizable: boolean
  closable: boolean
  decorated: boolean
  shadow: boolean
  contentProtected: boolean
  windowLevel: string
  skipTaskbar: boolean
  visibleOnAllWorkspaces: boolean
  opacity: number
  hasIcon: boolean
  taskbarProgressState: string
  taskbarProgress: number
  hasTaskbarOverlayIcon: boolean
  cursorVisible: boolean
  cursorGrab: string
  cursorHitTest: boolean
  cursorX?: number
  cursorY?: number
  representedFile: boolean
  documentEdited: boolean
  nativeTabbing: boolean
  nativeTabCount: number
  nativeSelectedTab?: number
  nativeTabBarVisible: boolean
  nativeTabOverviewVisible: boolean
  nativeTabsTruncated: boolean
}

/** Apply one fire-and-forget application-shell mutation. */
export declare function performAppMutation(app: number, action: string, value?: string | undefined | null): void

/** Start one application-shell service whose outcome arrives as an `app-service` event. */
export declare function performAppService(app: number, request: number, action: string, value?: string | undefined | null): void

export declare function performGlobalShortcutAction(app: number, request: number, action: string, registration?: number | undefined | null, accelerator?: string | undefined | null): void

export declare function performHostedAppMutation(app: number, action: string, value?: string | undefined | null): void

export declare function performHostedAppService(app: number, request: number, action: string, value?: string | undefined | null): Promise<void>

export declare function performHostedGlobalShortcutAction(app: number, request: number, action: string, registration?: number | undefined | null, accelerator?: string | undefined | null): Promise<void>

export declare function performHostedNotificationPermissionRequest(app: number, request: number, prompt: boolean): Promise<void>

export declare function performHostedShellAction(app: number, request: number, action: string, value: string): Promise<void>

export declare function performHostedWindowAction(app: number, window: number, action: string, value?: string | undefined | null): void

export declare function performHostedWindowImageAction(app: number, window: number, action: string, image?: NativeImageSource | undefined | null, description?: string | undefined | null): void

export declare function performNotificationPermissionRequest(app: number, request: number, prompt: boolean): void

export declare function performShellAction(app: number, request: number, action: string, value: string): void

export declare function performWindowAction(app: number, window: number, action: string, value?: string | undefined | null): void

export declare function performWindowImageAction(app: number, window: number, action: string, image?: NativeImageSource | undefined | null, description?: string | undefined | null): void

export declare function prepareApp(app: number): void

export declare function prepareHostedApp(app: number): Promise<void>

export declare function protocolVersion(): number

/** Return `-1` while running or the non-negative native exit code after termination. */
export declare function pumpApp(app: number, timeoutMs?: number | undefined | null): number

export declare function readClipboard(app: number): NativeClipboardItem | null

export declare function readFindClipboard(app: number): NativeClipboardItem | null

export declare function readHostedClipboard(app: number): Promise<NativeClipboardItem | null>

export declare function readHostedFindClipboard(app: number): Promise<NativeClipboardItem | null>

export declare function registerProtocol(options: NativeProtocolRegistrationOptions): Promise<void>

export declare function relaunchApp(app: number, options: NativeRelaunchOptions): boolean

export declare function relaunchHostedApp(app: number, options: NativeRelaunchOptions): Promise<boolean>

export declare function releaseHostedSingleInstanceLock(app: number): Promise<boolean>

export declare function releaseSingleInstanceLock(app: number): boolean

export declare function removeCrashExtraParameter(key: string): Promise<boolean>

export declare function removeHostedTrayIcon(app: number, request: number, id: number): Promise<void>

export declare function removeTrayIcon(app: number, request: number, id: number): void

export declare function requestAppQuit(app: number): boolean

export declare function requestFileIcon(app: number, request: number, path: string, size: string): void

export declare function requestHostedAppQuit(app: number): Promise<boolean>

export declare function requestHostedFileIcon(app: number, request: number, path: string, size: string): Promise<void>

export declare function requestHostedSingleInstanceLock(app: number, identifier: string): Promise<boolean>

export declare function requestPermission(kind: string): Promise<string>

export declare function requestSingleInstanceLock(app: number, identifier: string): boolean

export declare function runAppHost(onReady?: (() => void) | undefined | null): number

export declare function setApplicationMenu(app: number, menu: string): void

export declare function setDockBadge(app: number, value?: string | undefined | null): void

export declare function setDockIcon(app: number, icon?: NativeImageSource | undefined | null): void

export declare function setDockMenu(app: number, menu?: string | undefined | null): void

export declare function setHostedApplicationMenu(app: number, menu: string): void

export declare function setHostedDockBadge(app: number, value?: string | undefined | null): void

export declare function setHostedDockIcon(app: number, icon?: NativeImageSource | undefined | null): void

export declare function setHostedDockMenu(app: number, menu?: string | undefined | null): void

export declare function setHostedQuitInterception(app: number, intercepting: boolean): void

export declare function setHostedTrayIcon(app: number, request: number, options: NativeTrayIconOptions): Promise<void>

export declare function setHostedUserTasks(app: number, request: number, tasks: Array<NativeUserTask>): Promise<void>

export declare function setQuitInterception(app: number, intercepting: boolean): void

export declare function setSecureStorage(service: string, account: string, secret: Buffer): Promise<void>

export declare function setTrayIcon(app: number, request: number, options: NativeTrayIconOptions): void

export declare function setUserTasks(app: number, request: number, tasks: Array<NativeUserTask>): void

export declare function showAboutPanel(app: number, options: NativeAboutPanelOptions): void

export declare function showAlertDialog(app: number, window: number | undefined | null, request: number, options: NativeDialogOptions): void

export declare function showHostedAboutPanel(app: number, options: NativeAboutPanelOptions): void

export declare function showHostedAlertDialog(app: number, window: number | undefined | null, request: number, options: NativeDialogOptions): Promise<void>

export declare function showHostedNotification(app: number, options: NativeNotificationOptions): Promise<void>

export declare function showHostedOpenDialog(app: number, window: number | undefined | null, request: number, options: NativeOpenDialogOptions): Promise<void>

export declare function showHostedSaveDialog(app: number, window: number | undefined | null, request: number, options: NativeSaveDialogOptions): Promise<void>

export declare function showHostedTrayMenu(app: number, request: number, id: number): Promise<void>

export declare function showHostedWindowPopupMenu(app: number, request: number, window: number, menu: string, x?: number | undefined | null, y?: number | undefined | null): Promise<void>

export declare function showNotification(app: number, options: NativeNotificationOptions): void

export declare function showOpenDialog(app: number, window: number | undefined | null, request: number, options: NativeOpenDialogOptions): void

export declare function showSaveDialog(app: number, window: number | undefined | null, request: number, options: NativeSaveDialogOptions): void

export declare function showTrayMenu(app: number, request: number, id: number): void

/** Present a native popup menu owned by one window; completion arrives as a `popup-menu` event. */
export declare function showWindowPopupMenu(app: number, request: number, window: number, menu: string, x?: number | undefined | null, y?: number | undefined | null): void

export declare function stageUpdate(update: NativeAvailableUpdate, destinationDirectory: string, options: NativeUpdateClientOptions): Promise<string>

export declare function stageUpdateWithProgress(update: NativeAvailableUpdate, destinationDirectory: string, options: NativeUpdateClientOptions, onProgress: (progress: NativeUpdateProgress) => void): Promise<string>

export declare function startApp(app: number): void

export declare function startCrashReporter(options: NativeCrashReporterOptions): Promise<string>

export declare function startHostedApp(app: number): Promise<void>

export declare function supportsDynamicProtocolRegistration(): boolean

export declare function takeEvents(app: number): Array<NativeEvent>

export declare function unregisterProtocol(options: NativeProtocolRegistrationOptions): Promise<boolean>

export declare function uploadPendingCrashReports(endpoint?: string | undefined | null): Promise<NativeCrashUploadSummary>

export declare function verifyUpdate(path: string, signature: string, options: NativeUpdateClientOptions): Promise<void>

export declare function waitForHostedEvents(app: number): Promise<HostedAppUpdate>

export declare function writeClipboard(app: number, item: NativeClipboardItem): void

export declare function writeFindClipboard(app: number, item: NativeClipboardItem): void

export declare function writeHostedClipboard(app: number, item: NativeClipboardItem): Promise<void>

export declare function writeHostedFindClipboard(app: number, item: NativeClipboardItem): Promise<void>
