/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function abortAppHost(message: string): void

export declare function applyBatch(app: number, window: number, batch: Buffer): number

export declare function applyHostedBatch(app: number, window: number, batch: Buffer): number

export declare function closeHostedWindow(app: number, window: number): boolean

export declare function closeWindow(app: number, window: number): boolean

export declare function createAnchoredWindow(app: number, parent: number, anchor: number, options?: NativeWindowOptions | undefined | null): number

export declare function createApp(): number

export declare function createHostedAnchoredWindow(app: number, parent: number, anchor: number, options?: NativeWindowOptions | undefined | null): number

export declare function createHostedApp(): number

export declare function createHostedWindow(app: number, options?: NativeWindowOptions | undefined | null): number

export declare function createWindow(app: number, options?: NativeWindowOptions | undefined | null): number

export declare function destroyApp(app: number): boolean

export declare function destroyHostedApp(app: number): boolean

export declare function focusHostedNode(app: number, window: number, node: number): boolean

export declare function focusNode(app: number, window: number, node: number): boolean

export interface HostedAppUpdate {
  events: Array<NativeEvent>
  exitCode?: number
}

export interface NativeDialogButton {
  label: string
  role?: string
}

export interface NativeDialogOptions {
  level?: string
  message: string
  detail?: string
  buttons: Array<NativeDialogButton>
}

export interface NativeEvent {
  kind: string
  window: number
  target: number
  value?: string
  paths?: Array<string>
  error?: string
}

export interface NativeFileDialogFilter {
  name: string
  extensions: Array<string>
}

export interface NativeOpenDialogOptions {
  files: boolean
  directories: boolean
  multiple: boolean
  title?: string
  prompt?: string
  directory?: string
  suggestedName?: string
  filters: Array<NativeFileDialogFilter>
  showsHiddenFiles: boolean
}

export interface NativeSaveDialogOptions {
  directory: string
  title?: string
  suggestedName?: string
  prompt?: string
  filters: Array<NativeFileDialogFilter>
  showsHiddenFiles: boolean
}

export interface NativeWindowOptions {
  title?: string
  width?: number
  height?: number
  minimumWidth?: number
  minimumHeight?: number
  background?: number
  titleBarStyle?: string
  trafficLightX?: number
  trafficLightY?: number
  transparent?: boolean
  blur?: boolean
  popupPlacement?: string
  popupGap?: number
  popupOffsetX?: number
  popupOffsetY?: number
  popupGrab?: boolean
  popupAcceptsKeyFocus?: boolean
}

export declare function protocolVersion(): number

/** Return `-1` while running or the non-negative native exit code after termination. */
export declare function pumpApp(app: number, timeoutMs?: number | undefined | null): number

export declare function runAppHost(onReady?: (() => void) | undefined | null): number

export declare function showDialog(app: number, window: number | undefined | null, request: number, options: NativeDialogOptions): void

export declare function showHostedDialog(app: number, window: number | undefined | null, request: number, options: NativeDialogOptions): void

export declare function showHostedOpenDialog(app: number, window: number | undefined | null, request: number, options: NativeOpenDialogOptions): void

export declare function showHostedSaveDialog(app: number, window: number | undefined | null, request: number, options: NativeSaveDialogOptions): void

export declare function showOpenDialog(app: number, window: number | undefined | null, request: number, options: NativeOpenDialogOptions): void

export declare function showSaveDialog(app: number, window: number | undefined | null, request: number, options: NativeSaveDialogOptions): void

export declare function startApp(app: number): void

export declare function startHostedApp(app: number): void

export declare function takeEvents(app: number): Array<NativeEvent>

export declare function waitForHostedEvents(app: number): Promise<HostedAppUpdate>
